#****DO NOT EDIT THIS MODULE****#
'''----------------------------------------------------------------------------------------------------------
MODULE                  :       FC_PROTOBUF_SENSITIVITY
PROJECT                 :       FX onto Front Arena
PURPOSE                 :       This module defines the protobuf components for the SensitivityData object.
DEPARTMENT AND DESK     :       All Departments and all Desks.
REQUASTER               :       FX onto Front Arena Project
DEVELOPER               :       Gavin Wienand (only added the module)
                                Generated by the protocol buffer compiler.
CR NUMBER               :       XXXXXX
-------------------------------------------------------------------------------------------------------------
'''

'''----------------------------------------------------------------------------------------------------------
Importing all relevant Python modules.
----------------------------------------------------------------------------------------------------------'''
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='SensitivityDefinition.proto',
  package='',
  serialized_pb='\n\x1bSensitivityDefinition.proto\"+\n\tBenchmark\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x05Value\x18\x02 \x01(\x01:\x01\x30\"6\n\x0f\x46PortfolioSheet\x12#\n\rSensitivities\x18\x01 \x03(\x0b\x32\x0c.Sensitivity\"H\n\x17\x46VerticalPortfolioSheet\x12-\n\x12YieldSensitivities\x18\x01 \x03(\x0b\x32\x11.YieldSensitivity\"C\n\x10ScopeSensitivity\x12\x0f\n\x07Version\x18\x01 \x01(\t\x12\x1e\n\x04Item\x18\x02 \x01(\x0b\x32\x10.SensitivityData\"-\n\x0bSensitivity\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x05Value\x18\x02 \x01(\x01:\x01\x30\".\n\x0fSensitivityData\x12\x1b\n\x08Workbook\x18\x01 \x01(\x0b\x32\t.Workbook\"\x91\x01\n\x08Workbook\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x39\n\x17\x46VerticalPortfolioSheet\x18\x02 \x01(\x0b\x32\x18.FVerticalPortfolioSheet\x12)\n\x0f\x46PortfolioSheet\x18\x03 \x01(\x0b\x32\x10.FPortfolioSheet\x12\x11\n\x06Number\x18\x04 \x01(\x05:\x01\x30\":\n\nYieldCurve\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x1e\n\nBenchmarks\x18\x02 \x03(\x0b\x32\n.Benchmark\"B\n\x10YieldSensitivity\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12 \n\x0bYieldCurves\x18\x02 \x03(\x0b\x32\x0b.YieldCurve')




_BENCHMARK = descriptor.Descriptor(
  name='Benchmark',
  full_name='Benchmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Name', full_name='Benchmark.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Value', full_name='Benchmark.Value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=74,
)


_FPORTFOLIOSHEET = descriptor.Descriptor(
  name='FPortfolioSheet',
  full_name='FPortfolioSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Sensitivities', full_name='FPortfolioSheet.Sensitivities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=130,
)


_FVERTICALPORTFOLIOSHEET = descriptor.Descriptor(
  name='FVerticalPortfolioSheet',
  full_name='FVerticalPortfolioSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='YieldSensitivities', full_name='FVerticalPortfolioSheet.YieldSensitivities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=204,
)


_SCOPESENSITIVITY = descriptor.Descriptor(
  name='ScopeSensitivity',
  full_name='ScopeSensitivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Version', full_name='ScopeSensitivity.Version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Item', full_name='ScopeSensitivity.Item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=206,
  serialized_end=273,
)


_SENSITIVITY = descriptor.Descriptor(
  name='Sensitivity',
  full_name='Sensitivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Name', full_name='Sensitivity.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Value', full_name='Sensitivity.Value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=275,
  serialized_end=320,
)


_SENSITIVITYDATA = descriptor.Descriptor(
  name='SensitivityData',
  full_name='SensitivityData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Workbook', full_name='SensitivityData.Workbook', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=322,
  serialized_end=368,
)


_WORKBOOK = descriptor.Descriptor(
  name='Workbook',
  full_name='Workbook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Name', full_name='Workbook.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='FVerticalPortfolioSheet', full_name='Workbook.FVerticalPortfolioSheet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='FPortfolioSheet', full_name='Workbook.FPortfolioSheet', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Number', full_name='Workbook.Number', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=371,
  serialized_end=516,
)


_YIELDCURVE = descriptor.Descriptor(
  name='YieldCurve',
  full_name='YieldCurve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Name', full_name='YieldCurve.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Benchmarks', full_name='YieldCurve.Benchmarks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=518,
  serialized_end=576,
)


_YIELDSENSITIVITY = descriptor.Descriptor(
  name='YieldSensitivity',
  full_name='YieldSensitivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Name', full_name='YieldSensitivity.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='YieldCurves', full_name='YieldSensitivity.YieldCurves', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=578,
  serialized_end=644,
)

_FPORTFOLIOSHEET.fields_by_name['Sensitivities'].message_type = _SENSITIVITY
_FVERTICALPORTFOLIOSHEET.fields_by_name['YieldSensitivities'].message_type = _YIELDSENSITIVITY
_SCOPESENSITIVITY.fields_by_name['Item'].message_type = _SENSITIVITYDATA
_SENSITIVITYDATA.fields_by_name['Workbook'].message_type = _WORKBOOK
_WORKBOOK.fields_by_name['FVerticalPortfolioSheet'].message_type = _FVERTICALPORTFOLIOSHEET
_WORKBOOK.fields_by_name['FPortfolioSheet'].message_type = _FPORTFOLIOSHEET
_YIELDCURVE.fields_by_name['Benchmarks'].message_type = _BENCHMARK
_YIELDSENSITIVITY.fields_by_name['YieldCurves'].message_type = _YIELDCURVE
DESCRIPTOR.message_types_by_name['Benchmark'] = _BENCHMARK
DESCRIPTOR.message_types_by_name['FPortfolioSheet'] = _FPORTFOLIOSHEET
DESCRIPTOR.message_types_by_name['FVerticalPortfolioSheet'] = _FVERTICALPORTFOLIOSHEET
DESCRIPTOR.message_types_by_name['ScopeSensitivity'] = _SCOPESENSITIVITY
DESCRIPTOR.message_types_by_name['Sensitivity'] = _SENSITIVITY
DESCRIPTOR.message_types_by_name['SensitivityData'] = _SENSITIVITYDATA
DESCRIPTOR.message_types_by_name['Workbook'] = _WORKBOOK
DESCRIPTOR.message_types_by_name['YieldCurve'] = _YIELDCURVE
DESCRIPTOR.message_types_by_name['YieldSensitivity'] = _YIELDSENSITIVITY

class Benchmark(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BENCHMARK

  # @@protoc_insertion_point(class_scope:Benchmark)

class FPortfolioSheet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FPORTFOLIOSHEET

  # @@protoc_insertion_point(class_scope:FPortfolioSheet)

class FVerticalPortfolioSheet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FVERTICALPORTFOLIOSHEET

  # @@protoc_insertion_point(class_scope:FVerticalPortfolioSheet)

class ScopeSensitivity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCOPESENSITIVITY

  # @@protoc_insertion_point(class_scope:ScopeSensitivity)

class Sensitivity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENSITIVITY

  # @@protoc_insertion_point(class_scope:Sensitivity)

class SensitivityData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENSITIVITYDATA

  # @@protoc_insertion_point(class_scope:SensitivityData)

class Workbook(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKBOOK

  # @@protoc_insertion_point(class_scope:Workbook)

class YieldCurve(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _YIELDCURVE

  # @@protoc_insertion_point(class_scope:YieldCurve)

class YieldSensitivity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _YIELDSENSITIVITY

  # @@protoc_insertion_point(class_scope:YieldSensitivity)

# @@protoc_insertion_point(module_scope)
