
EXCLUDE_POSITIONS = [{"instrument":"ZAR/R189", "portfolio": "JOB2"},
{"instrument":"ZAR/R150", "portfolio": "JOB1"},
{"instrument":"ZAR/R159", "portfolio": "ALBI/GOVI Structures"},
{"instrument":"ZAR/ABL10A", "portfolio": "CD_CORPBONDS_NONCSA"},
{"instrument":"EUR/PORT/SOV/15APR2037", "portfolio": "CD_CORPBONDS_NONCSA"},
{"instrument":"ZAR/R157", "portfolio": "JOB1"},
{"instrument":"ZAR/R152", "portfolio": "JOB1"},
{"instrument":"ZAR/R203", "portfolio": "JOB1"},
{"instrument":"ZAR/R186", "portfolio": "JOB2"},
{"instrument":"ZAR/R150", "portfolio": "DERV2"},
{"instrument":"ZAR/R150", "portfolio": "JOB5"},
{"instrument":"ZAR/R150", "portfolio": "JOB2"},
{"instrument":"ZAR/R162", "portfolio": "DERV2"},
{"instrument":"ZAR/R162", "portfolio": "JOB2"},
{"instrument":"ZAR/R175", "portfolio": "JOB2"},
{"instrument":"ZAR/R184", "portfolio": "JOB2"},
{"instrument":"ZAR/E168", "portfolio": "JOB5"},
{"instrument":"ZAR/R153", "portfolio": "JOB5"},
{"instrument":"ZAR/R153", "portfolio": "JOB2"},
{"instrument":"ZAR/E170", "portfolio": "JOB5"},
{"instrument":"ZAR/E170", "portfolio": "JOB2"},
{"instrument":"ZAR/R152", "portfolio": "JOB10"},
{"instrument":"ZAR/R203", "portfolio": "JOB11"},
{"instrument":"ZAR/TFS84", "portfolio": "CD_CORPBONDS"},
{"instrument":"ZAR/R189", "portfolio": "JOB11"},
{"instrument":"ZAR/R189", "portfolio": "JOB11"},
{"instrument":"ZAR/R189", "portfolio": "JOB11"},
{"instrument":"ZAR/R189", "portfolio": "JOB11"},
{"instrument":"ZAR/R189", "portfolio": "JOB11"},
{"instrument":"ZAR/R189", "portfolio": "JOB11"},
{"instrument":"ZAR/WS05", "portfolio": "JOB11"},
{"instrument":"ZAR/WS05", "portfolio": "JOB11"},
{"instrument":"ZAR/WS05", "portfolio": "JOB11"},
{"instrument":"ZAR/R198", "portfolio": "JOB11"},
{"instrument":"ZAR/R198", "portfolio": "JOB11"},
{"instrument":"ZAR/R198", "portfolio": "JOB11"},
{"instrument":"ZAR/R203", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R202", "portfolio": "JOB11"},
{"instrument":"ZAR/R207", "portfolio": "DERV"},
{"instrument":"ZAR/FRB05", "portfolio": "CD_CORPBONDS"},
{"instrument":"ZAR/FRB05", "portfolio": "CD_CORPBONDS"},
{"instrument":"ZAR/R209", "portfolio": "DERV"},
{"instrument":"ZAR/SBKI11", "portfolio": "JOB11"},
{"instrument":"ZAR/SBKI11", "portfolio": "JOB11"},
{"instrument":"ZAR/R213", "portfolio": "JOB11"},
{"instrument":"ZAR/CBL12", "portfolio": "CD_CORPBONDS"}]

def exclude_bonds_hook(trade):
    portfolio = trade.Portfolio().Name()
    instrument = trade.Instrument().Name()
    exclude = False
    for instr, portf in EXCLUDE_POSITIONS:
        if instr == instrument and portf == portfolio:
            exclude = True
    return exclude
