""" Compiled: 2020-09-18 10:38:49 """

#__src_file__ = "extensions/confirmation/etc/FConfirmationUpdate.py"

def ApplyConfirmation(confirmation, confirmationToApply):
    confirmation.AcquirerAddress(confirmationToApply.AcquirerAddress())
    confirmation.AcquirerContact(confirmationToApply.AcquirerContact())
    confirmation.ArchiveStatus(confirmationToApply.ArchiveStatus())
    confirmation.ChaserCutoff(confirmationToApply.ChaserCutoff())
    confirmation.Checksum(confirmationToApply.Checksum())
    confirmation.CounterpartyAddress(confirmationToApply.CounterpartyAddress())
    confirmation.CounterpartyContact(confirmationToApply.CounterpartyContact())
    confirmation.ExpiryDay(confirmationToApply.ExpiryDay())
    confirmation.ManualMatch(confirmationToApply.ManualMatch())
    confirmation.ReceiverMethod(confirmationToApply.ReceiverMethod())
    confirmation.RecType(confirmationToApply.RecType())
    confirmation.ReferencedRecordAddress(confirmationToApply.ReferencedRecordAddress())
    confirmation.ReferencedRecordType(confirmationToApply.ReferencedRecordType())
    confirmation.SignOffStatus1(confirmationToApply.SignOffStatus1())
    confirmation.SignOffStatus2(confirmationToApply.SignOffStatus2())
    confirmation.Status(confirmationToApply.Status())
    confirmation.StatusExplanation(confirmationToApply.StatusExplanation())
    confirmation.Stp(confirmationToApply.Stp())
    confirmation.Text(confirmationToApply.Text())
    confirmation.Transport(confirmationToApply.Transport())
    confirmation.Type(confirmationToApply.Type())
    confirmation.AcquirerContactRef(confirmationToApply.AcquirerContactRef())
    confirmation.CashFlow(confirmationToApply.CashFlow())
    confirmation.ChasingConfirmation(confirmationToApply.ChasingConfirmation())
    confirmation.ConfInstruction(confirmationToApply.ConfInstruction())
    confirmation.ConfirmationReference(confirmationToApply.ConfirmationReference())
    confirmation.ConfTemplateChlItem(confirmationToApply.ConfTemplateChlItem())
    confirmation.CounterpartyContactRef(confirmationToApply.CounterpartyContactRef())
    confirmation.Diary(confirmationToApply.Diary())
    confirmation.EventChlItem(confirmationToApply.EventChlItem())
    confirmation.Receiver(confirmationToApply.Receiver())
    confirmation.Reset(confirmationToApply.Reset())
    confirmation.SignOffGroup1(confirmationToApply.SignOffGroup1())
    confirmation.SignOffGroup2(confirmationToApply.SignOffGroup2())
    confirmation.SignOffUser1(confirmationToApply.SignOffUser1())
    confirmation.SignOffUser2(confirmationToApply.SignOffUser2())
    confirmation.Trade(confirmationToApply.Trade())