""" Compiled: 2020-09-18 10:38:49 """

#__src_file__ = "extensions/confirmation/etc/FConfirmationFields.py"
field_dict = {}

# contact
field_dict['CONTACT'] = \
    ['ADDRESS', 'ADDRESS2', 'ATTENTION', 'CITY', 'COUNTRY', 'EMAIL', 'FAX',
     'FREE1', 'FREE2', 'FULLNAME', 'NETWORK2_ALIAS_SEQNBR',
     'NETWORK2_ALIAS_TYPE', 'NETWORK_ALIAS_SEQNBR', 'NETWORK_ALIAS_TYPE',
     'PTYNBR', 'TELEPHONE', 'ZIPCODE']

# contact rule
field_dict['CONTACTRULE'] = \
    ['ACQUIRER_PTYNBR', 'CURR', 'EVENT_CHLNBR', 'INSTYPE',
     'PRODUCT_TYPE_CHLNBR']

# confirmation
field_dict['CONFIRMATION'] = \
    ['CHASER_CUTOFF', 'CHASING_SEQNBR', 'CONFIRMATION_SEQNBR', 
     'CONF_TEMPLATE_CHLNBR', 'EVENT_CHLNBR', 'MANUAL_MATCH',
     'RESET_RESNBR', 'STATUS', 'STATUS_EXPLANATION', 'TRANSPORT', 'TRDNBR',
     'UPDAT_USRNBR', 'CFWNBR']

field_dict['SETTLEMENT'] = \
    ['ACQUIRER_ACCNAME', 'ACQUIRER_ACCOUNT', 'ACQUIRER_ACCOUNT_NETWORK_NAME',
    'ACQUIRER_PTYID', 'ACQUIRER_PTYNBR', 'AMOUNT', 'CFWNBR', 'COUNTERPARTY_PTYNBR', 
    'CURR', 'DELIVERY_TYPE', 'DIVIDEND_SEQNBR', 'FROM_PRFNBR', 'NETTING_RULE_SEQNBR', 
    'NOTIFICATION_DAY', 'ORG_SEC_NOM', 'PARTY_ACCOUNT', 'PARTY_ACCOUNT_NETWORK_NAME', 
    'PARTY_PTYID', 'PAYNBR', 'POST_SETTLE_ACTION', 'PRIMARY_ISSUANCE', 
    'REF_PAYNBR', 'RESTRICT_NET', 'SEC_INSADDR', 'SETTLED_AMOUNT', 
    'SETTLEINSTRUCTION_SEQNBR', 'STATUS', 'STATUS_EXPLANATION', 
    'TEXT', 'TO_PRFNBR', 'TRDNBR', 'TYPE', 'VALUE_DAY']

# instrument
field_dict['INSTRUMENT'] = \
    ['BARRIER', 'CALLABLE', 'CALL_OPTION', 'CONTR_SIZE', 'COUPONS',
     'COUP_RATE', 'CURR', 'DAYCOUNT_METHOD', 'DIGITAL', 'EX_COUP_METHOD',
     'EX_COUP_PERIOD', 'EXP_PERIOD', 'EXP_TIME', 'EXERCISE_TYPE',
     'EXOTIC_TYPE', 'EXP_DAY', 'INDEX_FACTOR', 'INSID', 'INSTYPE', 'ISSUE_DAY',
     'ISSUER', 'ISSUER_PTYNBR', 'LAST_COUP_DAY', 'NOTICE_PERIOD', 'OPEN_END',
     'ORIGINAL_CURR', 'ORIGINAL_INSADDR', 'PAY_DAY_OFFSET',
     'PAY_OFFSET_METHOD', 'PAYTYPE', 'PRODUCT_CHLNBR', 'PRODUCT_TYPE_CHLNBR',
     'PUTABLE', 'RATE', 'REBATE', 'SENIORITY_CHLNBR', 'SETTLEMENT', 'START_DAY',
     'STRIKE_CURR', 'STRIKE_PRICE', 'STRIKE_TYPE', 'UND_INSADDR', 'UND_INSTYPE']

# leg
field_dict['LEG'] = \
    ['AMORT_DAYCOUNT_METHOD', 'AMORT_END_DAY', 'AMORT_END_NOMINAL_FACTOR',
     'AMORT_END_PERIOD', 'AMORT_START_DAY', 'AMORT_START_PERIOD', 'AMORT_TYPE',
     'ANNUITY_RATE', 'BARRIER', 'CREDIT_REF', 'CURR', 'DAYCOUNT_METHOD',
     'DIGITAL', 'END_DAY', 'END_PERIOD', 'EXOTIC_TYPE', 'FIXED_COUPON',
     'FIXED_RATE', 'FLOAT_RATE', 'NOMINAL_FACTOR', 'PAYLEG', 'PAY_CALNBR',
     'PAY2_CALNBR', 'PAY3_CALNBR', 'PAY_DAY_METHOD', 'PAY_DAY_OFFSET',
     'RESET_CALNBR', 'RESET2_CALNBR', 'RESET3_CALNBR', 'RESET_DAY_METHOD',
     'RESET_DAY_OFFSET', 'RESET_PERIOD', 'RESET_TYPE', 'ROLLING_BASE_DAY',
     'ROLLING_PERIOD', 'SPREAD', 'START_DAY', 'START_PERIOD', 'STRIKE', 'TYPE']

# cash flow
field_dict['CASHFLOW'] = \
    ['END_DAY', 'EXCLUDE', 'FIXED_AMOUNT', 'FIXED_TIME', 'FLOAT_RATE_FACTOR',
     'FLOAT_RATE_FACTOR2', 'FLOAT_RATE_OFFSET', 'NOMINAL_FACTOR', 'PAY_DAY',
     'RATE', 'SPREAD', 'SPREAD2', 'START_DAY', 'STRIKE_RATE', 'TYPE']

# party
field_dict['PARTY'] = \
    ['ADDRESS', 'ADDRESS2', 'ATTENTION', 'CALCAGENT', 'CITY', 'CONTACT1',
     'CONTACT2', 'CORRESPONDENT_BANK', 'COUNTRY', 'DOCUMENT_DATE',
     'DOCUMENT_TYPE_CHLNBR', 'EMAIL', 'EXTERNAL_CUTOFF', 'FAX', 'FREE1',
     'FREE2', 'FREE3', 'FREE4', 'FREE5', 'FREE1_CHLNBR', 'FREE2_CHLNBR',
     'FREE3_CHLNBR', 'FREE4_CHLNBR', 'FULLNAME', 'FULLNAME2',
     'GUARANTOR_PTYNBR', 'INTERNAL_CUTOFF', 'ISDA_MEMBER', 'ISSUER',
     'LEGAL_FORM_CHLNBR', 'NOTIFY_RECEIPT', 'PARENT_PTYNBR', 'PTYID', 'PTYID2',
     'RED_CODE', 'SWIFT', 'TELEPHONE', 'TELEX', 'TIME_ZONE', 'TYPE', 'ZIPCODE']
                                                
# party alias
field_dict['PARTYALIAS'] = \
    ['ALIAS', 'PTYNBR', 'TYPE']

# agreement
field_dict['AGREEMENT'] = \
    ['COUNTERPARTY_PTYNBR', 'DATED', 'DOCUMENT_TYPE_CHLNBR', 'INSTYPE',
     'INTERNDEPT_PTYNBR', 'UND_INSTYPE']

# account
field_dict['ACCOUNT'] = \
    ['ACCOUNT', 'ACCOUNT2', 'ACCOUNT3', 'ACCOUNT4', 'ACCOUNT5', 'CURR', 'NAME',
     'SWIFT', 'SWIFT2', 'SWIFT3', 'SWIFT4', 'DETAILS_OF_CHARGES', 'BIC_SEQNBR',
     'BIC2_SEQNBR', 'BIC3_SEQNBR', 'BIC4_SEQNBR', 'BIC5_SEQNBR',
     'NETWORK_ALIAS_TYPE', 'NETWORK_ALIAS_SEQNBR', 'CORRESPONDENT_BANK_PTYNBR',
     'CORRESPONDENT_BANK2_PTYNBR', 'CORRESPONDENT_BANK3_PTYNBR',
     'CORRESPONDENT_BANK4_PTYNBR', 'CORRESPONDENT_BANK5_PTYNBR',
     'INTERNAL_CUTOFF', 'EXTERNAL_CUTOFF', 'ACCOUNT_TYPE']

# reset
field_dict['RESET'] = \
    ['CFWNBR', 'DAY', 'END_DAY', 'LEGNBR', 'READ_TIME', 'START_DAY', 'TYPE',
     'VALUE']

# trade
field_dict['TRADE'] = \
    ['ACQUIRE_DAY', 'ACQUIRER_PTYNBR', 'BROKER_PTYNBR',
     'CALCAGENT', 'CONNECTED_TRDNBR', 'CONTRACT_TRDNBR', 'CORRECTION_TRDNBR',
     'COUNTERPARTY_PTYNBR', 'CURR', 'DOCUMENT_TYPE_CHLNBR', 'FEE', 'INSADDR',
     'MIRROR_TRDNBR', 'OPTKEY2_CHLNBR', 'OPTKEY1_CHLNBR',
     'OPTKEY3_CHLNBR', 'OPTKEY4_CHLNBR', 'ORIGINAL_CURR', 'PREMIUM', 'PRICE', 
     'QUANTITY', 'QUOTATION_SEQNBR', 'SETTLE_CATEGORY_CHLNBR', 'TIME', 
     'TRADE_CURR', 'TRX_TRDNBR', 'TYPE', 'VALUE_DAY', 'YOUR_REF']


# trade account link
field_dict['TRADEACCOUNTLINK'] = \
    ['ACCNBR', 'CURR', 'PARTY_TYPE', 'SEC_ACCNBR', 'SEC_SETTLE_CF_TYPE',
     'SETTLE_CF_TYPE', 'SETTLE_DELIVERY_TYPE', 'SETTLE_SEQNBR']

# payment
field_dict['PAYMENT'] = \
    ['ACCNBR', 'AMOUNT', 'CURR', 'OUR_ACCNBR', 'PAYDAY', 'PTYNBR', 'TEXT',
     'TYPE', 'VALID_FROM']

# exotic
field_dict['EXOTIC'] = \
    ['AVERAGE_METHOD_TYPE', 'AVERAGE_STRIKE_TYPE', 'BARRIER_MONITORING',
     'BARRIER_OPTION_TYPE', 'BARRIER_REBATE_ON_EXPIRY', 'CHOOSER_CALL_STRIKE',
     'CHOOSER_DATE', 'CHOOSER_PUT_STRIKE', 'CLIQUET_OPTION_TYPE',
     'COUPON_CREDIT', 'DIGITAL_BARRIER_TYPE', 'DOUBLE_BARRIER',
     'FORWARD_START_DATE', 'FORWARD_START_TYPE', 'GLOBAL_CAP', 'GLOBAL_FLOOR',
     'INS_SERIES_TYPE', 'INSADDR', 'LADDER_DISCRETE_MONITORING', 'LOCAL_CAP',
     'LOCAL_FLOOR', 'LOOKBACK_DISCRETE_MONITORING', 'LOOKBACK_EXTREME_VALUE',
     'LOOKBACK_OPTION_TYPE', 'POWER_EXPONENT', 'POWER_GEARING',
     'RAINBOW_OPTION_TYPE', 'RANGE_ACCRUAL_AMOUNT', 'RANGE_ACCRUAL_CAP',
     'RANGE_ACCRUAL_FLOOR', 'VARIANCE_DIV_ADJ_RETURNS', 'VARIANCE_FACTOR',
     'VARIANCE_SWAP_TYPE']

# exotic event
field_dict['EXOTICEVENT'] = \
    ['DATE', 'END_DATE', 'INSADDR', 'TYPE', 'VALUE']

# exercise event
field_dict['EXERCISEEVENT'] = \
    ['EXP_TIME', 'DAY', 'NOTICE_DAY', 'NOTICE_PERIOD', 'PERIOD', 'SETTLE_DAY',
     'SETTLE_PERIOD', 'START_DAY', 'START_PERIOD', 'STRIKE', 'TYPE']

# credit event
field_dict['CREDITEVENTSPEC'] = \
    ['BANKRUPTCY', 'DEFAULT_DATE', 'DELIV_OBL_INSADDR',
     'DEL_OBL_CATEGORY_CHLNBR', 'FAILURE_TO_PAY', 'OBL_ACCELERATION',
     'OBL_CATEGORY_CHLNBR', 'OBL_DEFAULT', 'RECOVERY_RATE', 'REPUDIATION',
     'RESTRUCTURING_TYPE']

# combination link
field_dict['COMBINATIONLINK'] = \
    ['OWNER_INSADDR', 'MEMBER_INSADDR', 'WEIGHT', 'FIX_FX_RATE',
     'ORDERBOOK_OID', 'DEFAULT_DATE', 'RECOVERY_RATE', 'RESTRUCTURING_TYPE']