error_code_mapping = {"S429":"Settlement Amount Mismatch",
"S430":"Trade quantity Mismatch",
"S432":"Securities Movement Type Mismatch",
"S624":"Trade Already Associated with BTBReference",
"4039":" Settlement Date should be greater than Trade Date",
"4027":" Calender Details Does not Exist for the Trade Date",
"4036":" SellOrder Date should be current business Date",
"4015":" Seller Account No. Not Found",
"4009":" Role of Seller BP Not Active",
"4002":" Exchange BPID Not Active",
"9000":"Invalid Security/De-issued Or Reduction amount should be equal to or less thanIssued amount/Invalid Nostro should be present in any of the SOR accounts apart from Issuer SOR for De-Issuance/CSDP Or Issuer Code Or Issuer Ac No Or IA does not match/User not eligible",
"N726":"Entitlement amount should not be zero",
"O999":"Primary matching parameters cannot be Modified",
"MS01":"Invalid Trade Status/BPID role is invalid",
"2060":"Trade Cannot be Cancelled, It is In BTB Link",
"O444":"Invalid Trade Status",
"DM69":"Invalid Order Status",
"DM74":"Invalid Instrument ID for the request",
"DM72":"Participant reference must be unique",
"DM80":"Duplicate Certificate Details",
"DM30":"Effective date should be before Maturity Date for Fixed Income instruments",
"3333":"Trade cannot create - settlementdate should not greater or equal of delistingdate",
"4448":"BROK not active",
"DM88":"Confirmation Date should be current date",
"S635":"There are duplicates orders in the BTB request",
"PV01":"Invalid Quantity For Settlement Type PMO/RMO",
"O786":"Trade Qty should not be zero/Sett Quantity should not be zero for VP trades",
"2036":"Commited Trade Cannot be Cancelled",
"5050":"SELLER_ACCOUNT_NO_NOT_IN_VALID_AC_TYPE",
"5052":"Account not in valid accounttype should be normal account",
"5056":"Participantref and 20C TRRF ref should be Same",
"S690":"Instructing Party of BTBReference is not the CSD Party of Trade",
"TCM1":"Instrument not eligible for TCMS transactions and instrument is not in active status",
"AC00":"Ac no not in valid status",
"4447":"Broker not active",
"D007":"Instructing party does not exists",
"4449":"Instructing party does not have Exchange role",
"D006":"Invalid Group Reference Number",
"4453":"Settlement date mismatch for the Group Reference",
"D003":"Participant Reference already exists",
"D004":"Committed EQTY On market trades cannot be cancelled",
"D010":"Trade does not exists",
"D011":"Instructing party is invalid",
"D013":"DPL is not allowed on SLB Intermediate transactions",
"D015":"BTB is not allowed on SLB Intermediate transactions",
"D017":"Sender is invalid for this Allegement Rejection",
"D019":"Nominal Value is more than OutStanding Loan",
"D021":"Nominal Value is more than OutStanding Collateral",
"D022":"Statement Date must be Current Business Date",
"D024":"Intrument not in Active Status",
"D026":"Transaction Reference Already Exists",
"D028":"TradeReference is InValid",
"D031":"Instructing Party is not matching with the Sender",
"D034":"Failed Trade Management Already In Progress for the Instrument",
"D030":"Failed Trade Management Already Completed for the Instrument",
"D035":"Failed Trade Management has not been Initiated for the Instrument",
"D036":"Instrument is not matching with the Related Refrence",
"D038":"Instrument is not listed for the Exchange",
"D039":"ISIN mismatch for the Group Reference",
"5400":"tradeReference mismatch",
"0075":"Only owner of DP can Modify Address Details/First Amortisation Date Cannot be a Holiday. OR First Amortisation Date Cannot be a Holiday.",
"0076":"Only owner of DP can Modify Address Details/Call Date Cannot be a Holiday OR Call Date Cannot be a Holiday",
"0077":"Only owner of DP can Modify Address Details/Issue Date Cannot be a Holiday. OR Issue Date Cannot be a Holiday.",
"0079":"Only owner of DP can Modify Address Details/MATURITY_DATE_DATE_LESS_THAN_CURRENT_DATE OR MATURITY_DATE_DATE_LESS_THAN_CURRENT_DATE",
"0080":"Only owner of DP can Modify Address Details/ENTITY_DETAILS_NOT_FOUND OR ENTITY_DETAILS_NOT_FOUND",
"0082":"Only owner of DP can Modify Address Details/Issue Date Cannot be a Past Business Date OR Issue Date Cannot be a Past Business Date",
"0084":"Account is already in Freezed Status/Mandatory Field Maturity Date Not Specified OR Mandatory Field Maturity Date Not Specified",
"0085":"Account is already in Active Status/Failed in deriving business date for next payment date OR Failed in deriving business date for next payment date",
"0086":"Account is already in Closed Status/Calendar details not available OR Calendar details not available",
"0088":"Account Cannot be deleted since account balance is not NIL OR BP Does Not Exist (Fund BP / Issuer Cd)",
"0089":"Coporate CSDP is not eligible to create an account for the requested client/Client BP and Account number does not match OR BP Does Not Have Role As Issuer",
"0090":"ID Numbers and requested Client BP does not match/ISSUER ROLE NOT IN ACTIVE STATUS OR BP NOT ACTIVE (Fund BP / Issuer Cd)",
"0093":"Additional Address Creation Failed OR BP Does Not Have Role As Stock Exchange",
"0094":"Additional Address Creation Failed OR EXCHANGE_BPID_NOT_ACTIVE",
"0095":"Additional Address Creation Failed OR STK_EXCHNG_ROLE_NOT_IN_ACTIVE_STATUS",
"0096":"Additional Address Creation Failed OR INSTRUMENT CATEGORY NOT FOUND",
"1011":"Sender ID and Associated DP are not the same",
"1004":"Bpid already exists",
"1021":"Invalid idType",
"1025":"Invalid Nature Of Incorporation",
"1071":"Invalid Sector Code",
"1072":"Default Address Already Exists",
"1073":"Additional Address1 Creation Failed",
"1074":"Additional Address2 Creation Failed",
"1075":"Additional Address3 Creation Failed",
"1076":"Additional Address4 Creation Failed",
"1080":"Client Category and Id type does not match - client category 1",
"1081":"Multiple Id Details creation failed/PrimaryDetails Modification Failed",
"1082":"Multiple Id Details creation failed for id type 2",
"1084":"Client Category and Id type doesn not matchclient category 4",
"1085":"Client Category and Id type does not matchclient category 5",
"1086":"Client Category and Id type does not match - client category 6",
"1087":"Client Category and Id type does not matchclient category 7",
"1088":"Client Category and Id type does not matchclient category 8",
"1089":"Client Category and Id type does not matchclient category 9",
"1090":"Client Category and Id type does not matchclient category 10",
"1091":"Invalid Nationality (International Country Code)",
"2021":"CLIENT BP ALREADY ASSOCIATED WITH THE DP OR Settlement Amount Mismatch",
"2023":"ID Number Already exists OR Transaction code is not matching with the original settlement instruction",
"2024":"Invalid Type of CSDP Role OR Securities Movement Type Mismatch",
"2026":"FDHD BPID Does Not Exists OR Place of Settlement is invalid or unrecognized",
"2027":"FDHD role details does not exist OR Delivering Party1 BIC is not matching with the original settlement instruction",
"2028":"Broker ID Does Not Exists OR Referenced settlement instruction is already cancelled",
"2031":"Broker id mandatory OR Deadline not found",
"0001":"Instrument ID is mandatory/BeneficiaryBIC is Incorrect OR beneficiaryBIC and lcl_CrdtBic not Equal",
"0002":"Instrument sub category is mandatory/PayeeBIC is Incorrect OR inComing ordringInstBIC and lcl_DebtBic Not equal-inside credit part",
"0003":"Face Value is mandatory/Settlement Amount is Incorrrect OR amount not Equal",
"0004":"othrPreferredName is mandatory/Settlement Date is Incorrect OR valuedate Not Equal",
"0005":"Instrument Form ismandatory/Currency is Incorrect OR Currency Not Equal",
"0006":"other Long Name is mandatory/Central Bank Role does not Exist fot BPID OR Invalid Role",
"0007":"Issuer Type is mandatory/Sender of Message and Settling Bank is Incorrect OR Not SAMOS",
"0008":"issuePrice is mandatory",
"0010":"Maturity Date is mandatory/Incorrect Strate Reference No. / Strate Reference Does not Exist OR Transaction reference does not exists",
"0011":"Maturity Value is mandatory",
"0012":"Nominal Multiplier is mandatory",
"0015":"Mandatory Capital is mandatory",
"0017":"Issuer A/C is mandatory",
"0020":"Subscription start Date is mandatory",
"0022":"FISN Code is mandatory",
"0025":"Minimum Multiple Quantity is mandatory",
"0027":"Form ismandatory",
"0030":"Reserve Balance is mandatory",
"0032":"Coupon Calculation Method is mandatory",
"0035":"Coupon Rate is mandatory",
"0037":"Previous Coupon Date is mandatory",
"0040":"Compounding Frequency is mandatory",
"0042":"Variance Type is mandatory",
"0045":"Floor Rate is mandatory",
"0048":"Next Reset Dateis mandatory",
"0050":"Redemption Type is mandatory",
"0053":"Actual Redemption Date is mandatory",
"0055":"Amortisation Frequency is mandatory",
"0057":"Book Close Days is mandatory",
"0059":"ISIN Generation Category is mandatory",
"0062":"Instrument Flag Should be NO for Domestic Intruments",
"0063":"Instrument Flag Should be YES for Foreign Intruments",
"0066":"COUNTRY NOT IN ACTIVE STATUS",
"0069":"Subscription Start Date Cannot be a Holiday.",
"0070":"Subscription End Date Cannot be a Holiday",
"0097":"INSTRUMENT SUB CATEGORY NOT FOUND",
"0099":"EXPIRY_DATE_CANNOT_BE_ENTERED_ON_A_HOLIDAY",
"0101":"LINKED_INSTRUMENT_NOT_ACTIVE",
"0103":"Modification is not allowed for Active Instruments",
"0105":"Issued Amount and Authorized Amount are Mandatory for Creating an Instrument",
"0106":"Issued Amount is Mandatory for Creating an Instrument",
"0107":"Authorized amount should be greater than Issued Amount",
"0108":"Issuer Type and Issuer A/C is Mandatory for Creating an Instrument",
"0111":"Account does not exist",
"0113":"Subscription End Date should not be greater than Maturity Date",
"0114":"Programme Id is mandatory for Zero Coupon Instruments",
"0116":"Issuer Id does not match with the corresponding Programme Id",
"0117":"Form doesnot match with the corresponding Programme ID",
"0118":"Guarantee doesnot match with the corresponding Programme ID",
"0119":"Instrument Category doesnot match with the corresponding Programme ID, Issue Amount does not match with the corresponding Issuer Link Details",
"0120":"Currency doesnot match with the corresponding Programme ID",
"0122":"Underlying Product not in active status",
"0124":"Symboldetails created successfully",
"0127":"Original Issue Date is mandatory / Call Put Indicator is mandatory",
"0129":"Market is mandatory",
"0132":"Source of ISIN Creation is mandatory",
"0134":"Authorized Capital is mandatory",
"0136":"Specified Ticker Name is already present in system",
"0138":"Symbol details not found",
"0140":"Instrument details not found",
"0143":"Maturity date should be greater than issue date",
"0144":"Paid Up value cannot be greater than par value",
"0146":"Hair Cut Margin can be specified only if Collateral Eligibility is Yes",
"0147":"Lending Limit can be specified only if Lending Ind is YES",
"0149":"Original Issue Date Cannot be a Holiday",
"0151":"ISIN Range Exceeds",
"0153":"No Record exists in ISIN Generation Logic for Default",
"0155":"Issuer cannot create instrument of this type.",
"0156":"Maturity value should be equal to the Face value",
"0158":"Maturity Date Should Not Be A Holiday",
"0160":"Instrument belongs to Flexi bond (Category 4)",
"0163":"Last Payment Date Should be Greater than Issue Date",
"0164":"Next Interest Payment Date is greater than Maturity Date",
"0166":"Next and Last payment Date is less than start date of interest payment",
"0167":"Issue price should not be specified forbills",
"0169":"Trading Details Cannot be created for unlisted instruments",
"0170":"No. of days is mandatory for Creating Fixed Income",
"0172":"Invalid FISN Code",
"0174":"Underlying Asset Type is mandatory",
"0177":"Modified Authorized amount should not be less than the Issued Amount of the instrument",
"0178":"Issued Amountshould notbe greater than the Authorised Amount",
"0179":"Issued Amountshould notbe lesserthan the Issued Nominal Amount",
"0180":"Version Mismatch when updating Issued/Authorised amount",
"0182":"Associated Agentalready exists",
"0184":"Instrument already in Deleted Status",
"0186":"Version mismatch found when updating Debt",
"0187":"Version mismatch found when updating Equity",
"0189":"Interest details are not found for the instrument",
"9806":"INVALID COUNTER BTB NUMBER",
"0192":"OwnershipOrTransfer is mandatory",
"0194":"Distribution Principle is mandatory",
"0196":"Call Date should not be greater than Maturity Date",
"0198":"Fund BP should haveIssuer / Issuer Agent Role",
"0199":"Maturity date must be greater than current date :",
"0201":"Maturity Date Cannot be a Holiday",
"0204":"CANNOT CREATE OPTION FOR FUTURE SYMBOL",
"0205":"Mismatch between Currency specified and the Currency in Symbol Exchange Association",
"0206":"Currency not found in Symbol Exchange Association. Currency should be specified",
"0208":"Associated Agent does not Exist",
"0210":"Business partner does not have required role for this agent type",
"0212":"Nostro Account is not available for Issuer Agent/Invalid Security ID OR Invalid Security ID",
"0213":"Link doesnot exist between Agent ID and corresponding Program ID - Issuer Agent ID",
"0214":"Link doesnot exist between Agent ID and corresponding Issuer ID",
"0215":"Account not in Open or Active Status",
"0216":"Account NO not in Normal or Settlement Account Type or Issuer Account Type",
"0218":"Instrument doesnt exist",
"0220":"Agent Details Not Applicable for Index Instruments",
"0222":"Instrument Not In In-Capture Or Active Status - Cannot Create/Modify/Delete",
"0223":"Expiry Date Cannot Be Past Dated",
"0225":"Expiry Date cannot be less than Issue Date",
"0227":"Last Trading Date Cannot Be Past Dated",
"0229":"First Issue Date Cannot Be Past Dated",
"0230":"Subscription Start Date Cannot Be Past Dated",
"0232":"Subscription End Date Cannot Be greater than Expiry Date",
"0234":"First Amortisation Date should not be lesser than Issue date",
"0235":"Calendar details not available for calculated Next Payment Date",
"0237":"To Be Deleted Instrument cannot be modified",
"0239":"Suspended Instrument cannot be modified",
"0240":"Progarmme ID is mandatoryif Programme Association is selected as YES",
"0242":"Issued Amount is not specified for Issuer Role",
"0245":"Equity details not found",
"0247":"Housing company details not found",
"0249":"Mutual Fund details not found",
"0251":"JIBAR Rate Does Not Exist For Instrument",
"0253":"Mismatch between Preferred Name and Short Code",
"0255":"ACPC Indicator should be No for Category 3",
"0257":"Duplicate Transaction Reference for the Issuer Agent",
"0258":"DFLT Instrument ID does not found",
"0260":"Default Instrument is already processed",
"0263":"Action can be performed only by Primary IA",
"0265":"Next Coupon Date should be a Future Date",
"0268":"Instrument Already in Deleted Status",
"0270":"Withholding Tax Rate does not match with System defined Tax Rate",
"0271":"Last Payment Date is not equal to Maturity Date",
"0273":"Mismatch between SenderID and Issuer Agent BP Id",
"0274":"COUPON RESET START DATE MUST NOT BE IN THE PAST",
"0276":"COUPON RESET START DATE MUST NOT BE GREATER THAN MATURITY DATE",
"0277":"coupon reset date should not be greater than maturity date",
"0278":"Mismatch in MT598-155 and MT598-151",
"0904":"Modulo 10 validation for ISIN failed",
"2559":"Length of Alternate ID should not exceed 16 characters",
"BK78":"Invalid Issuer Agent",
"B003":"FE Does Not Exists for Instructing Party",
"B004":"FUNCTIONAL_ELIGIBILTY_IS_FROZEN_FOR_INSTRUCTING_PARTY",
"B006":"Depository Participant Role Does Not Exist For Instructing Party",
"B008":"CSDP must be Non Corporate ->Updated to INVALID_ACCREDITED_CUSTODIAN_FOR_BP_AFFI",
"B009":"TRPY Role Does Not Exists For Instructing Party",
"B011":"TRADE_DATE_SHOULD_BE_CURRENT_BUSINESS_DATE",
"B014":"STLMNT_DT_MUST_BE_LESS_THAN_MATURITY_DT_FOR_INSTR",
"B015":"The Instructing Party BPID and the BPID (first 8 characters)",
"B016":"The instrument should be valid and Active on the Settlement Date",
"B018":"Buyer BP Not Active",
"B020":"Seller BP Does Not Exist",
"B023":"If ITR is Not having min 8 digits .",
"B024":"Settlement Amount should be received as part of the message or captured from the screen for Settlement type DVP and RVP",
"B025":"Currency of trade price should be validated with instrument currency as defined in Instruments",
"B026":"Nominal Value of Securities should comply with'minimum tradable denomination' &'MINIMUM MULTIPLE QUANTITY' defined as part of Instruments",
"B027":"SOR_AC_DOES_NOT_EXIST",
"B029":"SOR Account should be linked to the respective CSD Participant // DEAG",
"B031":"Transaction Type Sell & Buy Back First Leg and the Second Leg can only be Versus Payment transactions",
"B032":"Transaction Type Sell & Buy Back,PortFolio Moves, Account Transfer should only have one trade allocation.",
"B033":"SETTLEMENT_DATE_NOT_A_VALID_BUSINESS_DATE",
"B034":"CALENDER_DETAILS_DOES_NOT_EXIST_FOR_THE_SETTLEMENT_DATE",
"B035":"On Settlement Date Cancellation Not Allowed for txntype = 60/61",
"B037":"INVALID_INSTR_STATUS (!=ACTI &! = ICPT)",
"B039":"SOR Account should be linked to the respective CSD Participant // DEAG",
"B040":"Cancellation Request Not Accepted //CANC - TransactionType -61 - on cancellation confirmation by same prty twice.",
"B042":"Settlement Amount is Mandatory for Versus Payment transactions",
"B043":"Nominal Value Should be Equal to Sum (Alloc Quantity)",
"B045":"DDL - Current Time Not within Deadline - Record Date DDL",
"B047":"DDL - Current Time Not within DeadlineNon Record Date",
"B093":"NOMINAL VALUE MUST HAVE A NON-ZERO POSITIVE NUMBER",
"BM89":"TAP IND'Y' IS ONLY ALLOWED FOR SETTL TYPE'DFP' AND'DVP'",
"BP79":"TAP REDU'Y' IS ONLY ALLOWED FOR SETTLEMENT TYPE'RFP' AND'RVP'",
"BN56":"THE ORDER TO BE MODIFIED IS NOT FOUND //Record not found to modify",
"BN71":"ISIN SHORT NAME IS NOT VALID",
"BP81":"TAP TOP UP NOMINAL VALUE MUST BE MULTIPLE OF MIN TRAD DENOMINATION",
"BP88":"FOR CLIENT TYPE 30 & 31, ONLY SETTLEMENT TYPE'DFP' OR'RFP' IS ALLOWED",
"BO80":"ITR-REF MUST BE SAME AS THE RELA-REF FOR MODIFICATION",
"BO78":"ISSR AGENT MUST BE IN ACTIVE STATUS",
"MO81":"REPURCHASE DATE MUST BE LESS THAN MATURITY DATE",
"BN50":"BULK SETTLEMENT AMOUNT DOES NOT MATCH WITH THE ALLOCATIONS",
"BP84":"TRADING/COUNTER PARTY MUST HAVE THE ROLE OF CSDP FOR CLNT TYPE 30 AND 31 //DEAG",
"BP85":"TRADING/COUNTER PARTY MUST HAVE THE ROLE OF CSDP FOR CLNT TYPE 30 AND 31 //DEAG",
"B353":"DUPLICATE TRADE RECEIVED",
"B065":"SECOND LEG RECORD NOT AVAILABLE",
"B061":"DATA NOT EXISTS FOR FIRST LEG //61 NEWM",
"BC01":"CANC Details and Accepted trade's Details doesn't Match",
"BC02":"CANC 170 - Trade already in cancelled status",
"BP14":"CalenderDoesNotexistForSystem - fixdrepodate",
"BI02":"92AINTR_IS_NOT_EQUAL_TO_INSTR_INTERESTRATE",
"BI04":"nextresetdate_NOT_EQUAL_TO_MFBDC_nextresetdate",
"BC03":"Given_CANC_ACNO_Does_not_Exists",
"BI06":"Instrument_not_eligible_for_Bulk_transactions",
"BO01":"RepoAmount should not be specified for OPEN Repo trades",
"BI08":"Only_MATU_DATE_is_Allowed_For_CAT1_Inst",
"BI09":"Incorrect_ISIN_Short_name",
"O003":"Buyer BIC not specified",
"O005":"Invalid Participant Reference",
"O008":"Account details invalid",
"O011":"Instructing Party and Sender should be same",
"O013":"Duplicate Participant Ref",
"O016":"Ac No. does not belong to specified Ac Owner",
"O018":"POA cannot create APMT trades",
"O020":"DP does not have access on account",
"O023":"Invalid linked omnibus account",
"O025":"Seller account inactive",
"O027":"AccountType invalid for client",
"O029":"Ac No. is not of Registered type for certified instrument",
"O031":"Seller should be default Registrar of Instrument",
"O033":"Settlement quantity is greater than issued amount",
"O034":"Instructing Party should be same as buyer",
"O037":"Client BPID does not belong to the Member BPID",
"O039":"AccountType not valid for member",
"O040":"Account No. is not of Registered type for certificated instrument",
"O042":"Buyer is not the issuer of the certified instrument",
"O044":"Trade currency not the base currency",
"O046":"Invalid settlement currency",
"O048":"Delivering party BIC should be same as account owners BIC",
"O049":"Receiving party BIC should be same as account owners BIC",
"O052":"Seller Securities Sub Balance ID cannot be specified by buyer",
"O053":"Seller Securities Sub Balance ID not found",
"O055":"Seller Securities Sub Balance ID invalid",
"O057":"Seller Securities Sub Balance ID inactive",
"O058":"Group 2 Restriction Registration is Pending in the account",
"O059":"Group 2 Restriction Registration is Pending in the account",
"O060":"Invalid Third Party Reference",
"O062":"Automated Transformation not supported after Record Date",
"O064":"Security not eligible for trading/Matching indicator should be MACH for BSEA BSEF and PRMT trades",
"O066":"Issuer Agent invalid",
"O069":"Switch not allowed for instrument",
"O071":"Settlement Link Indicator Invalid",
"O073":"Settlement Date mismatch",
"O075":"Settlement Bank Details not found",
"O201":"Functional Eligibilty is Frozen for Instructing Party",
"O203":"Functional Eligibilty is Frozen for Buyer",
"O204":"Functional Eligibilty does not Exist for Instructing Party",
"O206":"Functional Eligibilty does not Exist for Buyer",
"O208":"Seller not Active",
"O211":"Role does not exist for Seller",
"O213":"Seller does not have eligibility to transfer",
"O215":"Instructing Party does not have eligibility to transfer",
"O216":"Instrcting Party does Not Exist",
"O219":"Instructing Party does Not Exist",
"O250":"Unrecognized or Invalid Place of Settlement",
"O252":"Delivering Party not found",
"O255":"Seller Cash Account Invalid",
"O257":"Receiving Party BIC invalid",
"O260":"Buyer Cash Account Invalid",
"O262":"Buyer account does not exist",
"O265":"Settlement Date cannot be a past date",
"O267":"Trade Date is a holiday",
"O270":"Settlement Date Mismatch",
"O272":"Invalid trade currency",
"O275":"Seller cash account invalid",
"O277":"Buyer cash account invalid",
"O301":"Settlement quantity is less than minimun denomination",
"O302":"Settlement Quantity not a multiple of minimum multiple quantity of instrument",
"O304":"Instrument not found",
"O306":"Settlement Date is before Program Validity start date",
"O308":"Trade Date before Program Validity start date",
"O310":"Invalid settlement amount",
"O312":"Settlement date after subscription end date",
"O313":"Trade date before subscription start date",
"O316":"Buyer Cash Account Invalid",
"O402":"Invalid Custodian",
"O405":"Invalid To Balance Type",
"O408":"Sender ID Invalid",
"O411":"Invalid Seller Clearstream Account No",
"O413":"Invalid Buyer Clearstream Account No",
"O415":"Deadline Does Not Exist",
"O418":"Settlement Bank Details not found",
"O419":"Settlement Transaction condition indicator value invalid",
"O422":"Reference Already Exists in the System",
"O423":"Account No Mismatch",
"O427":"pledgorClientCode Mismatch",
"O429":"securityID Mismatch/settlementDate Mismatch",
"S419":"Instrument not eligible for TCMS transactions",
"S421":"Only Clearstream allowed to book trades on Collateral Reciever Accounts",
"S423":"Trade cannot be cancelled",
"S425":"Settlement Date Mismatch",
"S428":"Matching indicator mismatch",
"S431":"ISO Txn Code Mismatch",
"S433":"Payment Type Mismatch",
"O432":"Currency should not be in FreeofPayement",
"M344":"CSDP not authorized to commit",
"MP60":"Commit with MT598-101 for Tradesnot allowedwith NON Collateral Manager BPID",
"MP56":"Commit with MT598-101 for Pledges for Collateral not allowed",
"MP55":"Commit-Uncommit not allowed on past dated trades/Uncommit on uncommit not valid",
"8193":"Commit on commit not valid",
"8192":"Deadline Does Not Exist/Deadline time exceeded",
"S620":"Trades instrument Or SOR Account OR Settlement Date is not equal in all Trades",
"S621":"CommId doesnt exist for systemBPID",
"S623":"Instructing Party of BTBReference is not the CSD Party of Tradesss",
"S301":"Version_mismatch found",
"S303":"BTBSTATUS_NOT_SPECIFIED",
"S306":"Trade waiting for commit",
"S309":"TradeStatus is not in accepted mode",
"S311":"commit cannot be issued on already commited trade",
"S628":"invalid btb reference",
"S626":"Other than Bond Market Trades are not eligible for BTBREFERENCE",
"5044":"seller CSDP not active",
"2016":"Common Trade Reference is not matching with the original settlement instruction",
"2017":"Intended settlement Date is not matching with the original settlement instruction",
"2018":"Trade Date is not matching with the original settlement instruction",
"2020":"Matching indicator is not matching with the original settlement instruction",
"2025":"Invalid message type/ Payment type mismatch used for amendment",
"2030":"Receiving Party1 BIC is not matching with the original settlement instruction",
"2032":"intended deliveringPrty3BPID is not matching with the original deliveringPrty3BPID",
"2033":"intended deliveringPrty2ClntName is not matching with the original deliveringPrty2ClntName",
"2034":"intended receivingPrty2ClntName is not matching with the original receivingPrty2ClntName",
"2035":"intended receivingPrty3BPID is not matching with the original receivingPrty3BPID/ID 2 is not mandatory for this category",
"2052":"Trade Doesnot Exist'",
"4001":"instructing party is not valid(dependencylink)",
"3999":"Dependency link reference is not UNIQUE",
"3998":"Dependency link reference SHOULD BE SEPCIFIED",
"3996":"Transaction reference SHOULD BE SEPCIFIED",
"2518":"EM_TradeReference_Does_Not_Exist",
"3964":"Trade Satus is not Valid to Prcess the Request--dependencylinkref",
"3960":"Dependency link reference does not exist OR No Pending Trades to Remove",
"3962":"either tradereference or btbreference SHOULD BE SPECIFIED",
"3966":"Tradereference doesnot exist in dependency link table",
"4162":"BUYER_CLIENT_NOT_ASSOCIATED_WITH_THE_DEPOSITORY_PARTICIPANT",
"4165":"ACCOUNT DETAILS NOT FOUND",
"4444":"Buyer Trader/Broker is not active",
"5055":"Settlementdate should be business date or future date",
"5023":"Free Of Payment is not applicable to SARB Reverse REPO'S",
"5002":"Invalid DECU value",
"5005":"Invalid REAGvalue",
"5009":"Invalid Seller client Acno",
"5011":"IncorrectSettlementAmount",
"5040":"incorrect tradedate",
"5018":"dealType mismatch",
"5021":"guaranteedInd mismatch",
"4999":"locked in reference already exits",
"5099":"Money Market ISIN is not allowed in MT54x messages",
"5098":"versus payment is not applicable for client types 30 and 31",
"0541":"MISMATCH BETWEEN THE CSD ELIGIBLE AMOUNT AND IA ELIGIBLE AMOUNT",
"M908":"CORPORATE EVENT NOT FOUND",
"M162":"MISMATCH BETWEEN CORPORATE ACTION REFERENCE (CORP)",
"M163":"MISMATCH BETWEEN CORPORATE ACTION REFERENCE (CORP)",
"M164":"MISMATCH BETWEEN CORPORATE ACTION REFERENCE (CORP)",
"M910":"INVALID SETTLEMENT CYCLE DATE",
"M912":"INVALID SETTLEMENT AMOUNT",
"M411":"INVALID ISSUER ISSUING AGENT COMBINATION FOR ISIN",
"MP08":"INVALID PREVIOUS REFERENCE",
"MP69":"PAYMENT NOTIFICATION FROM IA IS EXPECTED ON RECON OR EXEC DATE",
"ZA01":"Feature Not Supported",
"4041":"Calender Details Does not Exist for the Settlement Date/Canc -Invalid Trade Status",
"4040":"CANC - Deadline Not exist",
"4038":" Deadline does not exist for trade creation",
"4034":" Invalid Currency",
"4031":" Holiday validation failed from CLD",
"4029":" Trade date is not a Valid Business Date",
"4028":" Holiday validation failed from CLD",
"4025":" Trade Qty Not a Multiple of Min Tradable Denomn",
"4024":" Trade Quantity Less Than Minimum Denomination",
"4035":" BuyOrder Date should be current business Date",
"4023":" Security ID not active",
"4020":" Buyer Account No. Not in Valid Status",
"4018":" Settlement Account for the Buyer BP Not Found",
"4016":" Seller Account No. Not in Valid Status",
"4014":" Settlement Account for the Seller BP Not Found",
"4013":" Role of Buyer BP Not Active",
"4010":" Buyer BP Does not Exist",
"4007":" Seller BP Not Active",
"4004":" Role of ExchangeNot Active",
"4089":"CSD BIC not valid",
"3968":"Trade is Already in DPL",
"2053":"Trade Cannot be Cancelled, If Counter Leg is In BTBReference",
"4998":"Committed or Partially Committed Trade legs cannot be cancelled",
"4446":"RECU not having CSDP Role",
"1953":"Issuer CSDP Does Not Exist",
"3995":"Instructingparty is not matching with ExistingInstructingParty of Dependencylink",
"3981":"Instrument is not matching with ExistingInstrument of Dependencylink",
"3983":"Instrument of All Trades are Not Same",
"3985":"One of the Trades in BTBReference is Already in DPL Reference",
"7300":"INVALID MESSAGE STRUCTURE",
"7303":"FORMAT ERROR",
"7310":"MISMATCH IN OCCURRENCE OF REPETITIVE STRUCTURE",
"7312":"UNEXPECTED PRESENCE OF FIELD",
"7316":"INVALID DATA IN KEYWORD",
"7309":"START OF TEXT NOT PRESENT",
"7398":"environment value mismatch",
"913":"Issue amount is not multiples of smallest tradeable denomination",
"2590":"Cannot create an instrument when IA link is closed",
"P001":"Current Cash State is 0",
"0906":"For CouponPaymentDay indicator ISDT and CouponPaymentDay value does not match with day of the issue",
"0905":"CouponPaymentDay indicator CLDT and CouponPaymentDay value does not match",
"B508":"Trader must be the issuer of the ISIN",
"P002":"Current Cash State is 2 and Instruction type is SUBSTITUTION(IN)",
"4888":"INVALID TRADEREFERENCE---LENGTH IS LESS THAN 13 ",
"DMA5":"INSTRUCTING PARTY NOT ELIGIBLE TO OPERATE THIS ACCOUNT",
"D001":"Invalid BPID in Group Reference",
"S629":"Both Deliverer and Reciever Order must be there for Adding a BTB",
"DMA1":"Investor BP does not exist",
"DMA3":"EXECUTION DATE IS PAST DATE NOT VALID",
"P006":"TransactionStatus is Invalid to process the Request",
"DMA8":"Account_not_In_Active_Status",
"P007":"Instructing Party is not PaymentBank or Service Provider",
"DM11":"INSTRUCTING PARTY SHOULD BE A DEPOSITORY PARTICIPANT",
"DM14":"Execution date b/w record and LDDR,Execution date and record and LDDR are same",
"DM16":"The total shares and consolid cert shares are not equal",
"DM18":"Buyers CSD participant must be the accredited custodian of the account",
"DM19":"The BP in 70E tag is not the instructing party",
"D042":"Failed Trade Management Already Marked Completed by the Exchange for the Instrument",
"5401":"securitiesTransactionType mismatch",
"D043":"Trade is Already in Uncommited Status",
"SDBR":"Deadline Exceeds,Settlement Date BTB Removal",
"TPFS":"Trades Picked for Settlement",
"1120":"CSDP No Already exists. MODF-Address1 creation Failed",
"1121":"CSDP No Already exists. MODF-Address2 creation Failed",
"1111":"Default address should have the address detail Number has 1",
"1118":"CSDP address NO of additional address-1 already exists",
"1114":"CSDP address NO of additional address-2 already exists",
"S631":"BTBReference Already moved for Settlement Process",
"3992":"Failed Trade Management Is In Progress for this Instrument",
"D041":"Settlement Date is after De-Listing date of ISIN",
"1122":"CSDP No Already exists. MODF-Address3 creation Failed",
"1123":"CSDP No Already exists. MODF-Address4 creation Failed",
"DM99":"Confirmation quantity is greater than the created quantity",
"0505":"Instrument is not a listed intr for the exch",
"S632":"Pledges are not allowed to link in BTB",
"0281":"Issue Date for the Instrument overlaps with other Instruments having same QUCD",
"0286":"Preferred name length cannot exceed 35 characters",
"0288":"Tax type is not applicable for Equities/Mutual funds/Housing companies",
"0997":"Price date can not be a holiday",
"0999":"ExchangeID should be primary for Given Instrument",
"0902":"Maturity event of instrument is already anticipatedt",
"0907":"Sum of Issue Amount and issue Capital is greater than 999999999999",
"0331":"COUPON RATE SHOULD BE GREATER THAN ZERO",
"1955":"Issuer CSDP Role is not Active",
"0909":"Nominal Value and Mininum tradable quantity validation failed ISSU",
"0908":"Minimum Tradable Denomination is zero ISSU",
"1976":"Programme Start date must be greater than issue date",
"1956":"Programme ID doesnt match with the corresponding Issuer Code",
"3237":"Maturity date is a holiday",
"3233":"Maturity date must be greater than current date",
"S5T5":"Commit Indicator is invalid",
"7777":"Ac no not in valid status-Dormant accnt not allowed for creation",
"8787":"Cancellation not allowed in Matched Ready for Settlement Status",
"2022":"Invalid Date(First Six Characters of SAID should contain date format YYMMDD) Invalid Date(First Eight Characters of DOB should contain date format CCYYMMDD)",
"5059":"Invalid Locked in Reference",
"0125":"IssueCapital is mandatory",
"2519":"Invalid Exchange Reference ETP",
"0267":"InterestCommencement Date Cannot be a Holiday.",
"B038":"SETTLEMENT_DATE_SHOULD_BE_AFTER_ISSUE_DATE_OF_INSTRUMENT",
"BP80":"FOR TAP REDU, SOR SHOULD BE THE SOR IN WHICH THE ISIN WAS ISSUED",
"BO97":"BULK REPO AMOUNT DOES NOT MATCH WITH THE ALLOCATIONS",
"BP84":"TRADING/COUNTER PARTY MUST HAVE THE ROLE OF CSDP FOR CLNT TYPE 30 AND 31 //DEAG",
"BP85":"TRADING/COUNTER PARTY MUST HAVE THE ROLE OF CSDP FOR CLNT TYPE 30 AND 31 //DEAG",
"B354":"SECOND LEG NOT IN CANCELLED STATUS",
"O051":"Invalid Securities Sub Balance Type",
"O052":"Seller Securities Sub Balance ID cannot be specified by buyer",
"O054":"Seller Securities Sub Balance ID invalid",
"O056":"Seller Securities Sub Balance ID invalid",
"O058":"Group 2 Restriction Registration is Pending in the account",
"O059":"Group 2 Restriction Registration is Pending in the account",
"O061":"Invalid Common Trade Reference",
"O063":"Security Matured",
"O064":"Security not eligible for trading/Matching indicator should be MACH for BSEA BSEF and PRMT trades",
"O066":"Issuer Agent invalid",
"O069":"Switch not allowed for instrument",
"O074":"Settlement Bank Details not found",
"O422":"Reference Already Exists in the System",
"O501":"Cash account is not linked to the safekeeping account owner Account Number And AccreditCustodian Mismatch Account Number And AccreditCustodian Mismatch",
"S419":"nstrument not eligible for TCMS transactions",
"S421":"Only Clearstream allowed to book trades on Collateral Reciever Accounts",
"S422":"Instruction could not be found",
"S424":"Duplicate Participant Reference",
"S427":"Instrument ID Mismatch",
"DMT0":"Settlement Date is after expiry date of ISIN",
"8":"Commit deadline exceeded",
"P008":"Currency is InValid",
"D303":"ISIN Status Invalid",
"0957":"Minimum Tradable Denomination Shoule be greater than or equal to100000for CPCM 1",
"0958":"Minimum Tradable Denomination Shoule be greater than or equal to1for CPCM 2 and 3",
"D666":"SETTLEMENTDATE AND RD DATE AND DELISTING DATE ARE NOT EQUAL",
"1125":"CSDP No Repeatedly Exists. MODF-Address creation Failed",
"RDNE":"Delisting date and settlement date is equal, and RD is not equal to settlement date",
"S431":"ISO Txn Code Mismatch",
"S433":"Payment Type Mismatch",
"S434":"Deadline Does Not Exist",
"4022":" Invalid Security ID",
"4012":" Buyer BP Does Not Have Broker Role",
"4005":" Exchange Reference already Exists",
"30012":"Invalid Status For Modification",
"DM71":"Invalid Participant reference",
"DM73":"Invalid order type for registrar confirmation",
"DM70":"Sender Id and instructing party mismatch",
"DM76":"NO BALANCE IN INVESTORS ACCOUNT",
"DM75":"Invalid Quantity",
"4488":"TradeReference Already Exists",
"RMT0":"Settlement Date is After Expiry Date of Instrument",
"3971":"There are duplicates orders in the DPL request",
"PV02":"Invalid BPID in Tag 26H",
"S634":"Invalid Order No and BTBreference combination",
"5051":"BUYER_ACCOUNT_NO_NOT_IN_VALID_AC_TYPE",
"5053":"Accountshould be a normal actype",
"5057":"Participantref is not available in System",
"NARR":"settlement instruction not found",
"DM77":"Quantity mismatch in cancellation",
"9090":"Settlement Date is not equal in all Trades",
"D008":"Instructing party not active",
"4450":"Instructing party does not have Lending Desk role",
"4452":"Commit/Uncommit is not allowed on SLB Intermediate transactions",
"4454":"Group Reference already exists",
"D005":"Guaranteed Indicator Should be Yes for Main Board orders",
"D009":"Cancellation is not allowed for this sender",
"D012":"Invalid trade status for cancellation",
"D014":"Instructing party is not eligible for BTB",
"D016":"Invalid Allegement Rejection Message",
"D018":"Loan Reference is Invalid",
"D020":"Collateral PoolReference is Invalid",
"D023":"Only Equity Intruments are allowed for Failed Trade Management",
"D025":"Intrument is Invalid",
"D027":"TradeReference and Instrument combination is Invalid",
"D029":"Confirmation Indicator is Invalid",
"D032":"Related Reference is Invalid",
"D033":"CSD Participant must be STRATE BPID",
"D037":"Trade is not in Valid Status to Process the Uncommit",
"2054":"Trade Cannot be Cancelled, If Trade is In BTB",
"P003":"Instruction Reference Already Exists",
"1092":"Country Code is Not ACTIVE",
"1094":"Country Code is Not ACTIVE",
"0009":"IssueSize is mandatory",
"0013":"Price Multiplier is mandatory",
"0014":"Interest Type is mandatory",
"0016":"Authorised Amount is mandatory",
"0018":"Programme ID is mandatory",
"0019":"Original Nominal Value is mandatory",
"0021":"Subscription End Date is mandatory",
"0023":"CFI Code is mandatory",
"0024":"Tax Rate is mandatory",
"0026":"Business Day Convention is mandatory",
"0028":"Guarantee is mandatory",
"0029":"Free Balance is mandatory",
"0031":"TaxType is mandatory",
"0033":"CouponFrequency is mandatory",
"0034":"No of Months is mandatory",
"0036":"Coupon Commencement Dt is mandatory",
"0038":"Next Coupon Date is mandatory",
"0039":"Calculation is mandatory",
"0041":"Source is mandatory",
"0043":"Variance Sign is mandatory",
"0044":"Variance is mandatory",
"0046":"Cap Rate is mandatory",
"0047":"Reset Frequency is mandatory",
"0049":"Last Reset Date is mandatory",
"0051":"Redemption (%%)",
"0052":"Book Closure Period is mandatory",
"0054":"Amortisation Rate is mandatory",
"0056":"First Amortisation Date is mandatory",
"0058":"Auto Corporate Action is mandatory",
"0060":"Technical ISIN is mandatory",
"0061":"Instrument Flag is mandatory",
"0064":"INVALID DOMAIN",
"0065":"INVALID COUNTRY",
"0067":"INVALID CURRENCY",
"0068":"CURRENCY NOT IN ACTIVE STATUS",
"0071":"First Coupon Date Cannot be a Holiday",
"0073":"Next Reset Date Cannot be a Holiday.",
"0098":"ClassId not found in the database",
"0100":"LINKED_INSTRUMENT_NOT_PRODUCTTYPE",
"0102":"LINKED_INSTRUMENT_DOES_NOT_EXIST",
"0104":"SUPD_DLET_IVLD_INSTR_CANT_BE_MODIFIED",
"0109":"iNVALID ACCOUNT",
"0110":"Invalid Issuer SOR account Type",
"0112":"Subscription End Date is lesser than Subscription Start Date",
"0115":"Program ID is notin Open or Activestatus",
"0121":"Underlying Product does not exist",
"0123":"Symbol details already exists",
"0126":"Paid Rate is Mandatrory",
"0128":"State of the Instrument is mandatory",
"0130":"Voting Rights is mandatory",
"0131":"Other Rights is mandatory",
"0133":"Expiry Date is mandatory",
"0135":"Invalid CFI Code",
"0137":"Invalid workflow status, Primary details can not modified",
"0139":"Symbol details modified successfully",
"0141":"Programme IDdoes not exist",
"0142":"Instrument Exists Already",
"0145":"Booking Basis - Should be Units for Equities",
"0148":"Original Issue Date Cannot be a Past Business Date",
"0150":"ISIN Start Range does not exist",
"0152":"ISIN Generation Failed due to version mismatch",
"0154":"ROLE DOES NOT EXIST FOR BP",
"0157":"Auto corporate action indicator should be redemption or none",
"0159":"Calendar Details Not Found For Maturity Date",
"0162":"Next Interest Payment Date is lesser than Last interest payment Date",
"0165":"Last Interest Payment Date is greater than Maturity Date",
"0168":"Mandatory Fields Are Not Specified",
"0171":"Issuer Agent does not have the privilege to create instrument",
"0173":"Instrument ID does not exist",
"0175":"Fund BPID is mandatory",
"0176":"Issuer Code is mandatory",
"0181":"Alternate ID already Exists",
"0183":"INSTR CANNOT BE DELETED WHEN IT IS IN SUSPENDED STATUS",
"0185":"Version mismatch found when updating Primary Details",
"0188":"Version mismatch found when updating MUTF",
"0190":"Redemption details are not found for the instrument",
"0191":"Instrument Status and Workflow should be in Active",
"0193":"Fund Type is mandatory",
"0195":"Call Date Cannot Be Past Dated",
"0197":"Actual Redemption Date Should be greater than the Issue Date",
"0200":"Maturity date must be greater than issue date :",
"0202":"Par Value is mandatory",
"0203":"Paid Up Value is mandatory",
"0207":"Instrument Flag should be NO",
"0209":"Associated Agent is not Active",
"0211":"Agent Role not in Active status",
"0217":"External Account Reference is Invalid",
"0219":"Agent Details Not Applicable for Derivatives",
"0221":"Agent Details Not Applicable for Commodities",
"0224":"Expiry Date cannot be less than Original Issue Date",
"0226":"First Trading Date Cannot Be Past Dated",
"0228":"Lock In End Date Cannot Be Past Dated",
"0231":"Subscription End Date Cannot Be Past Dated",
"0233":"Instrument ID format is invalid",
"0236":"Deleted Instrument cannot be modified",
"0238":"Invalid Instrument cannot be modified",
"0241":"Instrument is rejected",
"0243":"Debt details are not found",
"0244":"Debt details already exists",
"0246":"Equity details already exist",
"0248":"Housing company details already exists",
"0250":"Mutual Fund details already exists",
"0252":"Non-JIBAR Rate Does Not Exist For Instrument",
"0254":"ACPC Indicator should be No if CPMI ind is No for Category 2",
"0256":"Instrument Characteristics Matches",
"0259":"New Instrument ID Already Exists",
"0261":"Issuance Failed",
"0262":"Booking Failed",
"0264":"Next Coupon Date Cannot be a Holiday",
"0266":"Next Coupon Date should be less than Maturity Date",
"0269":"Ownership Ratio does not match",
"0272":"Next payment date should be greater tahn issue date",
"0275":"coupon reset date should be greater than issue date",
"0280":"Maturity Event has been anticipated",
"1854":"Issuer Agent BP is not Active",
"2012":"Invalid BIC for Issuer Agent",
"BK79":"Invalid Statement Date",
"BK77":"Ac No Does Not Exist",
"B001":"Instructing Party BP_DOES_NOT_EXIST",
"B002":"Instructing Party BP NOt Active",
"B005":"INSTRUMENT DETAILS NOT VALID",
"B007":"Depository Participant Role Not Active",
"B010":"TRPY Role Not Active",
"B012":"SETTLEMENT_DATE_CANNOT_BE_A_PAST_DATE",
"B017":"Buyer BP Does Not Exist",
"B019":"Trader Role Does Not Exist for Buyer BP- BROK",
"B021":"Seller BP Not Active",
"B022":"Trader Role Does Not Exist for Seller BP - BROK",
"B028":"SOR Account should be Active",
"B036":"BUYER_AND_SELLER_SHOULD_NOT_BE_SAME",
"B041":"Trades in Matched Status cannot be Modified",
"B046":"DDL - NoDeadlinesForInstParty Non Record Date",
"B049":"No Roletype found for instructing Prty - AFFI",
"BP80":"FOR TAP REDU, SOR SHOULD BE THE SOR IN WHICH THE ISIN WAS ISSUED",
"BO76":"FOR TAP-TOP-UP,TRADER MUST BE ISSUER FOR THE ISIN",
"BP17":"MODIFICATION IS NOT ALLOWED ON THE SECOND LEG OF SELL & BUY-BACK",
"BO79":"ISSR AGENT MUST BE IN ACTIVE STATUS",
"BO97":"BULK REPO AMOUNT DOES NOT MATCH WITH THE ALLOCATIONS",
"B354":"SECOND LEG NOT IN CANCELLED STATUS",
"B060":"First Leg NOT IN Settled Status //61 NEWM",
"BO88":"REPURCHASE DATE MUST BE GREATER THAN SETTLEMENT DATE",
"BP13":"REPURCHASE DATE IS NOT A BUSINESS DAY",
"BI01":"98AMATU_IS_NOT_EQUAL_TO_INSTR_MATURITYDT",
"BI03":"Nextpymntdate_NOT_EQUAL_TO_MFBDC_pymntdateDATE",
"BI05":"Next_Reset_Date_Details_Does_not_Exists",
"BC04":"98A_SETT_OR_98B_SETT_Is_Mandatory",
"BI07":"SORAcNo_not_eligible_for_Bulk_transactions",
"BC05":"61AUTOs CANC Not allowed for UNSETTLED 60",
"O001":"Receiving Party BIC not specified",
"O002":"Seller BIC not specified",
"O004":"Delivering Party BIC not specified",
"O006":"Invalid Value",
"O007":"Account details not specified",
"O009":"Account Reference invalid",
"O010":"Deadline Does Not Exist",
"O012":"Instructing party invalid",
"O014":"Invalid seller BP",
"O015":"Seller not eligible",
"O017":"CM not associated to DP",
"O019":"Instructing Party should be same as seller BP",
"O021":"Invalid Account Type",
"O022":"Settlement Bank Details not found",
"O024":"Invalid Seller account type",
"O026":"Seller Client BPID does not belong to the Member BPID",
"O028":"AccountType invalid for member",
"O030":"Seller is not the issuer of the certified instrument",
"O032":"Buyer not eligible",
"O035":"Invalid Buyer account type",
"O036":"Buyer account inactive",
"O038":"AccountType not valid for client",
"O041":"Buyer not an Issuer of instrument",
"O043":"Buyer is not the default Registrar of the Instrument",
"O045":"Settlement currency not the base currency",
"O047":"Settlement currency not active",
"O050":"Program is inactive",
"O051":"Invalid Securities Sub Balance Type",
"O054":"Seller Securities Sub Balance ID invalid",
"O056":"Seller Securities Sub Balance ID invalid",
"O061":"Invalid Common Trade Reference",
"O063":"Security Matured",
"O065":"Issuer Agent invalid",
"O067":"Instructing Party should be CSD",
"O068":"Invalid instrument type",
"O070":"Settlement Link Indicator not specified",
"O072":"Fund family name of ISINs do not match",
"O074":"Settlement Bank Details not found",
"O076":"Deadline time exceeded",
"O202":"Functional Eligibilty is Frozen for Seller",
"O205":"Functional Eligibilty does not Exist for Seller",
"O207":"Instructing Party not Active",
"O209":"Buyer not Active",
"O210":"Role does not exist for Instructing Party",
"O212":"Role does not exist for Buyer",
"O214":"Buyer does not have eligibility to transfer",
"O217":"Seller does Not Exist",
"O218":"Buyer does Not Exist",
"O220":"Seller does Not Exist",
"O221":"Buyer does Not Exist",
"O251":"Delivering Party BIC invalid",
"O253":"Delivering Party not active",
"O254":"Seller Cash Account Invalid",
"O256":"Seller account does not exist",
"O258":"Receiving Party does not exist",
"O259":"Receiving Party not active",
"O261":"Buyer Cash Account Invalid",
"O263":"Trade date not specified",
"O264":"Settlement Date not Business Date",
"O266":"Invalid Trade Date",
"O268":"Settlement Date is a holiday",
"O269":"Settlement Date is a holiday",
"O271":"Settlement Date earlier than Trade Date",
"O273":"Trade currency not in active status",
"O274":"Seller cash account inactive",
"O276":"Buyer cash account inactive",
"O300":"Settlement Date is before Effective Settlement Date of Instrument",
"O303":"Instrument not Active",
"O305":"Instrument not found",
"O307":"Settlement Date is after Program Validity end date",
"O309":"Trade Date after Program Validity end date",
"O311":"Settlement date before subscription start date",
"O314":"Trade date after subscription end date",
"O315":"Seller Cash Account Invalid",
"O400":"Invalid Custodian",
"O401":"Invalid Custodian",
"O403":"Invalid Custodian",
"O404":"Invalid From Balance Type",
"O406":"Invalid Instructing Party",
"O407":"Duplicate Participant Reference",
"O409":"Sender ID Invalid",
"O410":"Instructing party invalid",
"O412":"Invalid Seller Clearstream Account No",
"O414":"Invalid Buyer Clearstream Account No",
"O416":"Deadline Time Exceeds",
"O417":"Settlement Bank Details not found",
"O420":"Invalid Transaction Type",
"O421":"Invalid Instruction Type",
"O424":"Deliver leg Mismatch",
"O425":"pledgorCSDPPartiCode Mismatch",
"O426":"pledgeeCSDPPartiCode Mismatch",
"O428":"pledgeeClientCode Mismatch",
"O500":"Seller not Authorized to Trade",
"S420":"OptOut Indicator should be Yes for POA",
"S422":"Instruction could not be found",
"S424":"Duplicate Participant Reference",
"S426":"Trade date Mismatch",
"S427":"Instrument ID Mismatch",
"S429":"Settlement Amount Mismatch",
"S430":"Trade quantity Mismatch",
"S432":"Securities Movement Type Mismatch",
"S434":"Deadline Does Not Exist",
"O430":"Receiverleg Mismatch",
"5258":"Record does not exist",
"MP61":"Commit with MT598-101 for Trades allowedwith Instructing party",
"3431":"Invalid order status",
"7845":"Commit or uncommit not applicable on Pledge orders",
"S622":"BTBReference Already Exist",
"s624":"Trade Already Associated with BTBReference",
"S302":"NO_MATCHING_DETAILS_FOUND",
"S304":"TRADE_ASSOCIATED_WITH_BTBREFERENCE",
"S305":"AFFIRMATIONSTATUS_NOT_SPECIFIED",
"S307":"DEADLINE_DOES_NOT_EXIST",
"S308":"DEADLINE_NOT_MET",
"S310":"COMMIT_INDICATOR_MODIFIED_SUCCESSFUL",
"S312":"Trade is already fully commited",
"S625":"All Trades are not in Accepted or Matched Status",
"5045":"Buyer CSDP not active",
"2019":"Instrument ID is not matching with the original settlement instruction",
"3994":"instructingparty of dependencylink not matching with senderid",
"3997":"Transaction reference is not UNIQUE",
"3991":"BTBReference is invalid",
"3959":"settlementdate is not valid",
"3961":"DEPENDENCY LINK REFERNCE SHOULD BE SPECIFIED",
"3965":"BTBreference doesnot exist",
"4164":"ACCOUNT DETAILS NOT FOUND",
"4163":"SELLER_CLIENT_NOT_ASSOCIATED_WITH_THE_DEPOSITORY_PARTICIPANT",
"4033":"Trade Date should be current business Date OR PAST DATE",
"5001":"Invalid RECU value",
"5003":"Invalid SELL tagvalue",
"5004":"Invalid BUY tagvalue",
"5006":"Invalid DEAGvalue",
"5007":"Invalid Seller Acno",
"5008":"Invalid Buyer Acno",
"5010":"Invalid BUYER client Acno",
"5012":"incorrect tradequantity",
"5013":"incorrect settlementdate",
"5016":"Affirmation status mismatch",
"5017":"securitiesTransactionType mismatch",
"5019":"taxableInd mismatch",
"5020":"clientType mismatch",
"5022":"securityid mismatch",
"5014":"settlement type mismatch",
"4441":"Seller Trader/Broker does not exist",
"4442":"BuyerTrader/Broker does not exist",
"S627":"Invalid Trade Reference",
"M909":"CORPORATE EVENT IS NOT IN WAITING FOR CONFIRMATION STATUS",
"M165":"MISMATCH BETWEEN CORPORATE ACTION REFERENCE (CORP)",
"M911":"INVALID SETTLEMENT CURRENCY",
"M541":"Eligible Holdings Mismatch(Tag93A)",
"M913":"INVALID AGREEMENT NUMBER",
"K546":"INVALID ISIN",
"MP75":"PAYMENT AMOUNT CONFIRMATION IS EXPECTED ONLY FOR COUPON EVENTS",
"4042":" Buyer Account No. Not in Valid Status",
"4037":" Deadline does not exist for trade creation",
"4032":" Settlement Date not a valid business date",
"4030":" Calender Details Does not Exist",
"4026":" Security not eligible for trading",
"4021":" Account Type must be Settlement/Free A/c",
"4019":" Buyer Account No. Not Found",
"4017":" Account Type must be Settlement/Free A/c",
"4011":" Buyer BP not Active",
"4008":" Seller BP Does Not Have Broker Role",
"4006":" Seller BP Does not Exist",
"4003":" BP Does not have Exchange role",
"3967":"BTBReference is Already in DPL",
"3969":"Trades Attached to BTBReference is Already Settled",
"4445":"DECU not having CSDP Role",
"3970":"Instructing Party of DPL Reference is not the CSD Party of Trade",
"3982":"SOR Account is not matching with ExistingSOR Account of Dependencylink",
"3984":"SOR Account of All Trades are Not Same",
"7301":"MANDATORY FIELD NOT SPECIFIED IN THE TAG",
"7302":"LENGTH MISMATCH FOR FIELD",
"7308":"MANDATORY TAG NOT SPECIFIED",
"7311":"UNEXPECTED END OF REPETITIVE STRUCTURE",
"7314":"KEYWORD OCCURS MORE THAN ONCE",
"7315":"KEYWORD ERROR IN NARRATIVE FIELD",
"7475":"INVALID MESSAGE / SEQUENCE",
"7305":"END OF TEXT NOT PRESENT",
"7306":"DATA FOUND AFTER END OF TEXT",
"7206":"subscription doesnt exist",
"7399":"invalid message type",
"O502":"sender and instructing party not matching",
"4443":"Buyer Trader/Broker is not active",
"B059":"AFFI not allowed for Bulk Normal trades",
"DMA4":"INVALID ACCOUNT NUMBER",
"DM10":"INSTRUMENT_NOT_IN_ACTIVE_STATUS",
"D002":"Invalid Participant ref",
"S630":"Failed Trade Management Is In Progress for this Instrument",
"DMA2":"Investor BP NOT IN ACTIVE status",
"P005":"BanReference Not Found",
"DMA6":"ACCOUNT_DOES_NOT_EXISTS",
"DMA7":"INVALID ACCOUNT TYPE",
"DMA9":"SECURITY_DOES_NOT_EXIST",
"DM12":"The Account Owner Should Be An Investor",
"DM17":"Invalid value for Affirmation status",
"B510":"SOR should be the Issuer SOR for the ISIN",
"1115":"CSDP address NO of additional address-3 already exists",
"B605":"Invalid Market Segment-IO",
"SDUN":"Deadline Exceeds,Settlement Date Uncommit",
"1116":"CSDP address NO of additional address-4 already exists",
"1117":"Additional address can be created after Default address creation",
"P004":"Cash Advice maping does not exists",
"D040":"Guaranteed Indicator Mismatch",
"B100":"MATCHED-TRADE CANNOT BE CANCELED ON STLMT DATE -IO",
"1124":"CSDP No Already exists. MODF-Address5 creation Failed",
"S633":"Collateral Trades Notallowed to link in BTB",
"0287":"Long name length cannot exceed 120 characters",
"0995":"Price date Should be Business Date",
"0996":"Invalid Instrument status",
"0998":"Invalid Instrument",
"0913":"Nominal Value and Mininum tradable quantity validation failed TOPU or REDU",
"0912":"Minimum Tradable Denomination quantity is zero TOPU or REDU",
"0911":"Nominal Value and Mininum tradable quantity validation failed DISS",
"1954":"Issuer CSDP is not Active",
"0289":"Request is Already Pending With TSP Party",
"2183":"Programme ID is not active",
"2789":"Program ID does not Exist",
"3234":"Maturity date must be greater than issue date",
"332945":"Issue date can not be a holiday",
"D044":"Sender is not the Instructing Party of Trade",
"S636":"Instucting Party is not Issuer of BTB",
"B353":"DUPLICATE TRADE RECEIVED",
"BI04":"nextresetdate_NOT_EQUAL_TO_MFBDC_nextresetdate",
"O050":"Program is inactive",
"O053":"Seller Securities Sub Balance ID not found",
"O055":"Seller Securities Sub Balance ID invalid",
"O057":"Seller Securities Sub Balance ID inactive",
"O060":"Invalid Third Party Reference",
"O062":"Automated Transformation not supported after Record Date",
"O065":"Issuer Agent invalid",
"O067":"Instructing Party should be CSD",
"O068":"Invalid instrument type",
"O073":"Settlement Date mismatch",
"O075":"Settlement Bank Details not found",
"S420":"OptOut Indicator should be Yes for POA",
"S423":"Trade cannot be cancelled",
"S425":"Settlement Date Mismatch",
"S426":"Trade date Mismatch",
"S428":"Matching indicator mismatch",
"3972":"Instucting Party is not Issuer of DPL",
"7":"Commit deadline exceeded",
"1957":"Only one address line ADRC tag Can be given as 1",
"P009":"SettlementDate is InValid",
"P010":"SettlementAmount is InValid",
"D555":"SETTLEMENTDATEDELISTING DATE ARE NOT EQUAL",
"GRTS":"settlement date is greater than delisting date of ISIN",
"NORD":"NO RD AVAILABLE",
"0072":"Only owner of DP can Modify Address Details/Previous Coupon Date Cannot be a Holiday. OR Only owner of DP can Modify Address Details/Last Reset Date Cannot be a Holiday. OR Last Reset Date Cannot be a Holiday.",
"0078":"Only owner of DP can Modify Address Details/Lock-In End Date Cannot be a Holiday. OR Lock-In End Date Cannot be a Holiday.",
"0081":"Only owner of DP can Modify Address Details/Mandatory Field Issue Date Not Specified OR Mandatory Field Issue Date Not Specified",
"0083":"Only Owner of the Depository Participant can Freeze,Re-Activate,Close Account Details/Please Specify Locking Period For Subsidised Shares OR Please Specify Locking Period For Subsidised Shares",
"0087":"Account is not in open or active Status/Next Payment Date Specified Does Not Match With System Calculated Date OR Next Payment Date Specified Does Not Match With System Calculated Date",
"0091":"No Transactions are allowed when the account is in Deleted status OR ISSUER ROLE NOT IN ACTIVE STATUS",
"B030":"In one ITR, there should not be duplication of Account Numbers i.e. SOR should not be repeated for the same ITR.",
"2029":"Trade not in allowed status for cancellation"}

def get_error_reason_from_code(error_code):
    return error_code_mapping.get(error_code, "")
