"""-----------------------------------------------------------------------------
PURPOSE              :  Legal Agreement Service (LAS) integration
DEVELOPER            :  Libor Svoboda
REQUESTER            :  Victor Mofokeng (CRT desk)
--------------------------------------------------------------------------------

HISTORY
================================================================================
Date        Change no      Developer           Description
--------------------------------------------------------------------------------
2020-11-26  CHG0140652     Libor Svoboda       Initial implementation
2021-02-03  CHG0149970     Libor Svoboda       Add delayed queue
"""
from at_logging import getLogger
from las_util import is_amwi_cleared_trade


LOGGER = getLogger()
DEFAULTS = {
    'IndexLinkedBond': 'Bond - Index Linked',
    'Bond': 'Bond',
    'BuySellback': 'BuySell Back',
    'Cap': 'Cap',
    'Cash': 'Cash Payment',
    'CD': 'Term Funding',
    'Combination': 'Combination',
    'CFD': 'Contract for Difference - Equity',
    'Convertible': 'Convertible',
    'CreditDefaultSwap': 'Credit Default Swap',
    'CLN': 'Credit Linked Note',
    'CurrSwap': 'Currency Swap',
    'Deposit': 'Term Funding',
    'Stock': 'Equity',
    'EquityIndex': 'Equity Index',
    'ETF': 'Exchange Traded Funds',
    'FXOptionDatedFwd': 'FX Option Dated Forward',
    'FRN': 'Float Rate Note',
    'Floor': 'Floor',
    'FRA': 'Forward Rate Agreement',
    'Swap': 'Interest Rate Swap',
    'PromisLoan': 'Loan',
    'NDF': 'NDF',
    'Portfolio Swap': 'Portfolio Swap',
    'PriceSwap': 'Price Swap',
    'IndexLinkedSwap': 'Swap - Index Linked',
    'VarianceSwap': 'Swap - Variance Equity Index',
    'TotalReturnSwap': 'Total Return Swap',
    'Bill': 'Bill',
    'Warrant': 'Warrant',
    'Zero':  'Zero Coupon Bond',
}
MAPPING = {
    'IndexLinkedBond': {
        None: {
            (None, None, None, False): 'Bond - Index Linked',
            (None, None, None, True): 'Bond - Index Linked',
            (None, 'Combination - Rates Linked Note', None, False): 'Bond - Index Linked',
            (None, 'Combination - Rates Linked Note', None, True): 'Bond - Index Linked',
            (None, 'Fixed Rate Loan', None, False): 'Fixed Rate Loan',
            (None, 'Fixed Rate Loan', None, True): 'Fixed Rate Loan',
            (None, 'Term Loan', None, False): 'Term Loan',
            (None, 'Term Loan', None, True): 'Term Loan',
            ('FRN', None, None, False): 'Bond - Index Linked',
            ('FRN', None, None, True): 'Bond - Index Linked',
        },
    },
    'Bond': {
        None: {
            (None, None, None, False): 'Bond',
            (None, None, None, True): 'Bond',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Fixed Rate Loan', None, False): 'Fixed Rate Loan',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
            (None, 'Preference Shares', None, True): 'Preference Shares',
            (None, 'Repurchase Agreement - Bond', None, False): 'Repurchase Agreement - Bond',
            (None, 'Repurchase Agreement - Bond', None, True): 'Repurchase Agreement - Bond',
            (None, 'Selective Receivables Finance', None, False): 'Selective Receivables Finance',
            (None, 'Selective Receivables Finance', None, True): 'Selective Receivables Finance',
            (None, 'Supplier Finance', None, False): 'Supplier Finance',
            (None, 'Supplier Finance', None, True): 'Supplier Finance',
            (None, 'Vanilla Trade Loans', None, False): 'Vanilla Trade Loans',
            (None, 'Vanilla Trade Loans', None, True): 'Vanilla Trade Loans',
            ('CLN', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('FRN', None, None, False): 'Bond',
            ('FRN', None, None, True): 'Bond',
        },
    },
    'BuySellback': {
        'Bill': {
            (None, None, None, False): 'BuySell Back - Bill',
            (None, None, None, True): 'BuySell Back - Bill',
        },
        'Bond': {
            (None, None, None, False): 'BuySell Back - Bond',
            (None, None, None, True): 'BuySell Back - Bond',
        },
        'CD': {
            (None, None, None, False): 'BuySell Back - Certificate of Deposit',
            (None, None, None, True): 'BuySell Back - Certificate of Deposit',
        },
        'Deposit': {
            (None, None, None, False): 'BuySell Back - Deposit',
            (None, None, None, True): 'BuySell Back - Deposit',
        },
        'FRN': {
            (None, None, None, False): 'BuySell Back - Forward Rate Note',
            (None, None, None, True): 'BuySell Back - Forward Rate Note',
        },
        'IndexLinkedBond': {
            (None, None, None, False): 'BuySell Back - Index Linked Bond',
            (None, None, None, True): 'BuySell Back - Index Linked Bond',
        },
        'Stock': {
            (None, None, None, False): 'BuySell Back - Convertible Bond',
            (None, None, None, True): 'BuySell Back - Convertible Bond',
        },
    },
    'Cap': {
        None: {
            (None, None, None, False): 'Cap',
            (None, None, None, True): 'Cap',
            (None, 'Combination - Credit Linked Note', None, False): 'Cap',
            (None, 'Combination - Credit Linked Note', None, True): 'Cap',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, True): 'Combination - Rates Linked Note',
        },
    },
    'Cash': {
        None: {
            (None, None, None, False): 'Cash Payment',
            (None, None, None, True): 'Cash Payment',
            (None, 'Combination - Credit Linked Note', None, False): 'Cash Payment',
            (None, 'Combination - Credit Linked Note', None, True): 'Cash Payment',
            (None, 'Commitment Fee', None, False): 'Commitment Fees',
            (None, 'Commitment Fee', None, True): 'Commitment Fees',
            (None, 'Commodity Currency Swap', None, False): 'Cash Payment',
            (None, 'Commodity Currency Swap', None, True): 'Cash Payment',
            (None, 'Execution Fee', None, False): 'Execution Fee',
            (None, 'Execution Fee', None, True): 'Execution Fee',
            (None, 'Financing Fee', None, False): 'Financing Fee',
            (None, 'Financing Fee', None, True): 'Financing Fee',
            (None, 'Interest Claims', None, False): 'Interest Claims',
            (None, 'Interest Claims', None, True): 'Interest Claims',
            (None, 'Research Income', None, False): 'Research Income',
            (None, 'Research Income', None, True): 'Research Income',
            (None, 'Utilisation Fee', None, False): 'Utilisation Fee',
            (None, 'Utilisation Fee', None, True): 'Utilisation Fee',
        },
    },
    'CD': {
        None: {
            (None, None, 'CD', False): 'Term Funding',
            (None, None, 'CD', True): 'Term Funding',
            (None, None, 'CD Pre Payable', False): 'Term Funding',
            (None, None, 'CD Pre Payable', True): 'Term Funding',
            (None, None, 'CD Roll-up', False): 'Term Funding',
            (None, None, 'CD Roll-up', True): 'Term Funding',
            (None, None, 'CD SNR', False): 'Term Funding',
            (None, None, 'CD SNR', True): 'Term Funding',
            (None, None, 'CL', False): 'Term Funding',
            (None, None, 'CL', True): 'Term Funding',
            (None, None, 'CL Pre Payable', False): 'Term Funding',
            (None, None, 'CL Pre Payable', True): 'Term Funding',
            (None, None, 'CL Roll-up', False): 'Term Funding',
            (None, None, 'CL Roll-up', True): 'Term Funding',
            (None, None, 'CL SNR', False): 'Term Funding',
            (None, None, 'CL SNR', True): 'Term Funding',
            (None, None, 'Commercial Paper', False): 'Commercial Paper',
            (None, None, 'Commercial Paper', True): 'Commercial Paper',
            (None, None, 'Debentures', False): 'Bill',
            (None, None, 'Debentures', True): 'Bill',
            (None, None, 'FDC', False): 'Term Fixed Rate Deposit',
            (None, None, 'FDC', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDE', False): 'Term Fixed Rate Deposit',
            (None, None, 'FDE', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDI', False): 'Term Fixed Rate Deposit',
            (None, None, 'FDI', True): 'Term Fixed Rate Deposit',
            (None, None, 'FRN', False): 'Float Rate Note',
            (None, None, 'FRN', True): 'Float Rate Note',
            (None, None, 'NCC', False): 'Negotiable Certificate of Deposit',
            (None, None, 'NCC', True): 'Negotiable Certificate of Deposit',
            (None, None, 'NCD', False): 'Negotiable Certificate of Deposit',
            (None, None, 'NCD', True): 'Negotiable Certificate of Deposit',
            (None, None, 'NCF', False): 'Negotiable Certificate of Deposit',
            (None, None, 'NCF', True): 'Negotiable Certificate of Deposit',
            (None, None, 'PN', False): 'Promissory Note',
            (None, None, 'PN', True): 'Promissory Note',
            (None, None, 'PRN', False): 'Promissory Note',
            (None, None, 'PRN', True): 'Promissory Note',
            (None, 'Fixed Rate Loan', 'PM TLF', True): 'Promissory Note',
            (None, 'Interest on Bank Acc', None, False): 'Interest Make-up Accrual',
            (None, 'Interest on Bank Acc', None, True): 'Interest Make-up Accrual',
            ('CD', None, 'CD', True): 'Term Funding',
            ('PN', None, 'PRN', False): 'Promissory Note',
            ('PN', None, 'PRN', True): 'Promissory Note',
            ('PN', 'Fixed Rate Loan', 'PRN', False): 'Promissory Note',
            ('PRN', None, 'PRN', True): 'Promissory Note',
        },
    },
    'Combination': {
        None: {
            (None, None, None, False): 'Combination - Listed',
            (None, None, None, True): 'Combination',
            (None, None, 'CLN', False): 'Credit Link Note',
            (None, None, 'CLN', True): 'Credit Link Note',
            (None, 'Combination - CDS', None, False): 'Combination - CDS',
            (None, 'Combination - CDS', None, True): 'Combination - CDS',
            (None, 'Combination - Commodity Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Commodity Linked Note', None, True): 'Combination - Commodity Linked Note',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Equity Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Combination - FX Linked Note', None, False): 'Combination - FX Linked Note',
            (None, 'Combination - FX Linked Note', None, True): 'Combination - FX Linked Note',
            (None, 'Combination - FX Option', None, False): 'Combination - FX Option',
            (None, 'Combination - FX Option', None, True): 'Combination - FX Option',
            (None, 'Combination - FX option', None, False): 'Combination - FX Option',
            (None, 'Combination - FX option', None, True): 'Combination - FX Option',
            (None, 'Combination - Index Linked Note', None, False): 'Combination - Index Linked Note',
            (None, 'Combination - Index Linked Note', None, True): 'Combination - Index Linked Note',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Listed',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, False): 'Combination - Listed',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Repurchase Agreement - Bond', None, False): 'Repurchase agreement-Bond',
            (None, 'Repurchase Agreement - Bond', None, True): 'Repurchase agreement-Bond',
            (None, 'Repurchase Agreement - Index Linked Bond', None, False): 'Repurchase Agreement - Index Linked Bond',
            (None, 'Repurchase Agreement - Index Linked Bond', None, True): 'Repurchase Agreement - Index Linked Bond',
            (None, 'Structured Rates Deposit/Swap', None, False): 'Combination - Listed',
            (None, 'Structured Rates Deposit/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, True): 'Combination - Rates Linked Note',
        },
    },
    'CFD': {
        None: {
            (None, None, None, False): 'Contract for Difference - Equity',
            (None, None, None, True): 'Contract for Difference - Equity',
            (None, 'Synthetic Structured Deal', None, False): 'Contract for Difference - Equity',
            (None, 'Synthetic Structured Deal', None, True): 'Contract for Difference - Equity',
        },
    },
    'CreditDefaultSwap': {
        'Bond': {
            (None, None, None, False): 'Credit Default Swap',
            (None, None, None, True): 'Credit Default Swap',
            (None, 'Combination - Credit Link Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Link Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Non Payment Insurance', None, True): 'Credit Default Swap',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
            ('CD', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('CD', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('FDI', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('FDI', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('FRN', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('FRN', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
        },
        'CreditIndex': {
            (None, None, None, False): 'Credit Default Swap',
            (None, None, None, True): 'Credit Default Swap',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
        },
        None: {
            (None, None, None, False): 'Credit Default Swap',
            (None, None, None, True): 'Credit Default Swap',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Insurance', None, False): 'Insurance',
            (None, 'Insurance', None, True): 'Insurance',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
        },
    },
    'CurrSwap': {
        None: {
            (None, None, None, False): 'Currency Swap',
            (None, None, None, True): 'Currency Swap',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Cross Currency Swap', None, True): 'Currency Swap',
            (None, 'Combination - FX Linked Note', None, False): 'Currency Swap',
            (None, 'Combination - FX Linked Note', None, True): 'Currency Swap',
            (None, 'Combination - FX option', None, False): 'Currency Swap',
            (None, 'Combination - FX option', None, True): 'Currency Swap',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Interest Rate Future', None, False): 'Interest Rate Future',
            (None, 'Interest Rate Future', None, True): 'Interest Rate Future',
        },
    },
    'Deposit': {
        None: {
            (None, None, 'Access Deposit Note 370d', True): '370 Day Access Account',
            (None, None, 'Access Deposit Note 95d', True): '95 Day Access Account',
            (None, None, 'Access Deposit Note 95d Note 2', True): 'Access Note Deposit 95d Note 2',
            (None, None, 'Africa', False): 'Foreign Currency Term Deposit',
            (None, None, 'Africa', True): 'Foreign Currency Term Deposit',
            (None, None, 'CALL_EQ_Funding', False): 'Sec Lending Collateral - Cash',
            (None, None, 'CALL_EQ_Funding', True): 'Sec Lending Collateral - Cash',
            (None, None, 'CD', False): 'Term Funding',
            (None, None, 'CD', True): 'Term Funding',
            (None, None, 'CD Non Zar', False): 'Foreign Currency Term Deposit',
            (None, None, 'CD Non Zar', True): 'Foreign Currency Term Deposit',
            (None, None, 'CD Pre Payable', False): 'Term Funding',
            (None, None, 'CD Pre Payable', True): 'Term Funding',
            (None, None, 'CD Roll-up', False): 'Term Funding',
            (None, None, 'CD Roll-up', True): 'Term Funding',
            (None, None, 'CD SNR', False): 'Term Funding',
            (None, None, 'CD SNR', True): 'Term Funding',
            (None, None, 'CL', False): 'Term Funding',
            (None, None, 'CL', True): 'Term Funding',
            (None, None, 'CL Non Zar', False): 'Foreign Currency Term Deposit',
            (None, None, 'CL Non Zar', True): 'Foreign Currency Term Deposit',
            (None, None, 'CL Pre Payable', False): 'Term Funding',
            (None, None, 'CL Pre Payable', True): 'Term Funding',
            (None, None, 'CL Roll-up', False): 'Term Funding',
            (None, None, 'CL Roll-up', True): 'Term Funding',
            (None, None, 'CL SNR', False): 'Term Funding',
            (None, None, 'CL SNR', True): 'Term Funding',
            (None, None, 'CLN', False): 'Credit Link Note',
            (None, None, 'CLN', True): 'Credit Link Note',
            (None, None, 'Call 32 Day notice', False): 'Call Notice Deposit',
            (None, None, 'Call 32 Day notice', True): 'Call Notice Deposit',
            (None, None, 'Call 48 Hour Notice', True): 'Call Notice Deposit',
            (None, None, 'Call 7 Day notice', False): 'Call Notice Deposit',
            (None, None, 'Call 7 Day notice', True): 'Call Notice Deposit',
            (None, None, 'Call Deposit Coll DTI', False): 'Cash Collateral',
            (None, None, 'Call Deposit Coll DTI', True): 'Cash Collateral',
            (None, None, 'Call Deposit Coll NonDTI', False): 'Cash Collateral',
            (None, None, 'Call Deposit Coll NonDTI', True): 'Cash Collateral',
            (None, None, 'Call Deposit DTI', False): 'Call Deposit',
            (None, None, 'Call Deposit DTI', True): 'Call Deposit',
            (None, None, 'Call Deposit NonDTI', False): 'Call Deposit',
            (None, None, 'Call Deposit NonDTI', True): 'Call Deposit',
            (None, None, 'Call I/Div', False): 'Call Funding',
            (None, None, 'Call I/Div', True): 'Call Funding',
            (None, None, 'Call I/Div DTI', False): 'Call Funding',
            (None, None, 'Call I/Div DTI', True): 'Call Funding',
            (None, None, 'Call I/Div SARB', False): 'Call Funding',
            (None, None, 'Call I/Div SARB', True): 'Call Funding',
            (None, None, 'Call I/div 32 day', False): 'Call Funding',
            (None, None, 'Call I/div 32 day', True): 'Call Funding',
            (None, None, 'Call Interdesk', False): 'Call Funding',
            (None, None, 'Call Interdesk', True): 'Call Funding',
            (None, None, 'Call Loan Coll DTI', False): 'Cash Collateral',
            (None, None, 'Call Loan Coll DTI', True): 'Cash Collateral',
            (None, None, 'Call Loan Coll NonDTI', False): 'Cash Collateral',
            (None, None, 'Call Loan Coll NonDTI', True): 'Cash Collateral',
            (None, None, 'Call Loan DTI', False): 'Call Loan',
            (None, None, 'Call Loan DTI', True): 'Call Loan',
            (None, None, 'Call Loan NonDTI', False): 'Call Loan',
            (None, None, 'Call Loan NonDTI', True): 'Call Loan',
            (None, None, 'Call Prime Brokerage Funding', False): 'Client Cash Collateral',
            (None, None, 'Call Prime Brokerage Funding', True): 'Client Cash Collateral',
            (None, None, 'Eq', False): 'Term Funding',
            (None, None, 'Eq', True): 'Term Funding',
            (None, None, 'FDC', False): 'Term Fixed Rate Deposit',
            (None, None, 'FDC', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDC 48 Hour Notice', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDC 7 Day Notice', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDE', False): 'Term Fixed Rate Deposit',
            (None, None, 'FDE', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDE 32 Day notice', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDE Access Deposit Note 370d', True): '370 Day Fixed Notice Deposit',
            (None, None, 'FDI', False): 'Term Fixed Rate Deposit',
            (None, None, 'FDI', True): 'Term Fixed Rate Deposit',
            (None, None, 'FDI Access Deposit Note 370d', True): 'Deposit',
            (None, None, 'FDI Access Deposit Note 95d', True): '95 Day Fixed Notice Deposit',
            (None, None, 'FLI', False): 'Term Fixed Rate Loan',
            (None, None, 'FLI', True): 'Term Fixed Rate Loan',
            (None, None, 'FRD', False): 'Term Deposit',
            (None, None, 'FRD', True): 'Term Deposit',
            (None, None, 'FRD Pre Payable', False): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable', True): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 13M', False): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 13M', True): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 1M', False): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 1M', True): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 1Y', True): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 3M', False): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 3M', True): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 6M', False): 'Term Floating Rate Deposit',
            (None, None, 'FRD Pre Payable 6M', True): 'Term Floating Rate Deposit',
            (None, None, 'FRN', False): 'Float Rate Note',
            (None, None, 'FRN', True): 'Float Rate Note',
            (None, None, 'FTL', False): 'Term Fixed Rate Loan',
            (None, None, 'FTL', True): 'Term Fixed Rate Loan',
            (None, None, 'IRD Funding', False): 'Internal Fee Deposit',
            (None, None, 'IRD Funding', True): 'Internal Fee Deposit',
            (None, None, 'LEV CLN', False): 'Credit Link Note',
            (None, None, 'LEV CLN', True): 'Credit Link Note',
            (None, None, 'NCC', False): 'Negotiable Certificate of Deposit',
            (None, None, 'NCC', True): 'Negotiable Certificate of Deposit',
            (None, None, 'NCD', False): 'Negotiable Certificate of Deposit',
            (None, None, 'NCD', True): 'Negotiable Certificate of Deposit',
            (None, None, 'NCF', False): 'Negotiable Certificate of Deposit',
            (None, None, 'NCF', True): 'Negotiable Certificate of Deposit',
            (None, None, 'Non Zar CFC', False): 'Customer Foreign Currency Account',
            (None, None, 'Non Zar CFC', True): 'Customer Foreign Currency Account',
            (None, None, 'Non Zar Deposit', False): 'Term Fixed Rate Deposit',
            (None, None, 'Non Zar Deposit', True): 'Term Fixed Rate Deposit',
            (None, None, 'Non Zar Loan', False): 'Foreign Currency Term Loan',
            (None, None, 'Non Zar Loan', True): 'Foreign Currency Term Loan',
            (None, None, 'PM TLF', False): 'Term Loan',
            (None, None, 'PM TLF', True): 'Term Loan',
            (None, None, 'PM TLV', False): 'Term Loan',
            (None, None, 'PM TLV', True): 'Term Loan',
            (None, None, 'PRN', False): 'Promissory Note',
            (None, None, 'PRN', True): 'Promissory Note',
            (None, None, 'RDL', False): 'Commodity Deposit',
            (None, None, 'RDL', True): 'Commodity Deposit',
            (None, None, 'Repo', False): 'Repurchase Agreement - Deposit',
            (None, None, 'Repo', True): 'Repurchase Agreement - Deposit',
            (None, None, 'SL', False): 'Fixed Deposit',
            (None, None, 'SL', True): 'Fixed Deposit',
            (None, None, 'SNR', False): 'Term Funding',
            (None, None, 'SNR', True): 'Term Funding',
            (None, None, 'SRP', False): 'South African Reserve Bank Repo',
            (None, None, 'SRP', True): 'South African Reserve Bank Repo',
            (None, None, 'SS', True): 'Combination',
            (None, 'Call 48 Hour Notice', 'Call 48 Hour Notice', False): 'Call Deposit',
            (None, 'Call 48 Hour Notice', 'Call 48 Hour Notice', True): 'Call Deposit',
            (None, 'Combination - CDS', 'CD', True): 'Term Funding',
            (None, 'Combination - CDS', 'CL', True): 'Term Funding',
            (None, 'Combination - CDS', 'FTL', True): 'Term Fixed Rate Loan',
            (None, 'Combination - Commodity Linked Note', None, False): 'Combination - Commodity Linked Note',
            (None, 'Combination - Commodity Linked Note', None, True): 'Combination - Commodity Linked Note',
            (None, 'Combination - Commodity Linked Note', 'FDE', False): 'Combination - Listed',
            (None, 'Combination - Commodity Linked Note', 'FDE', True): 'Combination - Commodity Linked Note',
            (None, 'Combination - Commodity Linked Note', 'FDI', False): 'Combination - Listed',
            (None, 'Combination - Commodity Linked Note', 'FDI', True): 'Combination - Commodity Linked Note',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', 'SS', False): 'Credit Link Note',
            (None, 'Combination - Credit Linked Depo', 'SS', True): 'Credit Link Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', 'CLN', False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', 'CLN', True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', 'FDE', False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', 'FDE', True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', 'FDI', False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', 'FDI', True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', 'SS', False): 'Credit Link Note',
            (None, 'Combination - Credit Linked Note', 'SS', True): 'Credit Link Note',
            (None, 'Combination - Equity Linked Note', None, False): 'Combination - Equity Linked Note',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Combination - Equity Linked Note', 'CD', True): 'Combination - Equity Linked Note',
            (None, 'Combination - Equity Linked Note', 'CD Roll-up', True): 'Combination - Equity Linked Note',
            (None, 'Combination - Equity Linked Note', 'FDE', False): 'Combination - Listed',
            (None, 'Combination - Equity Linked Note', 'FDE', True): 'Combination - Equity Linked Note',
            (None, 'Combination - Equity Linked Note', 'FDI', False): 'Combination - Listed',
            (None, 'Combination - Equity Linked Note', 'FDI', True): 'Combination - Equity Linked Note',
            (None, 'Combination - Index Linked Note', None, False): 'Combination - Index Linked Note',
            (None, 'Combination - Index Linked Note', None, True): 'Combination - Index Linked Note',
            (None, 'Combination - Index Linked Note', 'FDI', False): 'Combination - Listed',
            (None, 'Combination - Index Linked Note', 'FDI', True): 'Combination - Index Linked Note',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', 'CD', False): 'Combination - Listed',
            (None, 'Combination - Rates Linked Note', 'CD', True): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', 'CL', False): 'Combination - Listed',
            (None, 'Combination - Rates Linked Note', 'CL', True): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', 'FDE', False): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', 'FDE', True): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', 'FDI', False): 'Combination - Listed',
            (None, 'Combination - Rates Linked Note', 'FDI', True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Listed',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', 'FDE', False): 'Combination - Listed',
            (None, 'Combination - Struct Rate Note', 'FDE', True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', 'FDI', False): 'Combination - Listed',
            (None, 'Combination - Struct Rate Note', 'FDI', True): 'Combination - Rates Linked Note',
            (None, 'Exchange Initial Margin', 'Call Deposit Coll NonDTI', True): 'Initial Margin',
            (None, 'Fixed Rate Loan', None, False): 'Fixed Rate Loan',
            (None, 'Fixed Rate Loan', None, True): 'Fixed Rate Loan',
            (None, 'Fixed Rate Loan', 'CD', False): 'Fixed Rate Loan',
            (None, 'Fixed Rate Loan', 'CD', True): 'Fixed Rate Loan',
            (None, 'Fixed Rate Loan', 'PM TLF', False): 'Fixed Rate Loan',
            (None, 'Fixed Rate Loan', 'PM TLF', True): 'Fixed Rate Loan',
            (None, 'Future/Forward - Bond Index', 'Call Deposit Coll NonDTI', True): 'Variation Margin Futures',
            (None, 'IRS - CFC Interest Charge', 'CD', False): 'CFC Interest Charge',
            (None, 'IRS - CFC Interest Charge', 'CD', True): 'CFC Interest Charge',
            (None, 'Interest Make-up Accrual', None, False): 'Interest Make-up Accrual',
            (None, 'Interest Make-up Accrual', None, True): 'Interest Make-up Accrual',
            (None, 'Interest Make-up Accrual', 'FTL', False): 'Interest Make-up Accrual',
            (None, 'Interest Make-up Accrual', 'FTL', True): 'Interest Make-up Accrual',
            (None, 'Interest Rate Future', 'Call Deposit Coll NonDTI', True): 'Variation Margin IRS',
            (None, 'Interest Suspension', None, False): 'Interest Suspension',
            (None, 'Interest Suspension', None, True): 'Interest Suspension',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
            (None, 'Passthrough', 'Africa', False): 'Passthrough',
            (None, 'Passthrough', 'Africa', True): 'Passthrough',
            (None, 'Passthrough', 'CD', False): 'Passthrough',
            (None, 'Passthrough', 'CD', True): 'Passthrough',
            (None, 'Passthrough', 'CD Non Zar', False): 'Passthrough',
            (None, 'Passthrough', 'CD Non Zar', True): 'Passthrough',
            (None, 'Passthrough', 'CL', False): 'Passthrough',
            (None, 'Passthrough', 'CL', True): 'Passthrough',
            (None, 'Passthrough', 'CLN', False): 'Passthrough',
            (None, 'Passthrough', 'CLN', True): 'Passthrough',
            (None, 'Passthrough', 'FDI', False): 'Passthrough',
            (None, 'Passthrough', 'FDI', True): 'Passthrough',
            (None, 'Passthrough', 'SS', False): 'Passthrough',
            (None, 'Passthrough', 'SS', True): 'Passthrough',
            (None, 'Preference Shares', None, False): 'Preference Shares',
            (None, 'Preference Shares', None, True): 'Preference Shares',
            (None, 'Preference Shares', 'PM TLF', True): 'Preference Shares',
            (None, 'Preference Shares', 'PM TLV', False): 'Preference Shares',
            (None, 'Preference Shares', 'PM TLV', True): 'Preference Shares',
            (None, 'Preference Shares - Hedged', 'PM TLV', False): 'Preference Shares - Hedged',
            (None, 'Preference Shares - Hedged', 'PM TLV', True): 'Preference Shares - Hedged',
            (None, 'Preference share-Hedge issued', None, False): 'Preference share-Hedge issued',
            (None, 'Preference share-Hedge issued', None, True): 'Preference share-Hedge issued',
            (None, 'Repurchase Agreement - Bond', None, False): 'Repurchase agreement-Bond',
            (None, 'Repurchase Agreement - Bond', None, True): 'Repurchase agreement-Bond',
            (None, 'Revolving Credit Loan', None, False): 'Revolving Credit Loan',
            (None, 'Revolving Credit Loan', None, True): 'Revolving Credit Loan',
            (None, 'Selective Receivables Finance', 'FTL', False): 'Selective Receivables Finance',
            (None, 'Selective Receivables Finance', 'FTL', True): 'Selective Receivables Finance',
            (None, 'Structured Rates Deposit/Swap', None, False): 'Combination - Listed',
            (None, 'Structured Rates Deposit/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Supplier Finance', 'CD', True): 'Term Funding',
            (None, 'Supplier Finance', 'CL', True): 'Term Funding',
            (None, 'Supplier Finance', 'FTL', False): 'Supplier Finance',
            (None, 'Supplier Finance', 'FTL', True): 'Supplier Finance',
            (None, 'Term Loan - Hedged', None, False): 'Term Loan - Hedged',
            (None, 'Term Loan - Hedged', None, True): 'Term Loan - Hedged',
            (None, 'Total Return Swap - Bond', 'CD', True): 'Term Funding',
            (None, 'Total Return Swap - Bond', 'CL', True): 'Term Funding',
            (None, 'Vanilla Trade Loans', 'FTL', False): 'Vanilla Trade Loans',
            (None, 'Vanilla Trade Loans', 'FTL', True): 'Vanilla Trade Loans',
            ('CLN', 'Combination - Credit Linked Note', 'CLN', False): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', 'CLN', True): 'Combination - Credit Linked Note',
            ('CLN', 'Passthrough', 'CLN', False): 'Passthrough',
            ('CLN', 'Passthrough', 'CLN', True): 'Passthrough',
            ('FRN', None, 'CD', False): 'Term Funding',
            ('FRN', None, 'CD', True): 'Term Funding',
            ('FRN', None, 'CD Roll-up', False): 'Term Funding',
            ('FRN', None, 'CD Roll-up', True): 'Term Funding',
            ('FRN', None, 'CL', False): 'Term Funding',
            ('FRN', None, 'CL', True): 'Term Funding',
            ('FRN', None, 'CL Roll-up', False): 'Term Funding',
            ('FRN', None, 'CL Roll-up', True): 'Term Funding',
            ('FRN', None, 'FDE', False): 'Term Fixed Rate Deposit',
            ('FRN', None, 'FDE', True): 'Term Fixed Rate Deposit',
            ('FRN', 'Combination - Commodity Linked Note', 'FDE', False): 'Combination - Listed',
            ('FRN', 'Combination - Commodity Linked Note', 'FDE', True): 'Combination - Commodity Linked Note',
            ('FRN', 'Combination - Credit Linked Note', 'FDE', False): 'Combination - Credit Linked Note',
            ('FRN', 'Combination - Credit Linked Note', 'FDE', True): 'Combination - Credit Linked Note',
            ('FRN', 'Combination - Equity Linked Note', 'FDE', False): 'Combination - Listed',
            ('FRN', 'Combination - Equity Linked Note', 'FDE', True): 'Combination - Equity Linked Note',
            ('FRN', 'Combination - FX Linked Note', 'FDE', True): 'Term Fixed Rate Deposit',
            ('FRN', 'Combination - Rates Linked Note', 'FDE', False): 'Combination - Listed',
            ('FRN', 'Combination - Rates Linked Note', 'FDE', True): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Struct Rate Note', 'FDE', False): 'Combination - Listed',
            ('FRN', 'Combination - Struct Rate Note', 'FDE', True): 'Combination - Rates Linked Note',
        },
    },
    'Stock': {
        None: {
            (None, None, None, False): 'Equity',
            (None, None, None, True): 'Equity',
            (None, 'Combination - Equity Linked Note', None, False): 'Combination - Equity Linked Note',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Equity OTC', None, True): 'Equity OTC',
            (None, 'Stock - Exchange Fees', None, False): 'Exchange Fees',
            (None, 'Stock - Exchange Fees', None, True): 'Exchange Fees',
        },
    },
    'EquityIndex': {
        None: {
            (None, None, None, False): 'Equity Index',
            (None, None, None, True): 'Equity Index',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
        },
    },
    'ETF': {
        None: {
            (None, 'ETN', None, False): 'ExchangeTradedNote',
            (None, 'ETN', None, True): 'ExchangeTradedNote',
        },
    },
    'FX Forward': {
        None: {
            (None, None, None, False): 'Commodity Currency Forward',
            (None, None, None, True): 'Commodity Currency Forward',
            (None, 'Combination - Credit Linked Note', None, False): 'FX Currency Forward',
            (None, 'Combination - Credit Linked Note', None, True): 'FX Currency Forward',
            (None, 'Combination - Equity Linked Note', None, False): 'FX Currency Forward',
            (None, 'Combination - Equity Linked Note', None, True): 'FX Currency Forward',
            (None, 'Commodity Currency Swap', None, False): 'Commodity Currency Forward',
            (None, 'Commodity Currency Swap', None, True): 'Commodity Currency Forward',
        },
    },
    'FX Spot': {
        None: {
            (None, None, None, False): 'Commodity Currency Spot',
            (None, None, None, True): 'Commodity Currency Spot',
            (None, 'Combination - Credit Linked Note', None, False): 'FX Currency Spot',
            (None, 'Combination - Credit Linked Note', None, True): 'FX Currency Spot',
            (None, 'Combination - FX Linked Note', None, False): 'FX Currency Spot',
            (None, 'Combination - FX Linked Note', None, True): 'FX Currency Spot',
            (None, 'Commodity Currency Swap', None, False): 'Commodity Currency Spot',
            (None, 'Commodity Currency Swap', None, True): 'Commodity Currency Spot',
            ('CLN', 'Combination - Credit Linked Note', 'CLN', False): 'FX Currency Spot',
            ('CLN', 'Combination - Credit Linked Note', 'CLN', True): 'FX Currency Spot',
        },
    },
    'FX Swap': {
        None: {
          (None, None, None, False): 'FX Currency Swap',
          (None, None, None, True): 'FX Currency Swap',
          (None, 'Commodity Currency Swap', None, False): 'Commodity Currency Swap',
          (None, 'Commodity Currency Swap', None, True): 'Commodity Currency Swap',
        },
    },
    'FRN': {
        None: {
            (None, 'Combination - Commodity Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Commodity Linked Note', None, True): 'Combination - Commodity Linked Note',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Equity Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Combination - Index Linked Note', None, False): 'Combination - Index Linked Note',
            (None, 'Combination - Index Linked Note', None, True): 'Combination - Index Linked Note',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, False): 'Combination - Listed',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
            (None, 'Structured Rates Deposit/Swap', None, False): 'Combination - Listed',
            (None, 'Structured Rates Deposit/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Term Loan', None, False): 'Term Loan',
            (None, 'Term Loan', None, True): 'Term Loan',
            ('Africa', None, None, False): 'Foreign Currency Term Deposit',
            ('Africa', None, None, True): 'Foreign Currency Term Deposit',
            ('CD', None, None, False): 'Term Funding',
            ('CD', None, None, True): 'Term Funding',
            ('CD Non Zar', None, None, False): 'Foreign Currency Term Deposit',
            ('CD Non Zar', None, None, True): 'Foreign Currency Term Deposit',
            ('CD Non Zar', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('CD Non Zar', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('CD Pre Payable', None, None, False): 'Term Funding',
            ('CD Pre Payable', None, None, True): 'Term Funding',
            ('CD Roll-Up', None, None, False): 'Term Funding',
            ('CD Roll-Up', None, None, True): 'Term Funding',
            ('CL', None, None, False): 'Term Funding',
            ('CL', None, None, True): 'Term Funding',
            ('CL Non Zar', None, None, False): 'Foreign Currency Term Deposit',
            ('CL Non Zar', None, None, True): 'Foreign Currency Term Deposit',
            ('CL Non Zar', None, 'FDE', False): 'Foreign Currency Term Deposit',
            ('CL Non Zar', None, 'FDE', True): 'Foreign Currency Term Deposit',
            ('CL Pre Payable', None, None, False): 'Term Funding',
            ('CL Pre Payable', None, None, True): 'Term Funding',
            ('CL Roll-Up', None, None, False): 'Term Loan',
            ('CL Roll-Up', None, None, True): 'Term Loan',
            ('CLN', None, None, False): 'Credit Link Note',
            ('CLN', None, None, True): 'Credit Link Note',
            ('CLN', None, 'CLN', False): 'Credit Link Note',
            ('CLN', None, 'CLN', True): 'Credit Link Note',
            ('CLN', 'Combination - Credit Link Depo', None, True): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', 'CLN', False): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - Credit Linked Note', 'CLN', True): 'Combination - Credit Linked Note',
            ('CLN', 'Combination - FX Linked Note', None, True): 'Credit Link Note',
            ('CLN', 'Passthrough', None, False): 'Passthrough',
            ('CLN', 'Passthrough', None, True): 'Passthrough',
            ('CLN', 'Passthrough', 'CLN', False): 'Passthrough',
            ('CLN', 'Passthrough', 'CLN', True): 'Passthrough',
            ('Comm Paper', None, None, False): 'Float Rate Note',
            ('Comm Paper', None, None, True): 'Float Rate Note',
            ('Corp Bonds Floating', None, None, False): 'Floating Corporate Bond',
            ('Corp Bonds Floating', None, None, True): 'Floating Corporate Bond',
            ('Corp Bonds Floating', None, 'Corp Bonds Floating', False): 'Float Rate Note',
            ('Corp Bonds Floating', None, 'Corp Bonds Floating', True): 'Float Rate Note',
            ('Corp Bonds Floating', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('Corp Bonds Floating', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('Corp Bonds Floating', 'Passthrough', None, False): 'Passthrough',
            ('Corp Bonds Floating', 'Passthrough', None, True): 'Passthrough',
            ('Ext Note Listed', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('Ext Note Listed', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('FDI', None, None, False): 'Fixed Deposit',
            ('FDI', None, None, True): 'Fixed Deposit',
            ('FDI', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('FDI', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('FDI', 'Combination - Rates Linked Note', None, False): 'Combination - Listed',
            ('FDI', 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            ('FDI', 'Combination - Rates Linked Note', 'FDE', False): 'Combination - Listed',
            ('FDI', 'Combination - Rates Linked Note', 'FDE', True): 'Combination - Rates Linked Note',
            ('FLI', None, None, False): 'Fixed Loan',
            ('FLI', None, None, True): 'Fixed Loan',
            ('FRD Pre Payable', None, None, False): 'Term Floating Rate Deposit',
            ('FRD Pre Payable', None, None, True): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 13M', None, None, False): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 13M', None, None, True): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 1M', None, None, False): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 1M', None, None, True): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 3M', None, None, False): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 3M', None, None, True): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 6M', None, None, False): 'Term Floating Rate Deposit',
            ('FRD Pre Payable 6M', None, None, True): 'Term Floating Rate Deposit',
            ('FRN', None, None, False): 'Float Rate Note',
            ('FRN', None, None, True): 'Float Rate Note',
            ('FRN', None, 'CD', False): 'Float Rate Note',
            ('FRN', None, 'CD', True): 'Float Rate Note',
            ('FRN', None, 'FRN', False): 'Float Rate Note',
            ('FRN', None, 'FRN', True): 'Float Rate Note',
            ('FRN', 'Combination - Commodity Linked Note', 'FDE', False): 'Combination - Listed',
            ('FRN', 'Combination - Commodity Linked Note', 'FDE', True): 'Combination - Commodity Linked Note',
            ('FRN', 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            ('FRN', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            ('FRN', 'Combination - Equity Linked Note', None, False): 'Combination - Listed',
            ('FRN', 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            ('FRN', 'Combination - Equity Linked Note', 'FDE', False): 'Combination - Listed',
            ('FRN', 'Combination - Equity Linked Note', 'FDE', True): 'Combination - Equity Linked Note',
            ('FRN', 'Combination - Equity Linked Note', 'FRN', True): 'Combination - Equity Linked Note',
            ('FRN', 'Combination - FX Option', None, True): 'Float Rate Note',
            ('FRN', 'Combination - Index Linked Note', None, True): 'Combination - Index Linked Note',
            ('FRN', 'Combination - Rates Linked Note', None, False): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Rates Linked Note', 'FDE', False): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Rates Linked Note', 'FDE', True): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Struct Rate Note', None, False): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            ('FRN', 'Combination - Struct Rate Note', 'FDE', False): 'Combination - Listed',
            ('FRN', 'Combination - Struct Rate Note', 'FDE', True): 'Combination - Rates Linked Note',
            ('FRN', 'Passthrough', None, False): 'Passthrough',
            ('FRN', 'Passthrough', None, True): 'Passthrough',
            ('FRN', 'Passthrough', 'CLN', False): 'Passthrough',
            ('FRN', 'Passthrough', 'CLN', True): 'Passthrough',
            ('FRN', 'Passthrough', 'FRN', False): 'Passthrough',
            ('FRN', 'Passthrough', 'FRN', True): 'Passthrough',
            ('FRN', 'Structured Rates Deposit/Swap', None, False): 'Combination - Rates Linked Note',
            ('FRN', 'Structured Rates Deposit/Swap', None, True): 'Combination - Rates Linked Note',
            ('FRN', 'Structured Rates Note', None, False): 'Combination - Rates Linked Note',
            ('FRN', 'Structured Rates Note', None, True): 'Combination - Rates Linked Note',
            ('FRN', 'Term Loan', None, False): 'Term Loan',
            ('FRN', 'Term Loan', None, True): 'Term Loan',
            ('FTL', None, None, False): 'Foreign Currency Term Deposit',
            ('FTL', None, None, True): 'Foreign Currency Term Deposit',
            ('LBB', None, None, False): 'Bill',
            ('LBB', None, None, True): 'Bill',
            ('LEV CLN', None, None, False): 'Credit Link Note',
            ('LEV CLN', None, None, True): 'Credit Link Note',
            ('LNCD', None, None, False): 'Negotiable Certificate of Deposit',
            ('LNCD', None, None, True): 'Negotiable Certificate of Deposit',
            ('NCC', None, None, False): 'Negotiable Certificate of Deposit',
            ('NCC', None, None, True): 'Negotiable Certificate of Deposit',
            ('NCD', None, None, False): 'Negotiable Certificate of Deposit',
            ('NCD', None, None, True): 'Negotiable Certificate of Deposit',
            ('NCF', None, None, False): 'Negotiable Certificate of Deposit',
            ('NCF', None, None, True): 'Negotiable Certificate of Deposit',
            ('PM TLF', None, None, False): 'Term Loan',
            ('PM TLF', None, None, True): 'Term Loan',
            ('PM TLV', None, None, False): 'Term Loan',
            ('PM TLV', None, None, True): 'Term Loan',
            ('PN', None, None, False): 'Promissory Note',
            ('PN', None, None, True): 'Promissory Note',
            ('PRN', None, None, False): 'Promissory Note',
            ('PRN', None, None, True): 'Promissory Note',
            ('SS', 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
        },
    },
    'Future/Forward': {
        'Bond': {
            (None, None, None, False): 'Future - Bond',
            (None, None, None, True): 'Forward OTC - Bond',
            (None, 'Total Return Swap - Bond', None, False): 'Future - Bond',
            (None, 'Total Return Swap - Bond', None, True): 'Forward OTC - Bond',
        },
        'Commodity': {
            (None, None, None, False): 'Future - Commodity',
            (None, None, None, True): 'Forward OTC - Commodity',
        },
        'Commodity Index': {
            (None, None, None, False): 'Future - Commodity',
            (None, None, None, True): 'Forward OTC - Commodity',
        },
        'Curr': {
            (None, None, None, False): 'Future - Currency Forward',
            (None, None, None, True): 'FX Currency Forward',
        },
        'Stock': {
            (None, None, None, False): 'Future - Equity',
            (None, None, None, True): 'Forward OTC - Equity',
            (None, 'Future/Forward - Bond Index', None, False): 'Future - Equity',
            (None, 'Future/Forward - Bond Index', None, True): 'Forward OTC - Equity',
            ('FRN', None, None, False): 'Future - Equity',
            ('FRN', None, None, True): 'Forward OTC - Equity',
        },
        'EquityIndex': {
            (None, None, None, False): 'Future - Equity Index',
            (None, None, None, True): 'Forward OTC - Equity Index',
            (None, 'Combination - Equity Linked Note', None, False): 'Future - Equity Index',
            (None, 'Combination - Equity Linked Note', None, True): 'Forward OTC - Equity Index',
            (None, 'Funding Allocation', None, False): 'Future - Equity Index',
            (None, 'Funding Allocation', None, True): 'Forward OTC - Equity Index',
            (None, 'Future/Forward - Bond Index', None, False): 'Future - Bond Index',
            (None, 'Future/Forward - Bond Index', None, True): 'Forward OTC - Bond Index',
            (None, 'Passthrough', None, False): 'Passthrough',
            (None, 'Passthrough', None, True): 'Passthrough',
        },
        'ETF': {
            (None, None, None, False): 'Future - Exchange Traded Funds',
            (None, None, None, True): 'Forward OTC - Exchange Traded Funds',
            (None, 'Future/Forward - Bond Index', None, False): 'Future - Exchange Traded Funds',
            (None, 'Future/Forward - Bond Index', None, True): 'Forward OTC - Exchange Traded Funds',
        },
        'IndexLinkedBond': {
            (None, None, None, False): 'Future - Index Linked Bond',
            (None, None, None, True): 'Forward - Index Linked Bond',
        },
        'RateIndex': {
            (None, None, None, False): 'Future - RateIndex',
            (None, None, None, True): 'Future - RateIndex',
            (None, 'Future/Forward - Bond Index', None, False): 'Future - RateIndex',
            (None, 'Future/Forward - Bond Index', None, True): 'Future - RateIndex',
        },
        'Swap': {
            (None, None, None, False): 'Future - Swap',
        },
    },
    'Swap': {
        None: {
            (None, None, None, False): 'Interest Rate Swap',
            (None, None, None, True): 'Interest Rate Swap',
            (None, 'Combination - Credit Link Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Link Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Equity Linked Note', None, False): 'Interest Rate Swap',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Combination - FX Linked Note', None, False): 'Interest Rate Swap',
            (None, 'Combination - FX Linked Note', None, True): 'Interest Rate Swap',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Funding Allocation', None, False): 'Funding Allocation',
            (None, 'Funding Allocation', None, True): 'Funding Allocation',
            (None, 'IRS - Arranging and Advisory Fees', None, False): 'Arranging and Advisory Fees',
            (None, 'IRS - Arranging and Advisory Fees', None, True): 'Arranging and Advisory Fees',
            (None, 'IRS - CFC Interest Charge', None, False): 'CFC Interest Charge',
            (None, 'IRS - CFC Interest Charge', None, True): 'CFC Interest Charge',
            (None, 'IRS - Participation Fees', None, False): 'Participation Fees',
            (None, 'IRS - Participation Fees', None, True): 'Participation Fees',
            (None, 'IRS - Research Fees', None, False): 'Research Fees',
            (None, 'IRS - Research Fees', None, True): 'Research Fees',
            (None, 'Interest Rate Future', None, False): 'Interest Rate Future',
            (None, 'Interest Rate Future', None, True): 'Interest Rate Future',
            (None, 'IsEmpty', None, False): 'Interest Rate Swap',
            (None, 'IsEmpty', None, True): 'Interest Rate Swap',
            (None, 'Passthrough', None, False): 'Interest Rate Swap',
            (None, 'Passthrough', None, True): 'Interest Rate Swap',
            (None, 'Profit Remittance', None, False): 'Profit Remittance',
            (None, 'Profit Remittance', None, True): 'Profit Remittance',
            (None, 'Structured Rates Deposit/Swap', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Deposit/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, True): 'Combination - Rates Linked Note',
            ('FDI', 'Combination - Struct Rate Note', None, False): 'Combination - Rates Linked Note',
            ('FDI', 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
        },
    },
    'Option': {
        'Bond': {
            (None, None, None, False): 'Option - Bond',
            (None, None, None, True): 'Option OTC - Bond',
        },
        'Combination': {
            (None, None, None, True): 'Option OTC - Combination',
            (None, 'Option - Commodity Currency', None, True): 'Option OTC - Combination',
        },
        'Commodity': {
            (None, None, None, True): 'Option OTC - Commodity',
            (None, 'Combination - Commodity Linked Note', None, True): 'Option OTC - Commodity',
            (None, 'Combination - Index Linked Note', None, True): 'Option OTC - Commodity',
        },
        'Commodity Index': {
            (None, None, None, False): 'Option - Commodity',
            (None, None, None, True): 'Option OTC - Commodity',
        },
        'Curr': {
            (None, None, None, False): 'Option - Currency Forward',
            (None, None, None, True): 'Option OTC - Currency Forward',
            (None, 'Combination - FX Linked Note', None, False): 'Option - Currency Forward',
            (None, 'Combination - FX Linked Note', None, True): 'Option OTC - Currency Forward',
            (None, 'Combination - FX Option', None, True): 'Combination - FX Option',
            (None, 'Commodity Currency Swap', None, False): 'Option - Currency Forward',
            (None, 'Commodity Currency Swap', None, True): 'Option OTC - Currency Forward',
            (None, 'Option - Commodity Currency', None, False): 'Option - Commodity Currency',
            (None, 'Option - Commodity Currency', None, True): 'Option OTC - Commodity Currency',
        },
        'Stock': {
            (None, None, None, False): 'Option - Equity',
            (None, None, None, True): 'Option OTC - Equity',
            (None, 'Combination - Equity Linked Note', None, False): 'Option - Equity',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
        },
        'EquityIndex': {
            (None, None, None, False): 'Option - Equity Index',
            (None, None, None, True): 'Option OTC - Equity Index',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Equity Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Option - Bond Index', None, False): 'Option - Bond Index',
            (None, 'Synthetic Structured Deal', None, False): 'Option - Equity Index',
            (None, 'Synthetic Structured Deal', None, True): 'Option OTC - Equity Index',
            (None, 'Synthetic Structured Deal', None, 'IsEmpty'): 'Option OTC - Equity Index',
            ('FRN', None, None, False): 'Option - Equity Index',
            ('FRN', None, None, True): 'Option OTC - Equity Index',
        },
        'ETF': {
            (None, None, None, False): 'Option - Exchange Traded Funds',
            (None, None, None, True): 'Option OTC - Exchange Traded Funds',
        },
        'FRA': {
            (None, None, None, True): 'Option OTC - Forward Rate Agreement',
        },
        'Future/Forward': {
            (None, None, None, False): 'Option - Future/Forward',
            (None, None, None, True): 'Option OTC - Future/Forward',
            (None, 'Option - Commodity Future', None, False): 'Option - Commodity Future',
            (None, 'Option - Commodity Future', None, True): 'Option OTC - Commodity Future',
        },
        'Swap': {
            (None, None, None, True): 'Option OTC - Swap',
            (None, 'Combination - Equity Linked Note', None, True): 'Option OTC - Swap',
            (None, 'Combination - Index Linked Note', None, True): 'Option OTC - Swap',
        },
    },
    'Portfolio Swap': {
        None: {
            (None, None, None, False): 'Portfolio Swap',
            (None, None, None, True): 'Portfolio Swap',
            (None, 'Synthetic Structured Deal', None, False): 'Synthetic Structured Deal',
            (None, 'Synthetic Structured Deal', None, True): 'Synthetic Structured Deal',
        },
    },
    'Repo/Reverse': {
        'Bill': {
            (None, None, None, False): 'Repurchase Agreement - Bill',
            (None, None, None, True): 'Repurchase Agreement - Bill',
        },
        'Bond': {
            (None, None, None, False): 'Repurchase Agreement - Bond',
            (None, None, None, True): 'Repurchase Agreement - Bond',
        },
        'CD': {
            (None, None, None, False): 'Repurchase Agreement - Certificate of Deposit',
            (None, None, None, True): 'Repurchase Agreement - Certificate of Deposit',
        },
        'Combination': {
            (None, None, None, False): 'Repurchase Agreement - Combination',
            (None, None, None, True): 'Repurchase Agreement - Combination',
        },
        'Deposit': {
            (None, None, None, False): 'Repurchase Agreement - Deposit',
            (None, None, None, True): 'Repurchase Agreement - Deposit',
        },
        'Stock': {
            (None, None, None, False): 'Repurchase Agreement - Equity',
            (None, None, None, True): 'Repurchase Agreement - Equity',
        },
        'FRN': {
            (None, None, None, False): 'Repurchase Agreement - Forward Rate Note',
            (None, None, None, True): 'Repurchase Agreement - Forward Rate Note',
        },
        'IndexLinkedBond': {
            (None, None, None, False): 'Repurchase Agreement - Index Linked Bond',
            (None, None, None, True): 'Repurchase Agreement - Index Linked Bond',
        },
        'Zero': {
            (None, None, None, False): 'Repurchase Agreement - Zero',
            (None, None, None, True): 'Repurchase Agreement - Zero',
        },
    },
    'SecurityLoan': {
        'Bill': {
            (None, None, None, False): 'SecurityLoan - Bill',
            (None, None, None, True): 'SecurityLoan - Bill',
        },
        'Bond': {
            (None, None, None, False): 'SecurityLoan - Bond',
            (None, None, None, True): 'SecurityLoan - Bond',
        },
        'CD': {
            (None, None, None, False): 'SecurityLoan - Certificate of Deposit',
            (None, None, None, True): 'SecurityLoan - Certificate of Deposit',
        },
        'Deposit': {
            (None, None, None, False): 'SecurityLoan - Deposit Loan',
            (None, None, None, True): 'SecurityLoan - Deposit Loan',
        },
        'Stock': {
            (None, None, None, False): 'SecurityLoan - Equity',
            (None, None, None, True): 'SecurityLoan - Equity',
        },
        'ETF': {
            (None, None, None, False): 'SecurityLoan - Exchange Traded Funds',
            (None, None, None, True): 'SecurityLoan - Exchange Traded Funds',
        },
        'FRN': {
            (None, None, None, False): 'SecurityLoan - Forward Rate Note',
            (None, None, None, True): 'SecurityLoan - Forward Rate Note',
        },
        'IndexLinkedBond': {
            (None, None, None, False): 'SecurityLoan - Index Linked Bond',
            (None, None, None, True): 'SecurityLoan - Index Linked Bond',
        },
    },
    'IndexLinkedSwap': {
        None: {
            (None, None, None, False): 'Swap - Index Linked',
            (None, None, None, True): 'Swap - Index Linked',
            (None, None, 'CLN', False): 'Credit Link Note',
            (None, None, 'CLN', True): 'Credit Link Note',
            (None, 'Combination - Commodity Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Commodity Linked Note', None, True): 'Combination - Commodity Linked Note',
            (None, 'Combination - Credit Linked Depo', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Depo', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Equity Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Combination - FX option', None, True): 'Swap - Index Linked',
            (None, 'Combination - Index Linked Note', None, False): 'Combination - Listed',
            (None, 'Combination - Index Linked Note', None, True): 'Combination - Index Linked Note',
            (None, 'Combination - Rates Linked Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Rates Linked Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Depo/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Combination - Struct Rate Note', None, True): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Deposit/Swap', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Deposit/Swap', None, True): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, False): 'Combination - Rates Linked Note',
            (None, 'Structured Rates Note', None, True): 'Combination - Rates Linked Note',
        },
    },
    'VarianceSwap': {
        None: {
            (None, None, None, False): 'Swap - Variance Equity Index',
            (None, None, None, True): 'Swap OTC - Variance Equity Index',
        },
    },
    'TotalReturnSwap': {
        None: {
            (None, None, None, False): 'Total Return Swap',
            (None, None, None, True): 'Total Return Swap',
            (None, 'Combination - Commodity Linked Note', None, False): 'Combination - Credit Linked Note',
            (None, 'Combination - Commodity Linked Note', None, True): 'Combination - Credit Linked Note',
            (None, 'Combination - Credit Linked Note', None, False): 'Total Return Swap',
            (None, 'Combination - Credit Linked Note', None, True): 'Total Return Swap',
            (None, 'Combination - Equity Linked Note', None, False): 'Combination - Equity Linked Note',
            (None, 'Combination - Equity Linked Note', None, True): 'Combination - Equity Linked Note',
            (None, 'Combination - Index Linked Note', None, False): 'Combination - Index Linked Note',
            (None, 'Combination - Index Linked Note', None, True): 'Combination - Index Linked Note',
            (None, 'Future/Forward - Bond Index', None, False): 'Total Return Swap',
            (None, 'Future/Forward - Bond Index', None, True): 'Total Return Swap',
            (None, 'Option - Commodity Currency', None, False): 'Total Return Swap',
            (None, 'Option - Commodity Currency', None, True): 'Total Return Swap',
            (None, 'Total Return Swap - Bond', None, False): 'Total Return Swap - Bond',
            (None, 'Total Return Swap - Bond', None, True): 'Total Return Swap - Bond',
        },
    },
    'Bill': {
        None: {
            ('BA', None, None, False): 'Bill',
            ('BA', None, None, True): 'Bill',
            ('Comm Paper', None, None, False): 'Commercial Paper',
            ('Comm Paper', None, None, True): 'Commercial Paper',
            ('FRN', None, None, False): 'Float Rate Note',
            ('FRN', None, None, True): 'Float Rate Note',
            ('LBB', None, None, False): 'Bill',
            ('LBB', None, None, True): 'Bill',
            ('NCC', None, None, False): 'Negotiable Certificate of Deposit',
            ('NCC', None, None, True): 'Negotiable Certificate of Deposit',
            ('NCD', None, None, False): 'Negotiable Certificate of Deposit',
            ('NCD', None, None, True): 'Negotiable Certificate of Deposit',
            ('NCF', None, None, False): 'Negotiable Certificate of Deposit',
            ('NCF', None, None, True): 'Negotiable Certificate of Deposit',
            ('PN', None, None, False): 'Promissory Note',
            ('PN', None, None, True): 'Promissory Note',
            ('PRN', None, None, False): 'Promissory Note',
            ('PRN', None, None, True): 'Promissory Note',
            ('SARB Debenture', None, None, False): 'Bill',
            ('SARB Debenture', None, None, True): 'Bill',
            ('TB', None, None, False): 'Bill',
            ('TB', None, None, True): 'Bill',
        },
    },
}


def get_instype(trade):
    instrument = trade.Instrument()
    instype = instrument.InsType()
    if instype == 'Curr':
        if trade.IsFxSpot():
            return 'FX Spot'
        if trade.IsFxSwap():
            return 'FX Swap'
        if trade.IsFxForward():
            return 'FX Forward'
        return 'Cash'
    if instype == 'Future/Forward':
        if instrument.Underlying().InsType() == 'Curr' and instrument.IsFxNdf():
            return 'NDF'
    return instype


def get_und_instype(trade):
    instrument = trade.Instrument()
    if instrument.Underlying():
        return instrument.Underlying().InsType()
    return None


def get_fund_instype(trade):
    return (trade.AdditionalInfo().Funding_Instype() 
            if trade.AdditionalInfo().Funding_Instype() else None)


def get_mm_instype(trade):
    return (trade.AdditionalInfo().MM_Instype() 
            if trade.AdditionalInfo().MM_Instype() else None)


def get_ins_override(trade):
    if is_amwi_cleared_trade(trade):
        return None
    try:
        return (trade.AdditionalInfo().InsOverride() 
                if trade.AdditionalInfo().InsOverride() else None)
    except:
        LOGGER.exception('Failed to get InsOverride for trade %s.' % trade.Oid())
        return None


def get_product(trade):
    instype = get_instype(trade)
    und_instype = get_und_instype(trade)
    fund_instype = get_fund_instype(trade)
    mm_instype = get_mm_instype(trade)
    ins_override = get_ins_override(trade)
    otc = trade.Instrument().Otc()
    try:
        return MAPPING[instype][und_instype][(mm_instype, ins_override, fund_instype, otc)]
    except KeyError:
        LOGGER.warning('No mapping found for [%s][%s][(%s, %s, %s, %s)].' 
                       % (instype, und_instype, mm_instype, ins_override, fund_instype, otc))
        try:
            return DEFAULTS[instype]
        except KeyError:
            LOGGER.warning('No default mapping found for [%s].' % instype)
    return instype

