""" Compiled: 2020-09-18 10:38:52 """

#__src_file__ = "extensions/ArenaExcel/../../Pace/Messages/Contracts/Tk/Messages/Contracts_Tk_Messages_TkEnumerations.py"
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Contracts/Tk/Messages/TkEnumerations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Contracts/Tk/Messages/TkEnumerations.proto',
  package='Tk',
  serialized_pb=_b('\n*Contracts/Tk/Messages/TkEnumerations.proto\x12\x02Tk*W\n\x0f\x65\x44\x61tePeriodType\x12\x0c\n\x08\x44PT_NONE\x10\x01\x12\x0b\n\x07\x44PT_DAY\x10\x02\x12\x0c\n\x08\x44PT_WEEK\x10\x03\x12\r\n\tDPT_MONTH\x10\x04\x12\x0c\n\x08\x44PT_YEAR\x10\x05*\x8e\x01\n\x0c\x65VariantType\x12\x0c\n\x08PVT_NONE\x10\x01\x12\x0c\n\x08PVT_BOOL\x10\x02\x12\r\n\tPVT_INT32\x10\x03\x12\r\n\tPVT_INT64\x10\x04\x12\x0e\n\nPVT_DOUBLE\x10\x05\x12\x0e\n\nPVT_STRING\x10\x06\x12\x10\n\x0cPVT_DATETIME\x10\x07\x12\x12\n\x0ePVT_DATEPERIOD\x10\t*\x98\x01\n\x16\x65\x46ormattableStringType\x12\x13\n\x0f\x46ST_USE_DEFAULT\x10\x01\x12\x16\n\x12\x46ST_DATE_TIME_LONG\x10\x02\x12\x17\n\x13\x46ST_DATE_TIME_SHORT\x10\x03\x12\x1b\n\x17\x46ST_DATE_TIME_TIME_ONLY\x10\x04\x12\x1b\n\x17\x46ST_DATE_TIME_DATE_ONLY\x10\x05* \n\x10\x65\x43ompareOperator\x12\x0c\n\x08\x43O_EQUAL\x10\x00*)\n\x10\x65LogicalOperator\x12\n\n\x06LO_AND\x10\x00\x12\t\n\x05LO_OR\x10\x01*\x88\x01\n\x0e\x65TextMatchMode\x12\r\n\tTMM_EXACT\x10\x00\x12\x1a\n\x16TMM_REGULAR_EXPRESSION\x10\x01\x12\x11\n\rTMM_WILDCARDS\x10\x02\x12\x13\n\x0fTMM_BEGINS_WITH\x10\x03\x12\x11\n\rTMM_ENDS_WITH\x10\x04\x12\x10\n\x0cTMM_CONTAINS\x10\x05*K\n\x0c\x65ValueStatus\x12\t\n\x05VS_OK\x10\x00\x12\x0b\n\x07VS_NULL\x10\x01\x12\x10\n\x0cVS_EXCEPTION\x10\x02\x12\x11\n\rVS_INCOMPLETE\x10\x03*D\n\x0c\x65HabitatType\x12\r\n\thtDefault\x10\x01\x12\r\n\thtPrivate\x10\x02\x12\x16\n\x12htNamedEnvironment\x10\x03\x42\x1b\n\x11\x63om.frontarena.tkB\x04\x45numH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EDATEPERIODTYPE = _descriptor.EnumDescriptor(
  name='eDatePeriodType',
  full_name='Tk.eDatePeriodType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DPT_NONE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPT_DAY', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPT_WEEK', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPT_MONTH', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPT_YEAR', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=50,
  serialized_end=137,
)
_sym_db.RegisterEnumDescriptor(_EDATEPERIODTYPE)

eDatePeriodType = enum_type_wrapper.EnumTypeWrapper(_EDATEPERIODTYPE)
_EVARIANTTYPE = _descriptor.EnumDescriptor(
  name='eVariantType',
  full_name='Tk.eVariantType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PVT_NONE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PVT_BOOL', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PVT_INT32', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PVT_INT64', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PVT_DOUBLE', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PVT_STRING', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PVT_DATETIME', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PVT_DATEPERIOD', index=7, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=140,
  serialized_end=282,
)
_sym_db.RegisterEnumDescriptor(_EVARIANTTYPE)

eVariantType = enum_type_wrapper.EnumTypeWrapper(_EVARIANTTYPE)
_EFORMATTABLESTRINGTYPE = _descriptor.EnumDescriptor(
  name='eFormattableStringType',
  full_name='Tk.eFormattableStringType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FST_USE_DEFAULT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FST_DATE_TIME_LONG', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FST_DATE_TIME_SHORT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FST_DATE_TIME_TIME_ONLY', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FST_DATE_TIME_DATE_ONLY', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=285,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_EFORMATTABLESTRINGTYPE)

eFormattableStringType = enum_type_wrapper.EnumTypeWrapper(_EFORMATTABLESTRINGTYPE)
_ECOMPAREOPERATOR = _descriptor.EnumDescriptor(
  name='eCompareOperator',
  full_name='Tk.eCompareOperator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CO_EQUAL', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=439,
  serialized_end=471,
)
_sym_db.RegisterEnumDescriptor(_ECOMPAREOPERATOR)

eCompareOperator = enum_type_wrapper.EnumTypeWrapper(_ECOMPAREOPERATOR)
_ELOGICALOPERATOR = _descriptor.EnumDescriptor(
  name='eLogicalOperator',
  full_name='Tk.eLogicalOperator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LO_AND', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LO_OR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=473,
  serialized_end=514,
)
_sym_db.RegisterEnumDescriptor(_ELOGICALOPERATOR)

eLogicalOperator = enum_type_wrapper.EnumTypeWrapper(_ELOGICALOPERATOR)
_ETEXTMATCHMODE = _descriptor.EnumDescriptor(
  name='eTextMatchMode',
  full_name='Tk.eTextMatchMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TMM_EXACT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TMM_REGULAR_EXPRESSION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TMM_WILDCARDS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TMM_BEGINS_WITH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TMM_ENDS_WITH', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TMM_CONTAINS', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=517,
  serialized_end=653,
)
_sym_db.RegisterEnumDescriptor(_ETEXTMATCHMODE)

eTextMatchMode = enum_type_wrapper.EnumTypeWrapper(_ETEXTMATCHMODE)
_EVALUESTATUS = _descriptor.EnumDescriptor(
  name='eValueStatus',
  full_name='Tk.eValueStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VS_OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VS_NULL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VS_EXCEPTION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VS_INCOMPLETE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=655,
  serialized_end=730,
)
_sym_db.RegisterEnumDescriptor(_EVALUESTATUS)

eValueStatus = enum_type_wrapper.EnumTypeWrapper(_EVALUESTATUS)
_EHABITATTYPE = _descriptor.EnumDescriptor(
  name='eHabitatType',
  full_name='Tk.eHabitatType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='htDefault', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='htPrivate', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='htNamedEnvironment', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=732,
  serialized_end=800,
)
_sym_db.RegisterEnumDescriptor(_EHABITATTYPE)

eHabitatType = enum_type_wrapper.EnumTypeWrapper(_EHABITATTYPE)
DPT_NONE = 1
DPT_DAY = 2
DPT_WEEK = 3
DPT_MONTH = 4
DPT_YEAR = 5
PVT_NONE = 1
PVT_BOOL = 2
PVT_INT32 = 3
PVT_INT64 = 4
PVT_DOUBLE = 5
PVT_STRING = 6
PVT_DATETIME = 7
PVT_DATEPERIOD = 9
FST_USE_DEFAULT = 1
FST_DATE_TIME_LONG = 2
FST_DATE_TIME_SHORT = 3
FST_DATE_TIME_TIME_ONLY = 4
FST_DATE_TIME_DATE_ONLY = 5
CO_EQUAL = 0
LO_AND = 0
LO_OR = 1
TMM_EXACT = 0
TMM_REGULAR_EXPRESSION = 1
TMM_WILDCARDS = 2
TMM_BEGINS_WITH = 3
TMM_ENDS_WITH = 4
TMM_CONTAINS = 5
VS_OK = 0
VS_NULL = 1
VS_EXCEPTION = 2
VS_INCOMPLETE = 3
htDefault = 1
htPrivate = 2
htNamedEnvironment = 3


DESCRIPTOR.enum_types_by_name['eDatePeriodType'] = _EDATEPERIODTYPE
DESCRIPTOR.enum_types_by_name['eVariantType'] = _EVARIANTTYPE
DESCRIPTOR.enum_types_by_name['eFormattableStringType'] = _EFORMATTABLESTRINGTYPE
DESCRIPTOR.enum_types_by_name['eCompareOperator'] = _ECOMPAREOPERATOR
DESCRIPTOR.enum_types_by_name['eLogicalOperator'] = _ELOGICALOPERATOR
DESCRIPTOR.enum_types_by_name['eTextMatchMode'] = _ETEXTMATCHMODE
DESCRIPTOR.enum_types_by_name['eValueStatus'] = _EVALUESTATUS
DESCRIPTOR.enum_types_by_name['eHabitatType'] = _EHABITATTYPE


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.frontarena.tkB\004EnumH\003'))
# @@protoc_insertion_point(module_scope)
