# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Contracts/IndexSearch/Messages/IndexSearchScope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Contracts/IndexSearch/Messages/IndexSearchScope.proto',
  package='IndexSearch.Scope.Msg',
  serialized_pb=_b('\n5Contracts/IndexSearch/Messages/IndexSearchScope.proto\x12\x15IndexSearch.Scope.Msg\"+\n\nDefinition\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tindexName\x18\x02 \x01(\t\"\x17\n\tResultKey\x12\n\n\x02id\x18\x01 \x01(\x03\"\x14\n\x06Result\x12\n\n\x02id\x18\x01 \x01(\x03\x42)\n com.frontarena.indexsearch.scopeB\x03MsgH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEFINITION = _descriptor.Descriptor(
  name='Definition',
  full_name='IndexSearch.Scope.Msg.Definition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='IndexSearch.Scope.Msg.Definition.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='indexName', full_name='IndexSearch.Scope.Msg.Definition.indexName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=123,
)


_RESULTKEY = _descriptor.Descriptor(
  name='ResultKey',
  full_name='IndexSearch.Scope.Msg.ResultKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='IndexSearch.Scope.Msg.ResultKey.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=148,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='IndexSearch.Scope.Msg.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='IndexSearch.Scope.Msg.Result.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['Definition'] = _DEFINITION
DESCRIPTOR.message_types_by_name['ResultKey'] = _RESULTKEY
DESCRIPTOR.message_types_by_name['Result'] = _RESULT

Definition = _reflection.GeneratedProtocolMessageType('Definition', (_message.Message,), dict(
  DESCRIPTOR = _DEFINITION,
  __module__ = 'Contracts.IndexSearch.Messages.IndexSearchScope_pb2'
  # @@protoc_insertion_point(class_scope:IndexSearch.Scope.Msg.Definition)
  ))
_sym_db.RegisterMessage(Definition)

ResultKey = _reflection.GeneratedProtocolMessageType('ResultKey', (_message.Message,), dict(
  DESCRIPTOR = _RESULTKEY,
  __module__ = 'Contracts.IndexSearch.Messages.IndexSearchScope_pb2'
  # @@protoc_insertion_point(class_scope:IndexSearch.Scope.Msg.ResultKey)
  ))
_sym_db.RegisterMessage(ResultKey)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'Contracts.IndexSearch.Messages.IndexSearchScope_pb2'
  # @@protoc_insertion_point(class_scope:IndexSearch.Scope.Msg.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.frontarena.indexsearch.scopeB\003MsgH\003'))
# @@protoc_insertion_point(module_scope)

