import acm

list = ['9803AFS HEDGED',
'9803AFS OUTRIGHT',
'9803AFS_Bills',
'9803CARRIES',
'9803FVTbills',
'9803HFT',
'9803_FV Bonds Hedged Futures',
'ABCAP FUND 2475',
'ABCAP FUND 2475 TANGO',
'ATIS',
'Africa_Accr_M',
'Africa_Accr_R',
'Allocate_Pfolio_GT_Internal',
'Alpha ring-fenced Accrual',
'BESA Investments_AFS',
'Barclays Africa Syndicate Bridge Loan',
'Barclays Africa Syndicate Loans',
'Bridge Facilities - Africa',
'CAPMKT ARB 9808',
'CD ACCRUALS 1574',
'CD ACCRUALS 2793',
'CD_ACCESS NOTES ACCRUALS',
'CD_STRCREDIT',
'COMM ACCRUALS 1574',
'COMM ACCRUALS 2793',
'CORPORATE LEND 3304',
'CPF AFS',
'CSA Non Cash Collateral',
'CSA Non ZAR Collateral',
'Call_3304',
'Call_3304 CRP Ln GAUTENG',
'Call_9808',
'Call_ASL_Repos',
'Call_SBL_Agency Collateral',
'Call_SBL_Fixed Income',
'Cash equities ETA revenue',
'Cession and Pledge',
'Collateral Optimisation',
'Corp Alp Accrual',
'Corp Lend 5613 DBN',
'DT Vanilla Trade Loans ZAR',
'DT Vanilla Trade loans Non ZAR',
'Delta One_MTN',
'EF_9803',
'EQ ACCRUALS 1574',
'EQ ACCRUALS 2793',
'ERM CFH',
'ERM CFH Equity',
'ERM CFH Funding Desk',
'ERM CFH NSBB CIBW',
'ERM CFH NSBB RBB',
'ERM CFH NSBB WHOLESALE',
'ERM FVH Inflation',
'ERM FVH LA',
'ERM FVH R157',
'ERM FVH R186',
'ERM FVH Senior Debt',
'ERM FVH Sub-ordinated Debt',
'ERM_FVH Bond Futures',
'Euro Funding Desk',
'FX ACCRUALS 1574',
'GT 2476 FUNDING LONG TERM SURPPLUS LA',
'GT 2476 FUNDING SHORT TERM SURPPLUS LA',
'GT 2657 FX DEBT',
'GT ABL Fixed Deposits',
'GT Accrued Swaps - CIB',
'GT CIB LA Repo',
'GT CIBW Underlying',
'GT Fair Value Funding',
'GT Funding Int - FTP',
'GT Funding Internal',
'GT Gov CPI Hedged',
'GT Gov Inflation',
'GT LA CDS',
'GT LT Carries',
'GT_FX_HEDGING_EUR',
'GT_FX_HEDGING_GBP',
'GT_FX_HEDGING_USD',
'GT_LA_Bond _FV',
'GT_LA_LEVEL2',
'GT_LA_LEVEL2 REPOS',
'GT_LA_Non ZAR',
'IB Lon Accrual',
'IB iMpu AFS',
'IMF Margin',
'IRD ACCRUALS 1574',
'IRD ACCRUALS 2793',
'IRD ACCRUALS 2794',
'Imp Repo 1 - CP',
'Imp Repo 1 - LREC',
'Impume 2 - CP',
'Impume 2 - LREC',
'JOB15',
'JOB7',
'LinTradingCFD_PB',
'Local Client AC',
'Money Markets - Subsidy Pot',
'NZ Accounting Mismatch',
'New_CFD',
'New_Local CFD',
'Non Zar Bonds',
'Non Zar Liquid Assets',
'Ovland_wealth_1',
'Ovland_wealth_2',
'PB_CALLACCNT_AAM_GOVI',
'PB_CALLACCNT_AAM_LINK',
'PB_CALLACCNT_ACU2P',
'PB_CALLACCNT_ALTRESOF',
'PB_CALLACCNT_ATPOINT1',
'PB_CALLACCNT_ATTOTAL1',
'PB_CALLACCNT_BELLROC',
'PB_CALLACCNT_FAIRBINK',
'PB_CALLACCNT_FAIRFIG',
'PB_CALLACCNT_FAIRMASH',
'PB_CALLACCNT_FAIRMP310',
'PB_CALLACCNT_FAIRPART',
'PB_CALLACCNT_FAIRWOOD',
'PB_CALLACCNT_KAIBINK',
'PB_CALLACCNT_KAISICAV',
'PB_CALLACCNT_KAISOPT',
'PB_CALLACCNT_KAIZSOF',
'PB_CALLACCNT_LAURBO',
'PB_CALLACCNT_MAP210E',
'PB_CALLACCNT_NITROBLUE',
'PB_CALLACCNT_SNORPHOL',
'PB_CALLACCNT_TERENOVE',
'PB_CALLACCNT_TOFT',
'PB_CALLACCNT_TOWNOVSBI',
'PB_CALLACCNT_TOWNOVTEM',
'PB_CALLACCNT_TOWSIT',
'PB_CALL_MARGIN_BELLROCK_1.5X',
'PB_CALL_MARGIN_BLUE INK_SP',
'PB_CALL_MARGIN_BLUEINK_FF',
'PB_CALL_MARGIN_CAFM_MAP280',
'PB_CALL_MARGIN_Freestone_BlueInk_FI',
'PB_CALL_MARGIN_MAP106',
'PB_CALL_MARGIN_MAP_150_FI',
'PB_CALL_MARGIN_SUNRISE',
'PB_FINANCING',
'PB_FINANCING_AAM_GOVI',
'PB_FINANCING_AAM_LINK',
'PB_FINANCING_AAM_SBEQ',
'PB_FINANCING_AAM_SBPROP',
'PB_FINANCING_ACU2P',
'PB_FINANCING_ALTRESOF',
'PB_FINANCING_ATPOINT1',
'PB_FINANCING_ATTOTAL1',
'PB_FINANCING_BELLROC',
'PB_FINANCING_BELLROCK_1.5X',
'PB_FINANCING_BLUE INK_SP',
'PB_FINANCING_BLUEINK_FF',
'PB_FINANCING_CORINCIS2',
'PB_FINANCING_CORINCISC',
'PB_FINANCING_EMPFLEX',
'PB_FINANCING_EMPIRI',
'PB_FINANCING_FAIRBINK',
'PB_FINANCING_FAIRFIG',
'PB_FINANCING_FAIRMASH',
'PB_FINANCING_FAIRMP310',
'PB_FINANCING_FAIRPART',
'PB_FINANCING_FAIRWOOD',
'PB_FINANCING_Freestone_BlueInk_FI',
'PB_FINANCING_KAIBINK',
'PB_FINANCING_KAISICAV',
'PB_FINANCING_KAISOPT',
'PB_FINANCING_KAIZSOF',
'PB_FINANCING_LARMLAIP',
'PB_FINANCING_LAURBO',
'PB_FINANCING_MAP106',
'PB_FINANCING_MAP210E',
'PB_FINANCING_MAP501B',
'PB_FINANCING_MAPMOM',
'PB_FINANCING_MAP_150_FI',
'PB_FINANCING_NITROBLUE',
'PB_FINANCING_NITROFIRE',
'PB_FINANCING_PRSADVTAA',
'PB_FINANCING_PRSGNLIFE',
'PB_FINANCING_SNORPHOL',
'PB_FINANCING_SUNRISE',
'PB_FINANCING_TERENOVE',
'PB_FINANCING_TOFT',
'PB_FINANCING_TOWELS',
'PB_FINANCING_TOWNOVSBI',
'PB_FINANCING_TOWNOVTEM',
'PB_FINANCING_TOWSIT',
'PB_FINANCING_TOWTEM',
'PB_FINANCING_VALISTABLE',
'PB_SBL_FEE_AAM_GOVI',
'PB_SBL_FEE_AAM_LINK',
'PB_SBL_FEE_AAM_SBEQ',
'PB_SBL_FEE_AAM_SBPROP',
'PB_SBL_FEE_ACU2P',
'PB_SBL_FEE_ARI',
'PB_SBL_FEE_ATPOINT1',
'PB_SBL_FEE_ATTOTAL1',
'PB_SBL_FEE_Acumen_BlueInk_FI',
'PB_SBL_FEE_Acumen_Invest_FI',
'PB_SBL_FEE_BELLROCK_1.5X',
'PB_SBL_FEE_BLUE INK_SP',
'PB_SBL_FEE_BLUEINK_FF',
'PB_SBL_FEE_BRAIT_TRUST',
'PB_SBL_FEE_CAFM_MAP280',
'PB_SBL_FEE_COGITOPT1',
'PB_SBL_FEE_CRUXHF1',
'PB_SBL_FEE_FAIRBINK',
'PB_SBL_FEE_FAIRFIG',
'PB_SBL_FEE_FAIRMASH',
'PB_SBL_FEE_FAIRMP310',
'PB_SBL_FEE_FAIRPART',
'PB_SBL_FEE_FAIRWOOD',
'PB_SBL_FEE_Freestone_BlueInk_FI',
'PB_SBL_FEE_KAIZSOF',
'PB_SBL_FEE_LARMLAIP',
'PB_SBL_FEE_MAP100',
'PB_SBL_FEE_MAP104SE',
'PB_SBL_FEE_MAP106',
'PB_SBL_FEE_MAP109',
'PB_SBL_FEE_MAP110',
'PB_SBL_FEE_MAP130',
'PB_SBL_FEE_MAP_111',
'PB_SBL_FEE_MAP_150_FI',
'PB_SBL_FEE_MAP_250_FI',
'PB_SBL_FEE_MAP_501',
'PB_SBL_FEE_MARKSOL',
'PB_SBL_FEE_MATRIXZAR',
'PB_SBL_FEE_MOMTMRETL',
'PB_SBL_FEE_MROC',
'PB_SBL_FEE_NMRQL',
'PB_SBL_FEE_NMRQLMCO',
'PB_SBL_FEE_Nitrogen_Trust',
'PB_SBL_FEE_OAKMANCO',
'PB_SBL_FEE_PRSADVTAA',
'PB_SBL_FEE_PRSGNLIFE',
'PB_SBL_FEE_PRSTARBHF',
'PB_SBL_FEE_SEFI',
'PB_SBL_FEE_SIMHFAMS',
'PB_SBL_FEE_SOUTHRETL',
'PB_SBL_FEE_TEREBINK',
'PB_SBL_FEE_TEREFI',
'PB_SBL_FEE_TERENOVE',
'PB_SBL_FEE_TERETR',
'PB_SBL_FEE_TOFT',
'PB_SBL_FEE_VALISTABLE',
'PB_SBL_OAKHAVEN',
'SBL Arbitrage Baskets Loans',
'SBL Arbitrage Reserved Basket Loans',
'SBL COMPLEX FICC SNP BOND COLLATERAL LO',
'SBL Cash Equities Loans',
'SBL Cash Equities Loans ACS',
'SBL Client Trades Loans',
'SBL Client Trades Loans ACS',
'SBL Delta One Bespoke Structures',
'SBL Delta_1_JV Loans',
'SBL Eq CFD Loans',
'SBL Equity Exotics Loans',
'SBL Equity Exotics Loans ACS',
'SBL LinTradingCFD Loans',
'SBL LinTradingNon CFD -Mapps',
'SBL LinTradingNonCFD Loans ACS',
'SBL NS Risk Loans',
'SBL Prime Client 1 Loans',
'SBL SNP 44032',
'SBL SNP 47415',
'SBL SNP Bond Collateral Loans',
'SBL ST 44008',
'SBL ST 44008 ACS',
'SBL ST 44016',
'SBL ST 44016 ACS',
'SBL ST 44024',
'SBL ST 44040',
'SBL ST 44263',
'SBL ST 44271',
'SBL ST 47142',
'SBL Single Stock FC LHC Structure',
'SBL Single Stock FC Loans',
'SBL Single Stock FC Reserve PTH',
'SBL Single Stock FC SHP Structure',
'SBL Single Stock RT Loans',
'SBL Small Cap SSO Loans',
'SBL Small Cap SSO Loans ACS',
'SBL_BLUE_INK_FI_Fee',
'SBL_LEIPS Structure',
'SBL_MAPPS_Bonds',
'SBL_MAPPS_Equities',
'SBL_Structured Bond Loans',
'SF 1511 Non ZAR Accrual',
'SF 3065',
'SF 3276 Non ZAR Accrual',
'SF 5000',
'SF 5001',
'SF 7530',
'SF 7533',
'SF 7536',
'SF 7537',
'SF 7538',
'SF 9362',
'SF 9609 Non ZAR FV',
'SF Carries And Repos',
'SF2624',
'SL Single Stock Structure',
'SL_ALPHA Structure',
'SL_Satu',
'SND Commodities BTB AC',
'SND Commodities Funding Mismatch',
'SND Commodities Mismatch AC',
'SND Credit BTB AC',
'SND Credit Funding Mismatch',
'SND Credit Mismatch AC',
'SND Equity BTB AC',
'SND Equity Funding Mismatch',
'SND Equity Mismatch AC',
'SND Other BTB AC',
'SND Other Funding Mismatch',
'SND Rates BTB AC',
'SND Rates Funding Mismatch',
'SND Rates Mismatch AC',
'SND Trigger Mismatch AC',
'STRUCTURING_9165',
'Securities Lending (Agency)',
'Strategic loan port (Africa) - Accrl',
'Term_3014',
'Transaction FX Risk Management',
'new_Equity Script Lending']

for item in list:
    contextLink = acm.FContextLink()
    contextLink.Context('FC Accrual Books')
    contextLink.MappingType('Portfolio')
    contextLink.Name('AP_MM')
    contextLink.Portfolio(item)
    contextLink.Type('Accounting Parameter')
    try:
        contextLink.Commit()
        print(('Adding portfolio %s to Context Definition %s' %(item, 'FC Accrual Books')))
    except Exception as e:
        print(('Unable to add portfolio %s to the Context Definition %s' %(item, 'FC Accrual Books')))
