
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PositionStorageDeleteMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Contracts_Tk_Messages_TkMessages


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PositionStorageDeleteMessages.proto',
  package='PositionStorage.Delete.Msg',
  serialized_pb=_b('\n#PositionStorageDeleteMessages.proto\x12\x1aPositionStorage.Delete.Msg\x1a&Contracts/Tk/Messages/TkMessages.proto\"\x9e\x01\n\nDefinition\x12%\n\rsessionFilter\x18\x01 \x01(\x0b\x32\x0e.Tk.Msg.Filter\x12$\n\x0c\x63olumnFilter\x18\x02 \x01(\x0b\x32\x0e.Tk.Msg.Filter\x12&\n\x0epositionFilter\x18\x03 \x01(\x0b\x32\x0e.Tk.Msg.Filter\x12\x1b\n\x13\x64\x65leteValueSessions\x18\x04 \x01(\x08\"\x82\x01\n\x10RecordTypeResult\x12\x14\n\x0ctotalRecords\x18\x01 \x01(\x03\x12\x16\n\x0e\x64\x65letedRecords\x18\x02 \x01(\x03\x12\x12\n\nrecordType\x18\x03 \x01(\x05\x12\x16\n\x0e\x66\x61iledRecordId\x18\x04 \x01(\x03\x12\x14\n\x0c\x65rrorMessage\x18\x05 \x01(\t\"Q\n\x06Result\x12G\n\x11recordTypeResults\x18\x06 \x03(\x0b\x32,.PositionStorage.Delete.Msg.RecordTypeResult\"\x17\n\tResultKey\x12\n\n\x02id\x18\x01 \x01(\x05\x42\x02H\x03')
  ,
  dependencies=[Contracts_Tk_Messages_TkMessages.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEFINITION = _descriptor.Descriptor(
  name='Definition',
  full_name='PositionStorage.Delete.Msg.Definition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionFilter', full_name='PositionStorage.Delete.Msg.Definition.sessionFilter', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columnFilter', full_name='PositionStorage.Delete.Msg.Definition.columnFilter', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='positionFilter', full_name='PositionStorage.Delete.Msg.Definition.positionFilter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleteValueSessions', full_name='PositionStorage.Delete.Msg.Definition.deleteValueSessions', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=266,
)


_RECORDTYPERESULT = _descriptor.Descriptor(
  name='RecordTypeResult',
  full_name='PositionStorage.Delete.Msg.RecordTypeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='totalRecords', full_name='PositionStorage.Delete.Msg.RecordTypeResult.totalRecords', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deletedRecords', full_name='PositionStorage.Delete.Msg.RecordTypeResult.deletedRecords', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recordType', full_name='PositionStorage.Delete.Msg.RecordTypeResult.recordType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failedRecordId', full_name='PositionStorage.Delete.Msg.RecordTypeResult.failedRecordId', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='PositionStorage.Delete.Msg.RecordTypeResult.errorMessage', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=399,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='PositionStorage.Delete.Msg.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recordTypeResults', full_name='PositionStorage.Delete.Msg.Result.recordTypeResults', index=0,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=482,
)


_RESULTKEY = _descriptor.Descriptor(
  name='ResultKey',
  full_name='PositionStorage.Delete.Msg.ResultKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PositionStorage.Delete.Msg.ResultKey.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=507,
)

_DEFINITION.fields_by_name['sessionFilter'].message_type = Contracts_Tk_Messages_TkMessages._FILTER
_DEFINITION.fields_by_name['columnFilter'].message_type = Contracts_Tk_Messages_TkMessages._FILTER
_DEFINITION.fields_by_name['positionFilter'].message_type = Contracts_Tk_Messages_TkMessages._FILTER
_RESULT.fields_by_name['recordTypeResults'].message_type = _RECORDTYPERESULT
DESCRIPTOR.message_types_by_name['Definition'] = _DEFINITION
DESCRIPTOR.message_types_by_name['RecordTypeResult'] = _RECORDTYPERESULT
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['ResultKey'] = _RESULTKEY

Definition = _reflection.GeneratedProtocolMessageType('Definition', (_message.Message,), dict(
  DESCRIPTOR = _DEFINITION,
  __module__ = 'PositionStorageDeleteMessages_pb2'
  # @@protoc_insertion_point(class_scope:PositionStorage.Delete.Msg.Definition)
  ))
_sym_db.RegisterMessage(Definition)

RecordTypeResult = _reflection.GeneratedProtocolMessageType('RecordTypeResult', (_message.Message,), dict(
  DESCRIPTOR = _RECORDTYPERESULT,
  __module__ = 'PositionStorageDeleteMessages_pb2'
  # @@protoc_insertion_point(class_scope:PositionStorage.Delete.Msg.RecordTypeResult)
  ))
_sym_db.RegisterMessage(RecordTypeResult)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'PositionStorageDeleteMessages_pb2'
  # @@protoc_insertion_point(class_scope:PositionStorage.Delete.Msg.Result)
  ))
_sym_db.RegisterMessage(Result)

ResultKey = _reflection.GeneratedProtocolMessageType('ResultKey', (_message.Message,), dict(
  DESCRIPTOR = _RESULTKEY,
  __module__ = 'PositionStorageDeleteMessages_pb2'
  # @@protoc_insertion_point(class_scope:PositionStorage.Delete.Msg.ResultKey)
  ))
_sym_db.RegisterMessage(ResultKey)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
