""" Compiled: 2015-09-23 14:33:50 """

# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='validationmessage2.proto',
  package='OrderValidation',
  serialized_pb='\n\x18validationmessage2.proto\x12\x0fOrderValidation\"s\n\nDefinition\x12\x15\n\rportfolio_oid\x18\x01 \x01(\x05\x12\x15\n\ractive_orders\x18\x02 \x01(\x08\x12\x1a\n\x12position_column_id\x18\x03 \x03(\t\x12\x1b\n\x13portfolio_column_id\x18\x04 \x03(\t\":\n\tResultKey\x12\x16\n\x0einstrument_oid\x18\x01 \x01(\x05\x12\x15\n\rportfolio_oid\x18\x02 \x01(\x05\"B\n\x10\x44\x65nominatedValue\x12\x0e\n\x06number\x18\x01 \x01(\x01\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\t\"\xac\x01\n\x07Variant\x12\x12\n\nbool_value\x18\x01 \x01(\x08\x12\x13\n\x0bint32_value\x18\x02 \x01(\x05\x12\x14\n\x0c\x64ouble_value\x18\x03 \x01(\x01\x12\x14\n\x0cstring_value\x18\x04 \x01(\t\x12\x33\n\x08\x64v_value\x18\x05 \x01(\x0b\x32!.OrderValidation.DenominatedValue\x12\x17\n\x0f\x65xception_value\x18\x06 \x01(\t\"\x9c\x01\n\x06Result\x12\x30\n\x0eposition_value\x18\x01 \x03(\x0b\x32\x18.OrderValidation.Variant\x12\x31\n\x0fportfolio_value\x18\x02 \x03(\x0b\x32\x18.OrderValidation.Variant\x12-\n\x0border_value\x18\x03 \x03(\x0b\x32\x18.OrderValidation.Variant')




_DEFINITION = descriptor.Descriptor(
  name='Definition',
  full_name='OrderValidation.Definition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='portfolio_oid', full_name='OrderValidation.Definition.portfolio_oid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='active_orders', full_name='OrderValidation.Definition.active_orders', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position_column_id', full_name='OrderValidation.Definition.position_column_id', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='portfolio_column_id', full_name='OrderValidation.Definition.portfolio_column_id', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=160,
)


_RESULTKEY = descriptor.Descriptor(
  name='ResultKey',
  full_name='OrderValidation.ResultKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='instrument_oid', full_name='OrderValidation.ResultKey.instrument_oid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='portfolio_oid', full_name='OrderValidation.ResultKey.portfolio_oid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=220,
)


_DENOMINATEDVALUE = descriptor.Descriptor(
  name='DenominatedValue',
  full_name='OrderValidation.DenominatedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='number', full_name='OrderValidation.DenominatedValue.number', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unit', full_name='OrderValidation.DenominatedValue.unit', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datetime', full_name='OrderValidation.DenominatedValue.datetime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=222,
  serialized_end=288,
)


_VARIANT = descriptor.Descriptor(
  name='Variant',
  full_name='OrderValidation.Variant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bool_value', full_name='OrderValidation.Variant.bool_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int32_value', full_name='OrderValidation.Variant.int32_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='double_value', full_name='OrderValidation.Variant.double_value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='string_value', full_name='OrderValidation.Variant.string_value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dv_value', full_name='OrderValidation.Variant.dv_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exception_value', full_name='OrderValidation.Variant.exception_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=str("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=291,
  serialized_end=463,
)


_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='OrderValidation.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='position_value', full_name='OrderValidation.Result.position_value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='portfolio_value', full_name='OrderValidation.Result.portfolio_value', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='order_value', full_name='OrderValidation.Result.order_value', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=466,
  serialized_end=622,
)

_VARIANT.fields_by_name['dv_value'].message_type = _DENOMINATEDVALUE
_RESULT.fields_by_name['position_value'].message_type = _VARIANT
_RESULT.fields_by_name['portfolio_value'].message_type = _VARIANT
_RESULT.fields_by_name['order_value'].message_type = _VARIANT
DESCRIPTOR.message_types_by_name['Definition'] = _DEFINITION
DESCRIPTOR.message_types_by_name['ResultKey'] = _RESULTKEY
DESCRIPTOR.message_types_by_name['DenominatedValue'] = _DENOMINATEDVALUE
DESCRIPTOR.message_types_by_name['Variant'] = _VARIANT
DESCRIPTOR.message_types_by_name['Result'] = _RESULT

class Definition(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEFINITION
  
  # @@protoc_insertion_point(class_scope:OrderValidation.Definition)

class ResultKey(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULTKEY
  
  # @@protoc_insertion_point(class_scope:OrderValidation.ResultKey)

class DenominatedValue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DENOMINATEDVALUE
  
  # @@protoc_insertion_point(class_scope:OrderValidation.DenominatedValue)

class Variant(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VARIANT
  
  # @@protoc_insertion_point(class_scope:OrderValidation.Variant)

class Result(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULT
  
  # @@protoc_insertion_point(class_scope:OrderValidation.Result)

# @@protoc_insertion_point(module_scope)
