""" Compiled: 2020-09-18 10:38:50 """

#__src_file__ = "extensions/corporate_actions_workbench/./etc/FCorporateActionsWorkbenchTradesCAPanel.py"
"""----------------------------------------------------------------------------
MODULE
    FCorporateActionsWorkbenchTradesCAPanel - Sheet to show CA trades

DESCRIPTION


ENDDESCRIPTION
----------------------------------------------------------------------------"""
import acm
from FEvent import EventCallback
from FSheetPanel import SheetPanel

class CorporateActionsWorkbenchTradesCAPanel(SheetPanel):

    def __init__(self):
        super(CorporateActionsWorkbenchTradesCAPanel, self).__init__()
        self._electionsByPortfolio = {}
        self._action = None

    @EventCallback
    def OnPortfoliosSelected(self, event):
        self._action = event.Action()
        folders = (self.CreateFolder(rowObj) for rowObj in event.Objects())
        self.Sheet().InsertObject(folders)
           
    def CreateFolder(self, rowObject):
        trades = rowObject.Trades()
        # trades are preselected to be all eligible trades 
        # plus trades generated by this corpaction
        caTrades = []
        for trade in trades:
            # this is a corporate action trade if
            # it is of type corporate action and has 
            # trade time >= exdate
            # we also check the business event
            if trade.Type() != 'Corporate Action':
                continue
            if trade.TradeTime() < self._action.ExDate():
                continue
            caTrades.append(trade)
        return caTrades
