""" Compiled: 2020-09-18 10:38:56 """

#__src_file__ = "extensions/RegulatoryInfo/../SwiftIntegration/RegulatoryInfo/General/Parameters/FRegulatoryNotificationConfig.py"
FREGULATORY_NOTIFICATION_MEDIA=OFF
FREGULATORY_NOTIFICATION_MESSAGE_BROKER=''
FREGULATORY_NOTIFY_LEVEL=WARNING
FREGULATORY_NOTIFY_USERS=''
FREGULATORY_SMTP_SERVER=''
FREGULATORY_USER_EMAILS=''