<?xml version='1.0' encoding='ISO-8859-1'?>
<FTradeFilter>
<owner>ATS</owner>
<protection>3072</protection>
<query>
[('', '', 'Counterparty', 'like', 'PRESCIENT IM', ''),
('Or', '', 'Counterparty', 'like', 'AEON', ''),
('Or', '', 'Counterparty', 'like', 'OASIS', ''),
('Or', '', 'Counterparty', 'like', 'TAQUANTA', ''),
('Or', '', 'Counterparty', 'like', 'PERSONAL TRUST', ''),
('Or', '', 'Counterparty', 'like', 'ELEMENT', ''),
('Or', '', 'Counterparty', 're_like', '^BOE', ''),
('Or', '', 'Counterparty', 'like', 'JM BUSHA', ''),
('Or', '', 'Counterparty', 'equal to', 'MITSUBISHI UFJ TRUST', ''),
('Or', '', 'Counterparty', 'like', 'ARGON', ''),
('Or', '', 'Counterparty', 'like', 'VUNANI F', ''),
('Or', '', 'Counterparty', 'like', 'ABSA PORTFOLIO MAN', ''),
('Or', '', 'Counterparty', 'like', 'ABSA ASSET MANAGEMENT', ''),
('Or', '', 'Counterparty', 'equal to', 'ABSA STOCKBROKERS AND PORTFOLIO MANAGEM', ''),
('Or', '', 'Counterparty', 'like', 'PROWESS', ''),
('Or', '', 'Counterparty', 'like', 'MELVILLE DOUGLAS', ''),
('Or', '', 'Counterparty', 'equal to', 'FIRSTRAND BANK LTD ATLANTIC POINT', ''),
('Or', '', 'Counterparty', 're_like', '^ATLANTIC AM', ''),
('Or', '', 'Counterparty', 'equal to', 'FIRSTRAND BANK LTD PSG HEDGE FUND', ''),
('Or', '', 'Counterparty', 'like', 'PSG PRIME', ''),
('Or', '', 'Counterparty', 'like', 'EFFICIENT', ''),
('Or', '', 'Counterparty', 'like', 'ABSA AM', ''),
('Or', '', 'Counterparty', 'like', 'COLOURFIELD', ''),
('Or', '', 'Counterparty', 'equal to', 'METAM PROFND', ''),
('Or', '', 'Counterparty', 'like', 'PRESCIENT LIFE', ''),
('Or', '', 'Counterparty', 'like', 'BANK WINDHOEK', ''),
('Or', '', 'Counterparty', 'like', 'BANK OF NAMIBIA', ''),
('Or', '', 'Counterparty', 'equal to', 'METAM AM INCFND', ''),
('Or', '', 'Counterparty', 'like', 'COUNTERPOINT', ''),
('Or', '', 'Counterparty', 'equal to', 'PRESCIENT SECURITIES PTY LTD', ''),
('Or', '', 'Counterparty', 're_like', '^HOLLARD', ''),
('Or', '', 'Counterparty', 'like', 'AIG', ''),
('Or', '', 'Counterparty', 're_like', '^ASHBURTON', ''),
('Or', '', 'Counterparty', 'like', 'AFENA', ''),
('Or', '', 'Counterparty', 'like', 'BALONDOLOZI', ''),
('Or', '', 'Counterparty', 'like', 'CONTEGO', ''),
('Or', '', 'Counterparty', 'equal to', 'CITY OF CAPE TOWN', ''),
('Or', '', 'Counterparty', 'like', 'FOORD', ''),
('Or', '', 'Counterparty', 'like', 'GRYPHON', ''),
('Or', '', 'Counterparty', 'like', 'HANNOVER', ''),
('Or', '', 'Counterparty', 'like', 'MARRIOTT', ''),
('Or', '', 'Counterparty', 'like', 'MVUNONALA', ''),
('Or', '', 'Counterparty', 'like', 'PERPETUA', ''),
('Or', '', 'Counterparty', 'like', 'RECM', ''),
('Or', '', 'Counterparty', 'like', 'REGENT', ''),
('Or', '', 'Counterparty', 'like', 'TANTALUM', ''),
('Or', '', 'Counterparty', 'like', 'TRUFFLE', ''),
('Or', '', 'Counterparty', 'like', 'WARWICK WEALTH', ''),
('Or', '', 'Counterparty', 'like', 'NORTHSTAR', ''),
('Or', '', 'Counterparty', 'like', 'REZCO', ''),
('Or', '', 'Counterparty', 'like', 'SASFIN', ''),
('Or', '', 'Counterparty', 'like', 'WARWICK', ''),
('Or', '', 'Counterparty', 'like', 'OMIG NAMIBIA', ''),
('Or', '', 'Counterparty', 'like', 'OMIGNAM', ''),
('Or', '', 'Counterparty', 'like', 'SOUTH EASTER', ''),
('Or', '', 'Counterparty', 'equal to', 'FIRSTRAND BANK LTD SOUTH EASTER', ''),
('Or', '', 'Counterparty', 'like', 'LIBERTY GROUP', ''),
('Or', '', 'Counterparty', 'like', 'LIBERTY IAM', ''),
('Or', '', 'Counterparty', 'like', 'CADIZ', ''),
('Or', '', 'Counterparty', 'equal to', 'FIRSTRAND BANK LTD LIMARCO 62', ''),
('Or', '', 'Counterparty', 'like', 'MMI GROUP', ''),
('Or', '', 'Counterparty', 'equal to', 'FIRSTRAND BANK LTD FAIRTREE CAPITAL', ''),
('Or', '', 'Counterparty', 'like', 'CARTESIAN CAPITAL', ''),
('Or', '', 'Counterparty', 'like', 'GR NEAM', ''),
('Or', '', 'Counterparty', 'equal to', 'ASHMORE INVESTMENT MANAGEMENT LIMITED', ''),
('Or', '', 'Counterparty', 'like', 'OM INVEST', '')
]
</query>
</FTradeFilter>
