<?xml version='1.0' encoding='ISO-8859-1'?>
<FTradeFilter>
<owner>ATS</owner>
<protection>3072</protection>
<query>
[('', '(', 'Status', 'equal to', 'FO Confirmed', ''),
('Or', '', 'Status', 'equal to', 'BO Confirmed', ''),
('Or', '', 'Status', 'equal to', 'BO-BO Confirmed', ')'),
('And', '', 'Optkey1: TradArea', 'not equal to', 'SPECIAL_FINANCE', ''),
('And', '', 'Instrument.Currency', 'equal to', 'ZAR', ''),
('And', '(', 'Value day', 'greater equal', '-15d', ''),
('Or', '', 'Instrument.Expiry day', 'greater equal', '-15d', ')'),
('And', '(', 'Counterparty.Type', 'equal to', 'Intern Dept', ''),
('Or', '', 'Counterparty', 'equal to', 'SECURITY LENDINGS DESK', ''),
('Or', '', 'Counterparty', 'equal to', 'DRA TRANSAKSIES', ')'),
('And', '(', 'Instrument.Type', 'equal to', 'Bond', ''),
('Or', '', 'Instrument.Type', 'equal to', 'IndexLinkedBond', ''),
('Or', '(', 'Instrument.Type', 'equal to', 'FRN', ''),
('And', '', 'Instrument.ISIN', 'like', 'ZAG%', ')'),
('Or', '', 'Instrument.Type', 'equal to', 'TotalReturnSwap', ''),
('Or', '', 'Instrument.Type', 'equal to', 'SecurityLoan', ''),
('Or', '', 'Instrument.Type', 'equal to', 'Future/Forward', ''),
('Or', '', 'Instrument.Type', 'equal to', 'BuySellback', ''),
('Or', '', 'Instrument.Type', 'equal to', 'Repo/Reverse', ')'),
('And', '(', 'Instrument.Underlying type', 'equal to', 'None', ''),
('Or', '', 'Instrument.Underlying type', 'equal to', 'Bond', ''),
('Or', '', 'Instrument.Underlying type', 'equal to', 'FRN', ''),
('Or', '', 'Instrument.Underlying type', 'equal to', 'IndexLinkedBond', ')'),
('And', '(', 'Portfolio', 'equal to', '9803CARRIES', ''),
('Or', '', 'Portfolio', 'equal to', 'GT Sub Debt Inflation', ''),
('Or', '', 'Portfolio', 'equal to', 'GT Sen Debt Inflation', ''),
('Or', '', 'Portfolio', 'equal to', 'GT Gov Inflation', ''),
('Or', '', 'Portfolio', 'equal to', 'GT CIB LA Repo', ''),
('Or', '', 'Portfolio', 'equal to', 'Call_9803', ''),
('Or', '', 'Portfolio', 'equal to', '9803_Short Term Surplus LA', ''),
('Or', '', 'Portfolio', 'equal to', '9803HFT', ''),
('Or', '', 'Portfolio', 'equal to', 'GT Homes1 Notes', ''),
('Or', '', 'Portfolio', 'equal to', '9803AFS_Bills', ''),
('Or', '', 'Portfolio', 'equal to', '9803_FV Bonds Hedged Futures', ''),
('Or', '', 'Portfolio', 'equal to', '9803AFS OUTRIGHT', ''),
('Or', '', 'Portfolio', 'equal to', '9803AFS HEDGED', ''),
('Or', '', 'Portfolio', 'equal to', 'GT LT Carries', ''),
('Or', '', 'Portfolio', 'equal to', 'ALBI/GOVI Structures', ''),
('Or', '', 'Portfolio', 'equal to', 'Allocate_Pfolio_GT', ''),
('Or', '', 'Portfolio', 'equal to', 'BB_Bonds', ''),
('Or', '', 'Portfolio', 'equal to', 'CD ACCRUALS 1574', ''),
('Or', '', 'Portfolio', 'equal to', 'CD_CORPBONDS', ''),
('Or', '', 'Portfolio', 'equal to', 'CD_CORPBONDS_NONCSA', ''),
('Or', '', 'Portfolio', 'equal to', 'CD_Corpbond_Repo', ''),
('Or', '', 'Portfolio', 'equal to', 'CD_GOVSWAP', ''),
('Or', '', 'Portfolio', 'equal to', 'CD_OFFSHOREvsDOMESTIC', ''),
('Or', '', 'Portfolio', 'equal to', 'CD_UNSECFIN_MTM', ''),
('Or', '', 'Portfolio', 'equal to', 'CD_UNSECFIN_MTM', ''),
('Or', '', 'Portfolio', 'equal to', 'Conduit Trading', ''),
('Or', '', 'Portfolio', 'equal to', 'DERV', ''),
('Or', '', 'Portfolio', 'equal to', 'DERV2', ''),
('Or', '', 'Portfolio', 'equal to', 'DERV3', ''),
('Or', '', 'Portfolio', 'equal to', 'DERV4', ''),
('Or', '', 'Portfolio', 'equal to', 'DERV5', ''),
('Or', '', 'Portfolio', 'equal to', 'DERV6', ''),
('Or', '', 'Portfolio', 'equal to', 'DERV7', ''),
('Or', '', 'Portfolio', 'equal to', 'DO_FI_Bonds', ''),
('Or', '', 'Portfolio', 'equal to', 'EA Bond Trading', ''),
('Or', '', 'Portfolio', 'equal to', 'EQ_SA_FITradingJV', ''),
('Or', '', 'Portfolio', 'equal to', 'FOREX SPOT BONDS', ''),
('Or', '', 'Portfolio', 'equal to', 'FX STRAT FUND', ''),
('Or', '', 'Portfolio', 'equal to', 'FX_RND_Bond_Trading', ''),
('Or', '', 'Portfolio', 'equal to', 'JV Risk Man', ''),
('Or', '', 'Portfolio', 'equal to', 'GK_BONDS', ''),
('Or', '', 'Portfolio', 'equal to', 'GK_SWAPS', ''),
('Or', '', 'Portfolio', 'equal to', 'GT Senior Debt', ''),
('Or', '', 'Portfolio', 'equal to', 'ILBI/IGOV Structures', ''),
('Or', '', 'Portfolio', 'equal to', 'IRD FAIR VALUE NOTES', ''),
('Or', '', 'Portfolio', 'equal to', 'JN_BONDS', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB10', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB11', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB12', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB13', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB15', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB16', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB2', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB3', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB4', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB5', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB7', ''),
('Or', '', 'Portfolio', 'equal to', 'JOB8', ''),
('Or', '', 'Portfolio', 'equal to', 'JOBX1', ''),
('Or', '', 'Portfolio', 'equal to', 'LIQ Trading', ''),
('Or', '', 'Portfolio', 'equal to', 'Mapps Growth 41129', ''),
('Or', '', 'Portfolio', 'equal to', 'Mapps Protector 41137', ''),
('Or', '', 'Portfolio', 'equal to', 'MONY 9802', ''),
('Or', '', 'Portfolio', 'equal to', 'NewFunds GOVI ETF', ''),
('Or', '', 'Portfolio', 'equal to', 'NewFunds ILBI ETF', ''),
('Or', '', 'Portfolio', 'equal to', 'NVL Risk', ''),
('Or', '', 'Portfolio', 'equal to', 'PB_FEES_OAKHAVEN', ''),
('Or', '', 'Portfolio', 'equal to', 'PB_RISK_FV_CLIENTBONDS', ''),
('Or', '', 'Portfolio', 'equal to', 'PB_RISK_FV_INTERMED_RIDGCAP', ''),
('Or', '', 'Portfolio', 'equal to', 'Portfolio Risk Management', ''),
('Or', '', 'Portfolio', 'equal to', 'Prime optimize', ''),
('Or', '', 'Portfolio', 'equal to', 'RAJ - Bonds', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL SNP Bond Collateral Loans', ''),
('Or', '', 'Portfolio', 'equal to', 'ST Bond Collateral', ''),
('Or', '', 'Portfolio', 'equal to', 'ST Playground', ''),
('Or', '', 'Portfolio', 'equal to', 'ST Rates Risk', ''),
('Or', '', 'Portfolio', 'equal to', 'STIRT-Bonds', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL COMPLEX FICC SNP BOND COLLATERAL LO', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL_MAPPS_Bonds', ''),
('Or', '', 'Portfolio', 'equal to', 'Synthetic Bond Structures', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL_Fixed Income_ University Free State', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL_Fixed Income_ Unisa', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL_Fixed Income National Tertiary RF', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL_Fixed Income Denel RF', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL_Fixed Income Denel', ''),
('Or', '', 'Portfolio', 'equal to', 'Swap_Bonds', ''),
('Or', '', 'Portfolio', 'equal to', 'Swap Flow', ''),
('Or', '', 'Portfolio', 'equal to', 'NN Bonds', ''),
('Or', '', 'Portfolio', 'equal to', 'SBL ETF - Trading Bonds', ''),
('Or', '', 'Portfolio', 'equal to', '40592', ''),
('Or', '', 'Portfolio', 'equal to', 'SND Credit BTB FV', ')')
]
</query>
</FTradeFilter>
