""" Compiled: 2020-09-18 10:38:55 """

#__src_file__ = "extensions/BrokerageRisk/etc/FACABTradingLimitMessages.py"
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FACABTradingLimitMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FACABTradingLimitMessages.proto',
  package='FACABTradingLimit',
  serialized_pb=_b('\n\x1f\x46\x41\x43\x41\x42TradingLimitMessages.proto\x12\x11\x46\x41\x43\x41\x42TradingLimit\"8\n\nDefinition\x12\x12\n\ncreateUser\x18\x01 \x01(\t\x12\x16\n\x0emarketserverid\x18\x02 \x01(\t\"1\n\tResultKey\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x13\n\x0borderbookid\x18\x02 \x01(\t\"\xbc\x03\n\x06Result\x12\x18\n\x10minOrderQuantity\x18\x01 \x01(\x01\x12\x18\n\x10maxOrderQuantity\x18\x02 \x01(\x01\x12\x15\n\rminOrderValue\x18\x03 \x01(\x01\x12\x15\n\rmaxOrderValue\x18\x04 \x01(\x01\x12\x1c\n\x14maxBuyQuantityPerDay\x18\x05 \x01(\x01\x12\x1d\n\x15maxSellQuantityPerDay\x18\x06 \x01(\x01\x12\x1e\n\x16maxGrossQuantityPerDay\x18\x07 \x01(\x01\x12\x1c\n\x14maxNetQuantityPerDay\x18\x08 \x01(\x01\x12\x19\n\x11maxBuyValuePerDay\x18\t \x01(\x01\x12\x1a\n\x12maxSellValuePerDay\x18\n \x01(\x01\x12\x1f\n\x17maxShortSellValuePerDay\x18\x0b \x01(\x01\x12\x1b\n\x13maxGrossValuePerDay\x18\x0c \x01(\x01\x12\x16\n\x0emaxOrderPerDay\x18\r \x01(\r\x12\x18\n\x10maxOrderActivity\x18\x0e \x01(\r\x12\x1c\n\x14maxOrderActivityTime\x18\x0f \x01(\r\x12\x10\n\x08\x63urrency\x18\x10 \x01(\tB\x12\n\x0e\x63om.frontarenaH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEFINITION = _descriptor.Descriptor(
  name='Definition',
  full_name='FACABTradingLimit.Definition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='createUser', full_name='FACABTradingLimit.Definition.createUser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marketserverid', full_name='FACABTradingLimit.Definition.marketserverid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=110,
)


_RESULTKEY = _descriptor.Descriptor(
  name='ResultKey',
  full_name='FACABTradingLimit.ResultKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='FACABTradingLimit.ResultKey.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderbookid', full_name='FACABTradingLimit.ResultKey.orderbookid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=161,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='FACABTradingLimit.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minOrderQuantity', full_name='FACABTradingLimit.Result.minOrderQuantity', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxOrderQuantity', full_name='FACABTradingLimit.Result.maxOrderQuantity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minOrderValue', full_name='FACABTradingLimit.Result.minOrderValue', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxOrderValue', full_name='FACABTradingLimit.Result.maxOrderValue', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxBuyQuantityPerDay', full_name='FACABTradingLimit.Result.maxBuyQuantityPerDay', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxSellQuantityPerDay', full_name='FACABTradingLimit.Result.maxSellQuantityPerDay', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxGrossQuantityPerDay', full_name='FACABTradingLimit.Result.maxGrossQuantityPerDay', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxNetQuantityPerDay', full_name='FACABTradingLimit.Result.maxNetQuantityPerDay', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxBuyValuePerDay', full_name='FACABTradingLimit.Result.maxBuyValuePerDay', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxSellValuePerDay', full_name='FACABTradingLimit.Result.maxSellValuePerDay', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxShortSellValuePerDay', full_name='FACABTradingLimit.Result.maxShortSellValuePerDay', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxGrossValuePerDay', full_name='FACABTradingLimit.Result.maxGrossValuePerDay', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxOrderPerDay', full_name='FACABTradingLimit.Result.maxOrderPerDay', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxOrderActivity', full_name='FACABTradingLimit.Result.maxOrderActivity', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxOrderActivityTime', full_name='FACABTradingLimit.Result.maxOrderActivityTime', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='FACABTradingLimit.Result.currency', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=608,
)

DESCRIPTOR.message_types_by_name['Definition'] = _DEFINITION
DESCRIPTOR.message_types_by_name['ResultKey'] = _RESULTKEY
DESCRIPTOR.message_types_by_name['Result'] = _RESULT

Definition = _reflection.GeneratedProtocolMessageType('Definition', (_message.Message,), dict(
  DESCRIPTOR = _DEFINITION,
  __module__ = 'FACABTradingLimitMessages_pb2'
  # @@protoc_insertion_point(class_scope:FACABTradingLimit.Definition)
  ))
_sym_db.RegisterMessage(Definition)

ResultKey = _reflection.GeneratedProtocolMessageType('ResultKey', (_message.Message,), dict(
  DESCRIPTOR = _RESULTKEY,
  __module__ = 'FACABTradingLimitMessages_pb2'
  # @@protoc_insertion_point(class_scope:FACABTradingLimit.ResultKey)
  ))
_sym_db.RegisterMessage(ResultKey)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'FACABTradingLimitMessages_pb2'
  # @@protoc_insertion_point(class_scope:FACABTradingLimit.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\016com.frontarenaH\003'))
# @@protoc_insertion_point(module_scope)