""" Compiled: 2020-09-18 10:38:55 """

#__src_file__ = "extensions/BrokerageRisk/etc/FXReferenceRateMessages.py"
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FXReferenceRateMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FXReferenceRateMessages.proto',
  package='FXReferenceRate',
  serialized_pb=_b('\n\x1d\x46XReferenceRateMessages.proto\x12\x0f\x46XReferenceRate\"8\n\nDefinition\x12\x12\n\ncreateUser\x18\x01 \x01(\t\x12\x16\n\x0emarketserverid\x18\x02 \x01(\t\"5\n\tResultKey\x12\x14\n\x0c\x66romCurrency\x18\x01 \x01(\t\x12\x12\n\ntoCurrency\x18\x02 \x01(\t\"!\n\x06Result\x12\x17\n\x0f\x66xReferenceRate\x18\x01 \x01(\x01\x42+\n\x0e\x63om.frontarenaB\x17\x46XReferenceRateMessagesH\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEFINITION = _descriptor.Descriptor(
  name='Definition',
  full_name='FXReferenceRate.Definition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='createUser', full_name='FXReferenceRate.Definition.createUser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marketserverid', full_name='FXReferenceRate.Definition.marketserverid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=106,
)


_RESULTKEY = _descriptor.Descriptor(
  name='ResultKey',
  full_name='FXReferenceRate.ResultKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromCurrency', full_name='FXReferenceRate.ResultKey.fromCurrency', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toCurrency', full_name='FXReferenceRate.ResultKey.toCurrency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=161,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='FXReferenceRate.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fxReferenceRate', full_name='FXReferenceRate.Result.fxReferenceRate', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['Definition'] = _DEFINITION
DESCRIPTOR.message_types_by_name['ResultKey'] = _RESULTKEY
DESCRIPTOR.message_types_by_name['Result'] = _RESULT

Definition = _reflection.GeneratedProtocolMessageType('Definition', (_message.Message,), dict(
  DESCRIPTOR = _DEFINITION,
  __module__ = 'FXReferenceRateMessages_pb2'
  # @@protoc_insertion_point(class_scope:FXReferenceRate.Definition)
  ))
_sym_db.RegisterMessage(Definition)

ResultKey = _reflection.GeneratedProtocolMessageType('ResultKey', (_message.Message,), dict(
  DESCRIPTOR = _RESULTKEY,
  __module__ = 'FXReferenceRateMessages_pb2'
  # @@protoc_insertion_point(class_scope:FXReferenceRate.ResultKey)
  ))
_sym_db.RegisterMessage(ResultKey)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'FXReferenceRateMessages_pb2'
  # @@protoc_insertion_point(class_scope:FXReferenceRate.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\016com.frontarenaB\027FXReferenceRateMessagesH\003'))
# @@protoc_insertion_point(module_scope)